// -------------------------------------------------------------
// 
// File Name: G:\AI\IIT BHU\codegen\shiftmul16\hdlsrc\shiftmul16_FixPt.v
// Created: 2016-06-07 17:01:02
// 
// Generated by MATLAB 8.1, MATLAB Coder 2.4 and HDL Coder 3.2
// 
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Design base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ceout         1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// y1                            ceout         1
// y3                            ceout         1
// y5                            ceout         1
// y7                            ceout         1
// y9                            ceout         1
// y11                           ceout         1
// y13                           ceout         1
// y15                           ceout         1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: shiftmul16_FixPt
// Source Path: shiftmul16_FixPt
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module shiftmul16_FixPt
          (
           clk,
           reset,
           clkenable,
           b1,
           b2,
           b3,
           b4,
           b5,
           b6,
           b7,
           b8,
           ceout,
           y1,
           y3,
           y5,
           y7,
           y9,
           y11,
           y13,
           y15
          );


  input   clk;
  input   reset;
  input   clkenable;
  input   [1:0] b1;  // ufix2
  input   [1:0] b2;  // ufix2
  input   [1:0] b3;  // ufix2
  input   [1:0] b4;  // ufix2
  input   [1:0] b5;  // ufix2
  input   [1:0] b6;  // ufix2
  input   [1:0] b7;  // ufix2
  input   [1:0] b8;  // ufix2
  output  ceout;
  output  [7:0] y1;  // ufix8
  output  [3:0] y3;  // ufix4
  output  [6:0] y5;  // ufix7
  output  signed [2:0] y7;  // sfix3
  output  [5:0] y9;  // ufix6
  output  [7:0] y11;  // ufix8
  output  [7:0] y13;  // ufix8
  output  [5:0] y15;  // ufix6


  wire enb;
  wire [1:0] shiftmul16_FixPt_d1;  // ufix2
  wire [1:0] shiftmul16_FixPt_d2;  // ufix2
  wire [1:0] shiftmul16_FixPt_d3;  // ufix2
  wire [1:0] shiftmul16_FixPt_d4;  // ufix2
  wire [1:0] shiftmul16_FixPt_d5;  // ufix2
  wire [1:0] shiftmul16_FixPt_d6;  // ufix2
  wire [1:0] shiftmul16_FixPt_d7;  // ufix2
  wire [1:0] shiftmul16_FixPt_d8;  // ufix2
  wire [1:0] shiftmul16_FixPt_d1_1;  // ufix2
  wire [1:0] shiftmul16_FixPt_d2_1;  // ufix2
  wire [8:0] shiftmul16_FixPt_add_temp;  // ufix9
  wire [9:0] shiftmul16_FixPt_add_temp_1;  // ufix10
  wire [1:0] shiftmul16_FixPt_d4_1;  // ufix2
  wire [14:0] shiftmul16_FixPt_add_temp_2;  // ufix15
  wire [18:0] shiftmul16_FixPt_add_temp_3;  // ufix19
  wire [1:0] shiftmul16_FixPt_d6_1;  // ufix2
  wire [21:0] shiftmul16_FixPt_add_temp_4;  // ufix22
  wire [22:0] shiftmul16_FixPt_add_temp_5;  // ufix23
  wire [1:0] shiftmul16_FixPt_d7_1;  // ufix2
  wire [25:0] shiftmul16_FixPt_add_temp_6;  // ufix26
  wire [1:0] shiftmul16_FixPt_d6_2;  // ufix2
  wire [1:0] shiftmul16_FixPt_d1_2;  // ufix2
  wire signed [9:0] shiftmul16_FixPt_add_temp_7;  // sfix10
  wire signed [10:0] shiftmul16_FixPt_add_temp_8;  // sfix11
  wire [1:0] shiftmul16_FixPt_d7_2;  // ufix2
  wire signed [15:0] shiftmul16_FixPt_sub_temp;  // sfix16
  wire signed [19:0] shiftmul16_FixPt_add_temp_9;  // sfix20
  wire [1:0] shiftmul16_FixPt_d4_2;  // ufix2
  wire signed [22:0] shiftmul16_FixPt_sub_temp_1;  // sfix23
  wire signed [23:0] shiftmul16_FixPt_sub_temp_2;  // sfix24
  wire [1:0] shiftmul16_FixPt_d8_1;  // ufix2
  wire signed [26:0] shiftmul16_FixPt_sub_temp_3;  // sfix27
  wire signed [28:0] shiftmul16_FixPt_add_temp_10;  // sfix29
  wire [1:0] shiftmul16_FixPt_d7_3;  // ufix2
  wire [1:0] shiftmul16_FixPt_d4_3;  // ufix2
  wire [8:0] shiftmul16_FixPt_sub_temp_4;  // ufix9
  wire [9:0] shiftmul16_FixPt_sub_temp_5;  // ufix10
  wire [1:0] shiftmul16_FixPt_d3_1;  // ufix2
  wire [14:0] shiftmul16_FixPt_sub_temp_6;  // ufix15
  wire [18:0] shiftmul16_FixPt_add_temp_11;  // ufix19
  wire [1:0] shiftmul16_FixPt_d8_2;  // ufix2
  wire [21:0] shiftmul16_FixPt_add_temp_12;  // ufix22
  wire [22:0] shiftmul16_FixPt_add_temp_13;  // ufix23
  wire [1:0] shiftmul16_FixPt_d5_1;  // ufix2
  wire [25:0] shiftmul16_FixPt_sub_temp_7;  // ufix26
  wire [1:0] shiftmul16_FixPt_d5_2;  // ufix2
  wire [1:0] shiftmul16_FixPt_d3_2;  // ufix2
  wire [8:0] shiftmul16_FixPt_sub_temp_8;  // ufix9
  wire [9:0] shiftmul16_FixPt_sub_temp_9;  // ufix10
  wire [1:0] shiftmul16_FixPt_d1_3;  // ufix2
  wire [14:0] shiftmul16_FixPt_add_temp_14;  // ufix15
  wire [18:0] shiftmul16_FixPt_sub_temp_10;  // ufix19
  wire [1:0] shiftmul16_FixPt_d2_2;  // ufix2
  wire [21:0] shiftmul16_FixPt_sub_temp_11;  // ufix22
  wire [22:0] shiftmul16_FixPt_sub_temp_12;  // ufix23
  wire [1:0] shiftmul16_FixPt_d6_3;  // ufix2
  wire [25:0] shiftmul16_FixPt_add_temp_15;  // ufix26
  wire [27:0] shiftmul16_FixPt_add_temp_16;  // ufix28
  wire [1:0] shiftmul16_FixPt_d4_4;  // ufix2
  wire [1:0] shiftmul16_FixPt_d6_4;  // ufix2
  wire [8:0] shiftmul16_FixPt_sub_temp_13;  // ufix9
  wire [9:0] shiftmul16_FixPt_sub_temp_14;  // ufix10
  wire [1:0] shiftmul16_FixPt_d8_3;  // ufix2
  wire [14:0] shiftmul16_FixPt_add_temp_17;  // ufix15
  wire [18:0] shiftmul16_FixPt_add_temp_18;  // ufix19
  wire [1:0] shiftmul16_FixPt_d7_4;  // ufix2
  wire [21:0] shiftmul16_FixPt_add_temp_19;  // ufix22
  wire [22:0] shiftmul16_FixPt_add_temp_20;  // ufix23
  wire [1:0] shiftmul16_FixPt_d3_3;  // ufix2
  wire [25:0] shiftmul16_FixPt_sub_temp_15;  // ufix26
  wire [1:0] shiftmul16_FixPt_d2_3;  // ufix2
  wire [1:0] shiftmul16_FixPt_d5_3;  // ufix2
  wire signed [9:0] shiftmul16_FixPt_sub_temp_16;  // sfix10
  wire signed [10:0] shiftmul16_FixPt_sub_temp_17;  // sfix11
  wire [1:0] shiftmul16_FixPt_d6_5;  // ufix2
  wire signed [15:0] shiftmul16_FixPt_add_temp_21;  // sfix16
  wire signed [19:0] shiftmul16_FixPt_add_temp_22;  // sfix20
  wire [1:0] shiftmul16_FixPt_d1_4;  // ufix2
  wire signed [22:0] shiftmul16_FixPt_add_temp_23;  // sfix23
  wire signed [23:0] shiftmul16_FixPt_add_temp_24;  // sfix24
  wire [1:0] shiftmul16_FixPt_d4_5;  // ufix2
  wire signed [26:0] shiftmul16_FixPt_add_temp_25;  // sfix27
  wire signed [28:0] shiftmul16_FixPt_add_temp_26;  // sfix29
  wire [1:0] shiftmul16_FixPt_d3_4;  // ufix2
  wire [1:0] shiftmul16_FixPt_d8_4;  // ufix2
  wire [8:0] shiftmul16_FixPt_add_temp_27;  // ufix9
  wire [9:0] shiftmul16_FixPt_add_temp_28;  // ufix10
  wire [1:0] shiftmul16_FixPt_d2_4;  // ufix2
  wire [14:0] shiftmul16_FixPt_sub_temp_18;  // ufix15
  wire [18:0] shiftmul16_FixPt_sub_temp_19;  // ufix19
  wire [1:0] shiftmul16_FixPt_d5_4;  // ufix2
  wire [21:0] shiftmul16_FixPt_add_temp_29;  // ufix22
  wire [22:0] shiftmul16_FixPt_add_temp_30;  // ufix23
  wire [1:0] shiftmul16_FixPt_d1_5;  // ufix2
  wire [25:0] shiftmul16_FixPt_add_temp_31;  // ufix26
  wire [1:0] shiftmul16_FixPt_d8_5;  // ufix2
  wire [1:0] shiftmul16_FixPt_d7_5;  // ufix2
  wire signed [9:0] shiftmul16_FixPt_add_temp_32;  // sfix10
  wire signed [10:0] shiftmul16_FixPt_add_temp_33;  // sfix11
  wire [1:0] shiftmul16_FixPt_d6_6;  // ufix2
  wire signed [15:0] shiftmul16_FixPt_sub_temp_20;  // sfix16
  wire signed [19:0] shiftmul16_FixPt_sub_temp_21;  // sfix20
  wire [1:0] shiftmul16_FixPt_d3_5;  // ufix2
  wire signed [22:0] shiftmul16_FixPt_add_temp_34;  // sfix23
  wire signed [23:0] shiftmul16_FixPt_add_temp_35;  // sfix24
  wire [1:0] shiftmul16_FixPt_d2_5;  // ufix2
  wire signed [26:0] shiftmul16_FixPt_sub_temp_22;  // sfix27
  wire signed [28:0] shiftmul16_FixPt_add_temp_36;  // sfix29


  assign enb = clkenable;

  //spssa
  //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  //                                                                          %
  //        Generated by MATLAB 8.1, MATLAB Coder 2.4 and HDL Coder 3.2      %
  //                                                                          %
  //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  assign shiftmul16_FixPt_d1 = b1;
  assign shiftmul16_FixPt_d2 = b2;
  assign shiftmul16_FixPt_d3 = b3;
  assign shiftmul16_FixPt_d4 = b4;
  assign shiftmul16_FixPt_d5 = b5;
  assign shiftmul16_FixPt_d6 = b6;
  assign shiftmul16_FixPt_d7 = b7;
  assign shiftmul16_FixPt_d8 = b8;
  assign shiftmul16_FixPt_d1_1 = shiftmul16_FixPt_d1 <<< 1;
  assign shiftmul16_FixPt_d2_1 = shiftmul16_FixPt_d2 <<< 1;
  assign shiftmul16_FixPt_add_temp = shiftmul16_FixPt_d1_1 + shiftmul16_FixPt_d2_1;
  assign shiftmul16_FixPt_add_temp_1 = shiftmul16_FixPt_add_temp + b2;
  assign shiftmul16_FixPt_d4_1 = shiftmul16_FixPt_d4 <<< 1;
  assign shiftmul16_FixPt_add_temp_2 = shiftmul16_FixPt_add_temp_1 + shiftmul16_FixPt_d4_1;
  assign shiftmul16_FixPt_add_temp_3 = shiftmul16_FixPt_add_temp_2 + b5;
  assign shiftmul16_FixPt_d6_1 = shiftmul16_FixPt_d6 <<< 1;
  assign shiftmul16_FixPt_add_temp_4 = shiftmul16_FixPt_add_temp_3 + shiftmul16_FixPt_d6_1;
  assign shiftmul16_FixPt_add_temp_5 = shiftmul16_FixPt_add_temp_4 + b6;
  assign shiftmul16_FixPt_d7_1 = shiftmul16_FixPt_d7 <<< 1;
  assign shiftmul16_FixPt_add_temp_6 = shiftmul16_FixPt_add_temp_5 + shiftmul16_FixPt_d7_1;
  assign y1 = shiftmul16_FixPt_add_temp_6 + b8;
  assign shiftmul16_FixPt_d6_2 = shiftmul16_FixPt_d6 <<< 1;
  assign shiftmul16_FixPt_d1_2 = shiftmul16_FixPt_d1 <<< 1;
  assign shiftmul16_FixPt_add_temp_7 = ( - (shiftmul16_FixPt_d6_2)) + $signed({1'b0, shiftmul16_FixPt_d1_2});
  assign shiftmul16_FixPt_add_temp_8 = shiftmul16_FixPt_add_temp_7 + $signed({1'b0, b1});
  assign shiftmul16_FixPt_d7_2 = shiftmul16_FixPt_d7 <<< 1;
  assign shiftmul16_FixPt_sub_temp = shiftmul16_FixPt_add_temp_8 - $signed({1'b0, shiftmul16_FixPt_d7_2});
  assign shiftmul16_FixPt_add_temp_9 = shiftmul16_FixPt_sub_temp + $signed({1'b0, b2});
  assign shiftmul16_FixPt_d4_2 = shiftmul16_FixPt_d4 <<< 1;
  assign shiftmul16_FixPt_sub_temp_1 = shiftmul16_FixPt_add_temp_9 - $signed({1'b0, shiftmul16_FixPt_d4_2});
  assign shiftmul16_FixPt_sub_temp_2 = shiftmul16_FixPt_sub_temp_1 - $signed({1'b0, b4});
  assign shiftmul16_FixPt_d8_1 = shiftmul16_FixPt_d8 <<< 1;
  assign shiftmul16_FixPt_sub_temp_3 = shiftmul16_FixPt_sub_temp_2 - $signed({1'b0, shiftmul16_FixPt_d8_1});
  assign shiftmul16_FixPt_add_temp_10 = shiftmul16_FixPt_sub_temp_3 + $signed({1'b0, b3});
  assign y3 = shiftmul16_FixPt_add_temp_10[3:0];
  assign shiftmul16_FixPt_d7_3 = shiftmul16_FixPt_d7 <<< 1;
  assign shiftmul16_FixPt_d4_3 = shiftmul16_FixPt_d4 <<< 1;
  assign shiftmul16_FixPt_sub_temp_4 = shiftmul16_FixPt_d7_3 - shiftmul16_FixPt_d4_3;
  assign shiftmul16_FixPt_sub_temp_5 = shiftmul16_FixPt_sub_temp_4 - b4;
  assign shiftmul16_FixPt_d3_1 = shiftmul16_FixPt_d3 <<< 1;
  assign shiftmul16_FixPt_sub_temp_6 = shiftmul16_FixPt_sub_temp_5 - shiftmul16_FixPt_d3_1;
  assign shiftmul16_FixPt_add_temp_11 = shiftmul16_FixPt_sub_temp_6 + b6;
  assign shiftmul16_FixPt_d8_2 = shiftmul16_FixPt_d8 <<< 1;
  assign shiftmul16_FixPt_add_temp_12 = shiftmul16_FixPt_add_temp_11 + shiftmul16_FixPt_d8_2;
  assign shiftmul16_FixPt_add_temp_13 = shiftmul16_FixPt_add_temp_12 + b8;
  assign shiftmul16_FixPt_d5_1 = shiftmul16_FixPt_d5 <<< 1;
  assign shiftmul16_FixPt_sub_temp_7 = shiftmul16_FixPt_add_temp_13 - shiftmul16_FixPt_d5_1;
  assign y5 = shiftmul16_FixPt_sub_temp_7 + b2;
  assign shiftmul16_FixPt_d5_2 = shiftmul16_FixPt_d5 <<< 1;
  assign shiftmul16_FixPt_d3_2 = shiftmul16_FixPt_d3 <<< 1;
  assign shiftmul16_FixPt_sub_temp_8 = shiftmul16_FixPt_d5_2 - shiftmul16_FixPt_d3_2;
  assign shiftmul16_FixPt_sub_temp_9 = shiftmul16_FixPt_sub_temp_8 - b3;
  assign shiftmul16_FixPt_d1_3 = shiftmul16_FixPt_d1 <<< 1;
  assign shiftmul16_FixPt_add_temp_14 = shiftmul16_FixPt_sub_temp_9 + shiftmul16_FixPt_d1_3;
  assign shiftmul16_FixPt_sub_temp_10 = shiftmul16_FixPt_add_temp_14 - b8;
  assign shiftmul16_FixPt_d2_2 = shiftmul16_FixPt_d2 <<< 1;
  assign shiftmul16_FixPt_sub_temp_11 = shiftmul16_FixPt_sub_temp_10 - shiftmul16_FixPt_d2_2;
  assign shiftmul16_FixPt_sub_temp_12 = shiftmul16_FixPt_sub_temp_11 - b2;
  assign shiftmul16_FixPt_d6_3 = shiftmul16_FixPt_d6 <<< 1;
  assign shiftmul16_FixPt_add_temp_15 = shiftmul16_FixPt_sub_temp_12 + shiftmul16_FixPt_d6_3;
  assign shiftmul16_FixPt_add_temp_16 = shiftmul16_FixPt_add_temp_15 + b4;
  assign y7 = $signed(shiftmul16_FixPt_add_temp_16[2:0]);
  assign shiftmul16_FixPt_d4_4 = shiftmul16_FixPt_d4 <<< 1;
  assign shiftmul16_FixPt_d6_4 = shiftmul16_FixPt_d6 <<< 1;
  assign shiftmul16_FixPt_sub_temp_13 = shiftmul16_FixPt_d4_4 - shiftmul16_FixPt_d6_4;
  assign shiftmul16_FixPt_sub_temp_14 = shiftmul16_FixPt_sub_temp_13 - b6;
  assign shiftmul16_FixPt_d8_3 = shiftmul16_FixPt_d8 <<< 1;
  assign shiftmul16_FixPt_add_temp_17 = shiftmul16_FixPt_sub_temp_14 + shiftmul16_FixPt_d8_3;
  assign shiftmul16_FixPt_add_temp_18 = shiftmul16_FixPt_add_temp_17 + b1;
  assign shiftmul16_FixPt_d7_4 = shiftmul16_FixPt_d7 <<< 1;
  assign shiftmul16_FixPt_add_temp_19 = shiftmul16_FixPt_add_temp_18 + shiftmul16_FixPt_d7_4;
  assign shiftmul16_FixPt_add_temp_20 = shiftmul16_FixPt_add_temp_19 + b7;
  assign shiftmul16_FixPt_d3_3 = shiftmul16_FixPt_d3 <<< 1;
  assign shiftmul16_FixPt_sub_temp_15 = shiftmul16_FixPt_add_temp_20 - shiftmul16_FixPt_d3_3;
  assign y9 = shiftmul16_FixPt_sub_temp_15 - b5;
  assign shiftmul16_FixPt_d2_3 = shiftmul16_FixPt_d2 <<< 1;
  assign shiftmul16_FixPt_d5_3 = shiftmul16_FixPt_d5 <<< 1;
  assign shiftmul16_FixPt_sub_temp_16 = ( - (shiftmul16_FixPt_d2_3)) - $signed({1'b0, shiftmul16_FixPt_d5_3});
  assign shiftmul16_FixPt_sub_temp_17 = shiftmul16_FixPt_sub_temp_16 - $signed({1'b0, b5});
  assign shiftmul16_FixPt_d6_5 = shiftmul16_FixPt_d6 <<< 1;
  assign shiftmul16_FixPt_add_temp_21 = shiftmul16_FixPt_sub_temp_17 + $signed({1'b0, shiftmul16_FixPt_d6_5});
  assign shiftmul16_FixPt_add_temp_22 = shiftmul16_FixPt_add_temp_21 + $signed({1'b0, b3});
  assign shiftmul16_FixPt_d1_4 = shiftmul16_FixPt_d1 <<< 1;
  assign shiftmul16_FixPt_add_temp_23 = shiftmul16_FixPt_add_temp_22 + $signed({1'b0, shiftmul16_FixPt_d1_4});
  assign shiftmul16_FixPt_add_temp_24 = shiftmul16_FixPt_add_temp_23 + $signed({1'b0, b1});
  assign shiftmul16_FixPt_d4_5 = shiftmul16_FixPt_d4 <<< 1;
  assign shiftmul16_FixPt_add_temp_25 = shiftmul16_FixPt_add_temp_24 + $signed({1'b0, shiftmul16_FixPt_d4_5});
  assign shiftmul16_FixPt_add_temp_26 = shiftmul16_FixPt_add_temp_25 + $signed({1'b0, b7});
  assign y11 = shiftmul16_FixPt_add_temp_26[7:0];
  assign shiftmul16_FixPt_d3_4 = shiftmul16_FixPt_d3 <<< 1;
  assign shiftmul16_FixPt_d8_4 = shiftmul16_FixPt_d8 <<< 1;
  assign shiftmul16_FixPt_add_temp_27 = shiftmul16_FixPt_d3_4 + shiftmul16_FixPt_d8_4;
  assign shiftmul16_FixPt_add_temp_28 = shiftmul16_FixPt_add_temp_27 + b8;
  assign shiftmul16_FixPt_d2_4 = shiftmul16_FixPt_d2 <<< 1;
  assign shiftmul16_FixPt_sub_temp_18 = shiftmul16_FixPt_add_temp_28 - shiftmul16_FixPt_d2_4;
  assign shiftmul16_FixPt_sub_temp_19 = shiftmul16_FixPt_sub_temp_18 - b7;
  assign shiftmul16_FixPt_d5_4 = shiftmul16_FixPt_d5 <<< 1;
  assign shiftmul16_FixPt_add_temp_29 = shiftmul16_FixPt_sub_temp_19 + shiftmul16_FixPt_d5_4;
  assign shiftmul16_FixPt_add_temp_30 = shiftmul16_FixPt_add_temp_29 + b5;
  assign shiftmul16_FixPt_d1_5 = shiftmul16_FixPt_d1 <<< 1;
  assign shiftmul16_FixPt_add_temp_31 = shiftmul16_FixPt_add_temp_30 + shiftmul16_FixPt_d1_5;
  assign y13 = shiftmul16_FixPt_add_temp_31 + b6;
  assign shiftmul16_FixPt_d8_5 = shiftmul16_FixPt_d8 <<< 1;
  assign shiftmul16_FixPt_d7_5 = shiftmul16_FixPt_d7 <<< 1;
  assign shiftmul16_FixPt_add_temp_32 = ( - (shiftmul16_FixPt_d8_5)) + $signed({1'b0, shiftmul16_FixPt_d7_5});
  assign shiftmul16_FixPt_add_temp_33 = shiftmul16_FixPt_add_temp_32 + $signed({1'b0, b7});
  assign shiftmul16_FixPt_d6_6 = shiftmul16_FixPt_d6 <<< 1;
  assign shiftmul16_FixPt_sub_temp_20 = shiftmul16_FixPt_add_temp_33 - $signed({1'b0, shiftmul16_FixPt_d6_6});
  assign shiftmul16_FixPt_sub_temp_21 = shiftmul16_FixPt_sub_temp_20 - $signed({1'b0, b4});
  assign shiftmul16_FixPt_d3_5 = shiftmul16_FixPt_d3 <<< 1;
  assign shiftmul16_FixPt_add_temp_34 = shiftmul16_FixPt_sub_temp_21 + $signed({1'b0, shiftmul16_FixPt_d3_5});
  assign shiftmul16_FixPt_add_temp_35 = shiftmul16_FixPt_add_temp_34 + $signed({1'b0, b3});
  assign shiftmul16_FixPt_d2_5 = shiftmul16_FixPt_d2 <<< 1;
  assign shiftmul16_FixPt_sub_temp_22 = shiftmul16_FixPt_add_temp_35 - $signed({1'b0, shiftmul16_FixPt_d2_5});
  assign shiftmul16_FixPt_add_temp_36 = shiftmul16_FixPt_sub_temp_22 + $signed({1'b0, b1});
  assign y15 = shiftmul16_FixPt_add_temp_36[5:0];



  assign ceout = clkenable;

endmodule  // shiftmul16_FixPt

