-- -------------------------------------------------------------
-- 
-- File Name: G:\AI\IIT BHU\codegen\shiftmul32\hdlsrc\shiftmul32_FixPt.vhd
-- Created: 2016-06-06 12:31:20
-- 
-- Generated by MATLAB 8.1, MATLAB Coder 2.4 and HDL Coder 3.2
-- 
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Design base rate: 1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- y1                            ce_out        1
-- y3                            ce_out        1
-- y5                            ce_out        1
-- y7                            ce_out        1
-- y9                            ce_out        1
-- y11                           ce_out        1
-- y13                           ce_out        1
-- y15                           ce_out        1
-- y17                           ce_out        1
-- y19                           ce_out        1
-- y21                           ce_out        1
-- y23                           ce_out        1
-- y25                           ce_out        1
-- y27                           ce_out        1
-- y29                           ce_out        1
-- y31                           ce_out        1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: shiftmul32_FixPt
-- Source Path: shiftmul32_FixPt
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY shiftmul32_FixPt IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        b1                                :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        b2                                :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        b3                                :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        b4                                :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        b5                                :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        b6                                :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        b7                                :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        b8                                :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        b9                                :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        b10                               :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        b11                               :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        b12                               :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        b13                               :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        b14                               :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        b15                               :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        b16                               :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        ce_out                            :   OUT   std_logic;
        y1                                :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
        y3                                :   OUT   std_logic_vector(7 DOWNTO 0);  -- sfix8
        y5                                :   OUT   std_logic_vector(6 DOWNTO 0);  -- ufix7
        y7                                :   OUT   std_logic_vector(4 DOWNTO 0);  -- sfix5
        y9                                :   OUT   std_logic_vector(6 DOWNTO 0);  -- ufix7
        y11                               :   OUT   std_logic_vector(7 DOWNTO 0);  -- sfix8
        y13                               :   OUT   std_logic_vector(8 DOWNTO 0);  -- sfix9
        y15                               :   OUT   std_logic_vector(5 DOWNTO 0);  -- sfix6
        y17                               :   OUT   std_logic_vector(4 DOWNTO 0);  -- ufix5
        y19                               :   OUT   std_logic_vector(5 DOWNTO 0);  -- ufix6
        y21                               :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
        y23                               :   OUT   std_logic_vector(6 DOWNTO 0);  -- ufix7
        y25                               :   OUT   std_logic_vector(7 DOWNTO 0);  -- sfix8
        y27                               :   OUT   std_logic_vector(6 DOWNTO 0);  -- sfix7
        y29                               :   OUT   std_logic_vector(5 DOWNTO 0);  -- sfix6
        y31                               :   OUT   std_logic_vector(7 DOWNTO 0)  -- sfix8
        );
END shiftmul32_FixPt;


ARCHITECTURE rtl OF shiftmul32_FixPt IS

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL b1_unsigned                      : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL b2_unsigned                      : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL b3_unsigned                      : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL b4_unsigned                      : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL b5_unsigned                      : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL b6_unsigned                      : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL b7_unsigned                      : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL b8_unsigned                      : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL b9_unsigned                      : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL b10_unsigned                     : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL b11_unsigned                     : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL b12_unsigned                     : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL b13_unsigned                     : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL b14_unsigned                     : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL b15_unsigned                     : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL b16_unsigned                     : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL y1_tmp                           : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL y3_tmp                           : signed(7 DOWNTO 0);  -- sfix8
  SIGNAL y5_tmp                           : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL y7_tmp                           : signed(4 DOWNTO 0);  -- sfix5
  SIGNAL y9_tmp                           : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL y11_tmp                          : signed(7 DOWNTO 0);  -- sfix8
  SIGNAL y13_tmp                          : signed(8 DOWNTO 0);  -- sfix9
  SIGNAL y15_tmp                          : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL y17_tmp                          : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL y19_tmp                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL y21_tmp                          : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL y23_tmp                          : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL y25_tmp                          : signed(7 DOWNTO 0);  -- sfix8
  SIGNAL y27_tmp                          : signed(6 DOWNTO 0);  -- sfix7
  SIGNAL y29_tmp                          : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL y31_tmp                          : signed(7 DOWNTO 0);  -- sfix8
  SIGNAL shiftmul32_FixPt_d1              : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_d2              : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_d3              : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_d4              : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_d5              : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_d6              : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_d7              : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_d8              : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_d9              : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_d10             : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_d11             : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_d12             : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_d13             : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_d14             : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_d15             : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_d16             : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_cast            : signed(7 DOWNTO 0);  -- int8
  SIGNAL shiftmul32_FixPt_cast_1          : signed(7 DOWNTO 0);  -- int8
  SIGNAL shiftmul32_FixPt_cast_2          : signed(7 DOWNTO 0);  -- int8
  SIGNAL shiftmul32_FixPt_cast_3          : signed(7 DOWNTO 0);  -- int8
  SIGNAL shiftmul32_FixPt_cast_4          : signed(7 DOWNTO 0);  -- int8
  SIGNAL shiftmul32_FixPt_cast_5          : signed(7 DOWNTO 0);  -- int8
  SIGNAL shiftmul32_FixPt_cast_6          : signed(7 DOWNTO 0);  -- int8
  SIGNAL shiftmul32_FixPt_cast_7          : signed(7 DOWNTO 0);  -- int8
  SIGNAL shiftmul32_FixPt_cast_8          : signed(7 DOWNTO 0);  -- int8
  SIGNAL shiftmul32_FixPt_cast_9          : signed(7 DOWNTO 0);  -- int8
  SIGNAL shiftmul32_FixPt_cast_10         : signed(7 DOWNTO 0);  -- int8
  SIGNAL shiftmul32_FixPt_cast_11         : signed(7 DOWNTO 0);  -- int8
  SIGNAL shiftmul32_FixPt_cast_12         : signed(7 DOWNTO 0);  -- int8
  SIGNAL shiftmul32_FixPt_cast_13         : signed(7 DOWNTO 0);  -- int8
  SIGNAL shiftmul32_FixPt_cast_14         : signed(7 DOWNTO 0);  -- int8
  SIGNAL shiftmul32_FixPt_cast_15         : signed(7 DOWNTO 0);  -- int8
  SIGNAL shiftmul32_FixPt_cast_16         : unsigned(57 DOWNTO 0);  -- ufix58
  SIGNAL shiftmul32_FixPt_d7_1            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_cast_17         : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL shiftmul32_FixPt_d13_1           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast        : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL shiftmul32_FixPt_add_cast_1      : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL shiftmul32_FixPt_d6_1            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_sub_cast        : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL shiftmul32_FixPt_d8_1            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_sub_cast_1      : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL shiftmul32_FixPt_add_cast_2      : signed(26 DOWNTO 0);  -- sfix27
  SIGNAL shiftmul32_FixPt_d2_1            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_3      : signed(28 DOWNTO 0);  -- sfix29
  SIGNAL shiftmul32_FixPt_add_cast_4      : signed(29 DOWNTO 0);  -- sfix30
  SIGNAL shiftmul32_FixPt_add_cast_5      : signed(34 DOWNTO 0);  -- sfix35
  SIGNAL shiftmul32_FixPt_d5_1            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_sub_cast_2      : signed(38 DOWNTO 0);  -- sfix39
  SIGNAL shiftmul32_FixPt_d9_1            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_sub_cast_3      : signed(42 DOWNTO 0);  -- sfix43
  SIGNAL shiftmul32_FixPt_add_cast_6      : signed(43 DOWNTO 0);  -- sfix44
  SIGNAL shiftmul32_FixPt_d11_1           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_7      : signed(46 DOWNTO 0);  -- sfix47
  SIGNAL shiftmul32_FixPt_add_cast_8      : signed(47 DOWNTO 0);  -- sfix48
  SIGNAL shiftmul32_FixPt_d3_1            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_9      : signed(51 DOWNTO 0);  -- sfix52
  SIGNAL shiftmul32_FixPt_d16_1           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_10     : signed(54 DOWNTO 0);  -- sfix55
  SIGNAL shiftmul32_FixPt_sub_cast_4      : signed(57 DOWNTO 0);  -- sfix58
  SIGNAL shiftmul32_FixPt_cast_18         : signed(58 DOWNTO 0);  -- sfix59
  SIGNAL shiftmul32_FixPt_d5_2            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_cast_19         : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL shiftmul32_FixPt_d14_1           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_sub_cast_5      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL shiftmul32_FixPt_add_cast_11     : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL shiftmul32_FixPt_d9_2            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_12     : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL shiftmul32_FixPt_d15_1           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_sub_cast_6      : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL shiftmul32_FixPt_sub_cast_7      : signed(26 DOWNTO 0);  -- sfix27
  SIGNAL shiftmul32_FixPt_d4_1            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_sub_cast_8      : signed(28 DOWNTO 0);  -- sfix29
  SIGNAL shiftmul32_FixPt_sub_cast_9      : signed(29 DOWNTO 0);  -- sfix30
  SIGNAL shiftmul32_FixPt_sub_cast_10     : signed(34 DOWNTO 0);  -- sfix35
  SIGNAL shiftmul32_FixPt_d11_2           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_13     : signed(38 DOWNTO 0);  -- sfix39
  SIGNAL shiftmul32_FixPt_d2_2            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_14     : signed(42 DOWNTO 0);  -- sfix43
  SIGNAL shiftmul32_FixPt_add_cast_15     : signed(43 DOWNTO 0);  -- sfix44
  SIGNAL shiftmul32_FixPt_d8_2            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_16     : signed(46 DOWNTO 0);  -- sfix47
  SIGNAL shiftmul32_FixPt_add_cast_17     : signed(47 DOWNTO 0);  -- sfix48
  SIGNAL shiftmul32_FixPt_d16_2           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_sub_cast_11     : signed(51 DOWNTO 0);  -- sfix52
  SIGNAL shiftmul32_FixPt_d7_2            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_sub_cast_12     : signed(54 DOWNTO 0);  -- sfix55
  SIGNAL shiftmul32_FixPt_sub_cast_13     : signed(57 DOWNTO 0);  -- sfix58
  SIGNAL shiftmul32_FixPt_sub_temp        : signed(57 DOWNTO 0);  -- sfix58
  SIGNAL shiftmul32_FixPt_d4_2            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_cast_20         : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL shiftmul32_FixPt_d11_3           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_sub_cast_14     : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL shiftmul32_FixPt_add_cast_18     : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL shiftmul32_FixPt_d1_1            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_19     : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL shiftmul32_FixPt_d7_3            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_20     : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL shiftmul32_FixPt_add_cast_21     : signed(26 DOWNTO 0);  -- sfix27
  SIGNAL shiftmul32_FixPt_d12_1           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_sub_cast_15     : signed(28 DOWNTO 0);  -- sfix29
  SIGNAL shiftmul32_FixPt_sub_cast_16     : signed(29 DOWNTO 0);  -- sfix30
  SIGNAL shiftmul32_FixPt_sub_cast_17     : signed(34 DOWNTO 0);  -- sfix35
  SIGNAL shiftmul32_FixPt_d3_2            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_sub_cast_18     : signed(38 DOWNTO 0);  -- sfix39
  SIGNAL shiftmul32_FixPt_d10_1           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_sub_cast_19     : signed(42 DOWNTO 0);  -- sfix43
  SIGNAL shiftmul32_FixPt_sub_cast_20     : signed(43 DOWNTO 0);  -- sfix44
  SIGNAL shiftmul32_FixPt_d16_3           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_22     : signed(46 DOWNTO 0);  -- sfix47
  SIGNAL shiftmul32_FixPt_add_cast_23     : signed(47 DOWNTO 0);  -- sfix48
  SIGNAL shiftmul32_FixPt_d9_3            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_24     : signed(51 DOWNTO 0);  -- sfix52
  SIGNAL shiftmul32_FixPt_d2_3            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_25     : signed(54 DOWNTO 0);  -- sfix55
  SIGNAL shiftmul32_FixPt_add_cast_26     : signed(57 DOWNTO 0);  -- sfix58
  SIGNAL shiftmul32_FixPt_cast_21         : signed(58 DOWNTO 0);  -- sfix59
  SIGNAL shiftmul32_FixPt_cast_22         : unsigned(57 DOWNTO 0);  -- ufix58
  SIGNAL shiftmul32_FixPt_d3_3            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_cast_23         : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL shiftmul32_FixPt_d8_3            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_sub_cast_21     : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL shiftmul32_FixPt_add_cast_27     : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL shiftmul32_FixPt_d10_2           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_28     : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL shiftmul32_FixPt_d5_3            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_29     : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL shiftmul32_FixPt_add_cast_30     : signed(26 DOWNTO 0);  -- sfix27
  SIGNAL shiftmul32_FixPt_d6_2            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_31     : signed(28 DOWNTO 0);  -- sfix29
  SIGNAL shiftmul32_FixPt_add_cast_32     : signed(29 DOWNTO 0);  -- sfix30
  SIGNAL shiftmul32_FixPt_add_cast_33     : signed(34 DOWNTO 0);  -- sfix35
  SIGNAL shiftmul32_FixPt_d16_4           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_34     : signed(38 DOWNTO 0);  -- sfix39
  SIGNAL shiftmul32_FixPt_d12_2           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_sub_cast_22     : signed(42 DOWNTO 0);  -- sfix43
  SIGNAL shiftmul32_FixPt_add_cast_35     : signed(43 DOWNTO 0);  -- sfix44
  SIGNAL shiftmul32_FixPt_d7_4            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_sub_cast_23     : signed(46 DOWNTO 0);  -- sfix47
  SIGNAL shiftmul32_FixPt_sub_cast_24     : signed(47 DOWNTO 0);  -- sfix48
  SIGNAL shiftmul32_FixPt_d2_4            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_sub_cast_25     : signed(51 DOWNTO 0);  -- sfix52
  SIGNAL shiftmul32_FixPt_d4_3            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_sub_cast_26     : signed(54 DOWNTO 0);  -- sfix55
  SIGNAL shiftmul32_FixPt_sub_cast_27     : signed(57 DOWNTO 0);  -- sfix58
  SIGNAL shiftmul32_FixPt_sub_temp_1      : signed(57 DOWNTO 0);  -- sfix58
  SIGNAL shiftmul32_FixPt_d7_5            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_cast_24         : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL shiftmul32_FixPt_d9_4            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_36     : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL shiftmul32_FixPt_add_cast_37     : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL shiftmul32_FixPt_d13_2           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_38     : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL shiftmul32_FixPt_d3_4            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_sub_cast_28     : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL shiftmul32_FixPt_sub_cast_29     : signed(26 DOWNTO 0);  -- sfix27
  SIGNAL shiftmul32_FixPt_d1_2            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_39     : signed(28 DOWNTO 0);  -- sfix29
  SIGNAL shiftmul32_FixPt_add_cast_40     : signed(29 DOWNTO 0);  -- sfix30
  SIGNAL shiftmul32_FixPt_sub_cast_30     : signed(34 DOWNTO 0);  -- sfix35
  SIGNAL shiftmul32_FixPt_d2_5            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_sub_cast_31     : signed(38 DOWNTO 0);  -- sfix39
  SIGNAL shiftmul32_FixPt_d14_2           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_41     : signed(42 DOWNTO 0);  -- sfix43
  SIGNAL shiftmul32_FixPt_add_cast_42     : signed(43 DOWNTO 0);  -- sfix44
  SIGNAL shiftmul32_FixPt_d4_4            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_43     : signed(46 DOWNTO 0);  -- sfix47
  SIGNAL shiftmul32_FixPt_add_cast_44     : signed(47 DOWNTO 0);  -- sfix48
  SIGNAL shiftmul32_FixPt_d12_3           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_sub_cast_32     : signed(51 DOWNTO 0);  -- sfix52
  SIGNAL shiftmul32_FixPt_d6_3            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_sub_cast_33     : signed(54 DOWNTO 0);  -- sfix55
  SIGNAL shiftmul32_FixPt_add_cast_45     : signed(57 DOWNTO 0);  -- sfix58
  SIGNAL shiftmul32_FixPt_add_temp        : signed(57 DOWNTO 0);  -- sfix58
  SIGNAL shiftmul32_FixPt_d9_5            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_cast_25         : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL shiftmul32_FixPt_d14_3           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_46     : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL shiftmul32_FixPt_sub_cast_34     : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL shiftmul32_FixPt_d7_6            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_47     : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL shiftmul32_FixPt_d12_4           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_sub_cast_35     : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL shiftmul32_FixPt_sub_cast_36     : signed(26 DOWNTO 0);  -- sfix27
  SIGNAL shiftmul32_FixPt_d11_4           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_48     : signed(28 DOWNTO 0);  -- sfix29
  SIGNAL shiftmul32_FixPt_add_cast_49     : signed(29 DOWNTO 0);  -- sfix30
  SIGNAL shiftmul32_FixPt_sub_cast_37     : signed(34 DOWNTO 0);  -- sfix35
  SIGNAL shiftmul32_FixPt_d1_3            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_50     : signed(38 DOWNTO 0);  -- sfix39
  SIGNAL shiftmul32_FixPt_d5_4            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_sub_cast_38     : signed(42 DOWNTO 0);  -- sfix43
  SIGNAL shiftmul32_FixPt_sub_cast_39     : signed(43 DOWNTO 0);  -- sfix44
  SIGNAL shiftmul32_FixPt_d10_3           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_51     : signed(46 DOWNTO 0);  -- sfix47
  SIGNAL shiftmul32_FixPt_add_cast_52     : signed(47 DOWNTO 0);  -- sfix48
  SIGNAL shiftmul32_FixPt_d15_2           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_sub_cast_40     : signed(51 DOWNTO 0);  -- sfix52
  SIGNAL shiftmul32_FixPt_d13_3           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_sub_cast_41     : signed(54 DOWNTO 0);  -- sfix55
  SIGNAL shiftmul32_FixPt_add_cast_53     : signed(57 DOWNTO 0);  -- sfix58
  SIGNAL shiftmul32_FixPt_cast_26         : signed(58 DOWNTO 0);  -- sfix59
  SIGNAL shiftmul32_FixPt_d1_4            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_cast_27         : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL shiftmul32_FixPt_d5_5            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_sub_cast_42     : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL shiftmul32_FixPt_sub_cast_43     : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL shiftmul32_FixPt_d14_4           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_sub_cast_44     : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL shiftmul32_FixPt_d16_5           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_54     : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL shiftmul32_FixPt_add_cast_55     : signed(26 DOWNTO 0);  -- sfix27
  SIGNAL shiftmul32_FixPt_d10_4           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_56     : signed(28 DOWNTO 0);  -- sfix29
  SIGNAL shiftmul32_FixPt_add_cast_57     : signed(29 DOWNTO 0);  -- sfix30
  SIGNAL shiftmul32_FixPt_add_cast_58     : signed(34 DOWNTO 0);  -- sfix35
  SIGNAL shiftmul32_FixPt_d4_5            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_59     : signed(38 DOWNTO 0);  -- sfix39
  SIGNAL shiftmul32_FixPt_d1_5            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_60     : signed(42 DOWNTO 0);  -- sfix43
  SIGNAL shiftmul32_FixPt_add_cast_61     : signed(43 DOWNTO 0);  -- sfix44
  SIGNAL shiftmul32_FixPt_d3_5            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_62     : signed(46 DOWNTO 0);  -- sfix47
  SIGNAL shiftmul32_FixPt_add_cast_63     : signed(47 DOWNTO 0);  -- sfix48
  SIGNAL shiftmul32_FixPt_d6_4            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_64     : signed(51 DOWNTO 0);  -- sfix52
  SIGNAL shiftmul32_FixPt_d9_6            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_65     : signed(54 DOWNTO 0);  -- sfix55
  SIGNAL shiftmul32_FixPt_add_cast_66     : signed(57 DOWNTO 0);  -- sfix58
  SIGNAL shiftmul32_FixPt_cast_28         : signed(58 DOWNTO 0);  -- sfix59
  SIGNAL shiftmul32_FixPt_cast_29         : unsigned(57 DOWNTO 0);  -- ufix58
  SIGNAL shiftmul32_FixPt_cast_30         : unsigned(57 DOWNTO 0);  -- ufix58
  SIGNAL shiftmul32_FixPt_d6_5            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_cast_31         : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL shiftmul32_FixPt_d16_6           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_67     : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL shiftmul32_FixPt_add_cast_68     : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL shiftmul32_FixPt_d15_3           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_sub_cast_45     : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL shiftmul32_FixPt_d4_6            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_sub_cast_46     : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL shiftmul32_FixPt_sub_cast_47     : signed(26 DOWNTO 0);  -- sfix27
  SIGNAL shiftmul32_FixPt_d14_5           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_69     : signed(28 DOWNTO 0);  -- sfix29
  SIGNAL shiftmul32_FixPt_add_cast_70     : signed(29 DOWNTO 0);  -- sfix30
  SIGNAL shiftmul32_FixPt_add_cast_71     : signed(34 DOWNTO 0);  -- sfix35
  SIGNAL shiftmul32_FixPt_d9_7            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_72     : signed(38 DOWNTO 0);  -- sfix39
  SIGNAL shiftmul32_FixPt_d13_4           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_sub_cast_48     : signed(42 DOWNTO 0);  -- sfix43
  SIGNAL shiftmul32_FixPt_sub_cast_49     : signed(43 DOWNTO 0);  -- sfix44
  SIGNAL shiftmul32_FixPt_d2_6            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_sub_cast_50     : signed(46 DOWNTO 0);  -- sfix47
  SIGNAL shiftmul32_FixPt_sub_cast_51     : signed(47 DOWNTO 0);  -- sfix48
  SIGNAL shiftmul32_FixPt_d10_5           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_sub_cast_52     : signed(51 DOWNTO 0);  -- sfix52
  SIGNAL shiftmul32_FixPt_d12_5           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_73     : signed(54 DOWNTO 0);  -- sfix55
  SIGNAL shiftmul32_FixPt_add_cast_74     : signed(57 DOWNTO 0);  -- sfix58
  SIGNAL shiftmul32_FixPt_add_temp_1      : signed(57 DOWNTO 0);  -- sfix58
  SIGNAL shiftmul32_FixPt_d16_7           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_cast_32         : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL shiftmul32_FixPt_d15_4           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_75     : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL shiftmul32_FixPt_add_cast_76     : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL shiftmul32_FixPt_d12_6           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_sub_cast_53     : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL shiftmul32_FixPt_d11_5           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_77     : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL shiftmul32_FixPt_sub_cast_54     : signed(26 DOWNTO 0);  -- sfix27
  SIGNAL shiftmul32_FixPt_d9_8            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_78     : signed(28 DOWNTO 0);  -- sfix29
  SIGNAL shiftmul32_FixPt_add_cast_79     : signed(29 DOWNTO 0);  -- sfix30
  SIGNAL shiftmul32_FixPt_sub_cast_55     : signed(34 DOWNTO 0);  -- sfix35
  SIGNAL shiftmul32_FixPt_d7_7            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_80     : signed(38 DOWNTO 0);  -- sfix39
  SIGNAL shiftmul32_FixPt_d6_6            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_sub_cast_56     : signed(42 DOWNTO 0);  -- sfix43
  SIGNAL shiftmul32_FixPt_sub_cast_57     : signed(43 DOWNTO 0);  -- sfix44
  SIGNAL shiftmul32_FixPt_d5_6            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_81     : signed(46 DOWNTO 0);  -- sfix47
  SIGNAL shiftmul32_FixPt_add_cast_82     : signed(47 DOWNTO 0);  -- sfix48
  SIGNAL shiftmul32_FixPt_d4_7            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_sub_cast_58     : signed(51 DOWNTO 0);  -- sfix52
  SIGNAL shiftmul32_FixPt_d3_6            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul32_FixPt_add_cast_83     : signed(54 DOWNTO 0);  -- sfix55
  SIGNAL shiftmul32_FixPt_sub_cast_59     : signed(57 DOWNTO 0);  -- sfix58
  SIGNAL shiftmul32_FixPt_sub_temp_2      : signed(57 DOWNTO 0);  -- sfix58

BEGIN
  b1_unsigned <= unsigned(b1);

  b2_unsigned <= unsigned(b2);

  b3_unsigned <= unsigned(b3);

  b4_unsigned <= unsigned(b4);

  b5_unsigned <= unsigned(b5);

  b6_unsigned <= unsigned(b6);

  b7_unsigned <= unsigned(b7);

  b8_unsigned <= unsigned(b8);

  b9_unsigned <= unsigned(b9);

  b10_unsigned <= unsigned(b10);

  b11_unsigned <= unsigned(b11);

  b12_unsigned <= unsigned(b12);

  b13_unsigned <= unsigned(b13);

  b14_unsigned <= unsigned(b14);

  b15_unsigned <= unsigned(b15);

  b16_unsigned <= unsigned(b16);

  enb <= clk_enable;

  --spssa
  --%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  --                                                                          %
  --        Generated by MATLAB 8.1, MATLAB Coder 2.4 and HDL Coder 3.2      %
  --                                                                          %
  --%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  shiftmul32_FixPt_cast <= signed(resize(b1_unsigned, 8));
  shiftmul32_FixPt_d1 <= unsigned(shiftmul32_FixPt_cast(1 DOWNTO 0));
  shiftmul32_FixPt_cast_1 <= signed(resize(b2_unsigned, 8));
  shiftmul32_FixPt_d2 <= unsigned(shiftmul32_FixPt_cast_1(1 DOWNTO 0));
  shiftmul32_FixPt_cast_2 <= signed(resize(b3_unsigned, 8));
  shiftmul32_FixPt_d3 <= unsigned(shiftmul32_FixPt_cast_2(1 DOWNTO 0));
  shiftmul32_FixPt_cast_3 <= signed(resize(b4_unsigned, 8));
  shiftmul32_FixPt_d4 <= unsigned(shiftmul32_FixPt_cast_3(1 DOWNTO 0));
  shiftmul32_FixPt_cast_4 <= signed(resize(b5_unsigned, 8));
  shiftmul32_FixPt_d5 <= unsigned(shiftmul32_FixPt_cast_4(1 DOWNTO 0));
  shiftmul32_FixPt_cast_5 <= signed(resize(b6_unsigned, 8));
  shiftmul32_FixPt_d6 <= unsigned(shiftmul32_FixPt_cast_5(1 DOWNTO 0));
  shiftmul32_FixPt_cast_6 <= signed(resize(b7_unsigned, 8));
  shiftmul32_FixPt_d7 <= unsigned(shiftmul32_FixPt_cast_6(1 DOWNTO 0));
  shiftmul32_FixPt_cast_7 <= signed(resize(b8_unsigned, 8));
  shiftmul32_FixPt_d8 <= unsigned(shiftmul32_FixPt_cast_7(1 DOWNTO 0));
  shiftmul32_FixPt_cast_8 <= signed(resize(b9_unsigned, 8));
  shiftmul32_FixPt_d9 <= unsigned(shiftmul32_FixPt_cast_8(1 DOWNTO 0));
  shiftmul32_FixPt_cast_9 <= signed(resize(b10_unsigned, 8));
  shiftmul32_FixPt_d10 <= unsigned(shiftmul32_FixPt_cast_9(1 DOWNTO 0));
  shiftmul32_FixPt_cast_10 <= signed(resize(b11_unsigned, 8));
  shiftmul32_FixPt_d11 <= unsigned(shiftmul32_FixPt_cast_10(1 DOWNTO 0));
  shiftmul32_FixPt_cast_11 <= signed(resize(b12_unsigned, 8));
  shiftmul32_FixPt_d12 <= unsigned(shiftmul32_FixPt_cast_11(1 DOWNTO 0));
  shiftmul32_FixPt_cast_12 <= signed(resize(b13_unsigned, 8));
  shiftmul32_FixPt_d13 <= unsigned(shiftmul32_FixPt_cast_12(1 DOWNTO 0));
  shiftmul32_FixPt_cast_13 <= signed(resize(b14_unsigned, 8));
  shiftmul32_FixPt_d14 <= unsigned(shiftmul32_FixPt_cast_13(1 DOWNTO 0));
  shiftmul32_FixPt_cast_14 <= signed(resize(b15_unsigned, 8));
  shiftmul32_FixPt_d15 <= unsigned(shiftmul32_FixPt_cast_14(1 DOWNTO 0));
  shiftmul32_FixPt_cast_15 <= signed(resize(b16_unsigned, 8));
  shiftmul32_FixPt_d16 <= unsigned(shiftmul32_FixPt_cast_15(1 DOWNTO 0));
  y1_tmp <= resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(shiftmul32_FixPt_d1 sll 1, 9) + resize(shiftmul32_FixPt_d2 sll 1, 9), 16) + resize(b4_unsigned, 16), 19) + resize(shiftmul32_FixPt_d5 sll 1, 19), 23) + resize(shiftmul32_FixPt_d6 sll 1, 23), 26) + resize(b7_unsigned, 26), 28) + resize(shiftmul32_FixPt_d8 sll 1, 28), 29) + resize(b8_unsigned, 29), 34) + resize(b9_unsigned, 34), 38) + resize(shiftmul32_FixPt_d10 sll 1, 38), 42) + resize(shiftmul32_FixPt_d11 sll 1, 42), 43) + resize(b11_unsigned, 43), 46) + resize(shiftmul32_FixPt_d12 sll 1, 46), 47) + resize(b12_unsigned, 47), 51) + resize(shiftmul32_FixPt_d13 sll 1, 51), 54) + resize(shiftmul32_FixPt_d14 sll 1, 54), 57) + resize(b15_unsigned, 57), 8);
  shiftmul32_FixPt_cast_16 <= resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(shiftmul32_FixPt_d1 sll 1, 9) - resize(shiftmul32_FixPt_d11 sll 1, 9), 16) + resize(b10_unsigned, 16), 19) + resize(shiftmul32_FixPt_d2 sll 1, 19), 23) - resize(shiftmul32_FixPt_d13 sll 1, 23), 26) - resize(b9_unsigned, 26), 28) + resize(shiftmul32_FixPt_d3 sll 1, 28), 29) + resize(b3_unsigned, 29), 34) - resize(b14_unsigned, 34), 38) - resize(shiftmul32_FixPt_d8 sll 1, 38), 42) + resize(shiftmul32_FixPt_d4 sll 1, 42), 43) + resize(b4_unsigned, 43), 46) - resize(shiftmul32_FixPt_d15 sll 1, 46), 47) - resize(b15_unsigned, 47), 51) - resize(shiftmul32_FixPt_d7 sll 1, 51), 54) + resize(shiftmul32_FixPt_d5 sll 1, 54), 57) - resize(b16_unsigned, 57), 58);
  y3_tmp <= signed(shiftmul32_FixPt_cast_16(7 DOWNTO 0));
  shiftmul32_FixPt_d7_1 <= shiftmul32_FixPt_d7 sll 1;
  shiftmul32_FixPt_cast_17 <= signed(resize(shiftmul32_FixPt_d7_1, 6));
  shiftmul32_FixPt_d13_1 <= shiftmul32_FixPt_d13 sll 1;
  shiftmul32_FixPt_add_cast <= signed(resize(shiftmul32_FixPt_d13_1, 10));
  shiftmul32_FixPt_add_cast_1 <= signed(resize(b12_unsigned, 17));
  shiftmul32_FixPt_d6_1 <= shiftmul32_FixPt_d6 sll 1;
  shiftmul32_FixPt_sub_cast <= signed(resize(shiftmul32_FixPt_d6_1, 20));
  shiftmul32_FixPt_d8_1 <= shiftmul32_FixPt_d8 sll 1;
  shiftmul32_FixPt_sub_cast_1 <= signed(resize(shiftmul32_FixPt_d8_1, 24));
  shiftmul32_FixPt_add_cast_2 <= signed(resize(b12_unsigned, 27));
  shiftmul32_FixPt_d2_1 <= shiftmul32_FixPt_d2 sll 1;
  shiftmul32_FixPt_add_cast_3 <= signed(resize(shiftmul32_FixPt_d2_1, 29));
  shiftmul32_FixPt_add_cast_4 <= signed(resize(b2_unsigned, 30));
  shiftmul32_FixPt_add_cast_5 <= signed(resize(b15_unsigned, 35));
  shiftmul32_FixPt_d5_1 <= shiftmul32_FixPt_d5 sll 1;
  shiftmul32_FixPt_sub_cast_2 <= signed(resize(shiftmul32_FixPt_d5_1, 39));
  shiftmul32_FixPt_d9_1 <= shiftmul32_FixPt_d9 sll 1;
  shiftmul32_FixPt_sub_cast_3 <= signed(resize(shiftmul32_FixPt_d9_1, 43));
  shiftmul32_FixPt_add_cast_6 <= signed(resize(b9_unsigned, 44));
  shiftmul32_FixPt_d11_1 <= shiftmul32_FixPt_d11 sll 1;
  shiftmul32_FixPt_add_cast_7 <= signed(resize(shiftmul32_FixPt_d11_1, 47));
  shiftmul32_FixPt_add_cast_8 <= signed(resize(b11_unsigned, 48));
  shiftmul32_FixPt_d3_1 <= shiftmul32_FixPt_d3 sll 1;
  shiftmul32_FixPt_add_cast_9 <= signed(resize(shiftmul32_FixPt_d3_1, 52));
  shiftmul32_FixPt_d16_1 <= shiftmul32_FixPt_d16 sll 1;
  shiftmul32_FixPt_add_cast_10 <= signed(resize(shiftmul32_FixPt_d16_1, 55));
  shiftmul32_FixPt_sub_cast_4 <= signed(resize(b10_unsigned, 58));
  shiftmul32_FixPt_cast_18 <= resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize( - (shiftmul32_FixPt_cast_17), 10) + shiftmul32_FixPt_add_cast, 17) + shiftmul32_FixPt_add_cast_1, 20) - shiftmul32_FixPt_sub_cast, 24) - shiftmul32_FixPt_sub_cast_1, 27) + shiftmul32_FixPt_add_cast_2, 29) + shiftmul32_FixPt_add_cast_3, 30) + shiftmul32_FixPt_add_cast_4, 35) + shiftmul32_FixPt_add_cast_5, 39) - shiftmul32_FixPt_sub_cast_2, 43) - shiftmul32_FixPt_sub_cast_3, 44) + shiftmul32_FixPt_add_cast_6, 47) + shiftmul32_FixPt_add_cast_7, 48) + shiftmul32_FixPt_add_cast_8, 52) + shiftmul32_FixPt_add_cast_9, 55) + shiftmul32_FixPt_add_cast_10, 58) - shiftmul32_FixPt_sub_cast_4, 59);
  y5_tmp <= unsigned(shiftmul32_FixPt_cast_18(6 DOWNTO 0));
  shiftmul32_FixPt_d5_2 <= shiftmul32_FixPt_d5 sll 1;
  shiftmul32_FixPt_cast_19 <= signed(resize(shiftmul32_FixPt_d5_2, 6));
  shiftmul32_FixPt_d14_1 <= shiftmul32_FixPt_d14 sll 1;
  shiftmul32_FixPt_sub_cast_5 <= signed(resize(shiftmul32_FixPt_d14_1, 10));
  shiftmul32_FixPt_add_cast_11 <= signed(resize(b1_unsigned, 17));
  shiftmul32_FixPt_d9_2 <= shiftmul32_FixPt_d9 sll 1;
  shiftmul32_FixPt_add_cast_12 <= signed(resize(shiftmul32_FixPt_d9_2, 20));
  shiftmul32_FixPt_d15_1 <= shiftmul32_FixPt_d15 sll 1;
  shiftmul32_FixPt_sub_cast_6 <= signed(resize(shiftmul32_FixPt_d15_1, 24));
  shiftmul32_FixPt_sub_cast_7 <= signed(resize(b6_unsigned, 27));
  shiftmul32_FixPt_d4_1 <= shiftmul32_FixPt_d4 sll 1;
  shiftmul32_FixPt_sub_cast_8 <= signed(resize(shiftmul32_FixPt_d4_1, 29));
  shiftmul32_FixPt_sub_cast_9 <= signed(resize(b4_unsigned, 30));
  shiftmul32_FixPt_sub_cast_10 <= signed(resize(b13_unsigned, 35));
  shiftmul32_FixPt_d11_2 <= shiftmul32_FixPt_d11 sll 1;
  shiftmul32_FixPt_add_cast_13 <= signed(resize(shiftmul32_FixPt_d11_2, 39));
  shiftmul32_FixPt_d2_2 <= shiftmul32_FixPt_d2 sll 1;
  shiftmul32_FixPt_add_cast_14 <= signed(resize(shiftmul32_FixPt_d2_2, 43));
  shiftmul32_FixPt_add_cast_15 <= signed(resize(b2_unsigned, 44));
  shiftmul32_FixPt_d8_2 <= shiftmul32_FixPt_d8 sll 1;
  shiftmul32_FixPt_add_cast_16 <= signed(resize(shiftmul32_FixPt_d8_2, 47));
  shiftmul32_FixPt_add_cast_17 <= signed(resize(b8_unsigned, 48));
  shiftmul32_FixPt_d16_2 <= shiftmul32_FixPt_d16 sll 1;
  shiftmul32_FixPt_sub_cast_11 <= signed(resize(shiftmul32_FixPt_d16_2, 52));
  shiftmul32_FixPt_d7_2 <= shiftmul32_FixPt_d7 sll 1;
  shiftmul32_FixPt_sub_cast_12 <= signed(resize(shiftmul32_FixPt_d7_2, 55));
  shiftmul32_FixPt_sub_cast_13 <= signed(resize(b3_unsigned, 58));
  shiftmul32_FixPt_sub_temp <= resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize( - (shiftmul32_FixPt_cast_19), 10) - shiftmul32_FixPt_sub_cast_5, 17) + shiftmul32_FixPt_add_cast_11, 20) + shiftmul32_FixPt_add_cast_12, 24) - shiftmul32_FixPt_sub_cast_6, 27) - shiftmul32_FixPt_sub_cast_7, 29) - shiftmul32_FixPt_sub_cast_8, 30) - shiftmul32_FixPt_sub_cast_9, 35) - shiftmul32_FixPt_sub_cast_10, 39) + shiftmul32_FixPt_add_cast_13, 43) + shiftmul32_FixPt_add_cast_14, 44) + shiftmul32_FixPt_add_cast_15, 47) + shiftmul32_FixPt_add_cast_16, 48) + shiftmul32_FixPt_add_cast_17, 52) - shiftmul32_FixPt_sub_cast_11, 55) - shiftmul32_FixPt_sub_cast_12, 58) - shiftmul32_FixPt_sub_cast_13;
  y7_tmp <= shiftmul32_FixPt_sub_temp(4 DOWNTO 0);
  shiftmul32_FixPt_d4_2 <= shiftmul32_FixPt_d4 sll 1;
  shiftmul32_FixPt_cast_20 <= signed(resize(shiftmul32_FixPt_d4_2, 6));
  shiftmul32_FixPt_d11_3 <= shiftmul32_FixPt_d11 sll 1;
  shiftmul32_FixPt_sub_cast_14 <= signed(resize(shiftmul32_FixPt_d11_3, 10));
  shiftmul32_FixPt_add_cast_18 <= signed(resize(b8_unsigned, 17));
  shiftmul32_FixPt_d1_1 <= shiftmul32_FixPt_d1 sll 1;
  shiftmul32_FixPt_add_cast_19 <= signed(resize(shiftmul32_FixPt_d1_1, 20));
  shiftmul32_FixPt_d7_3 <= shiftmul32_FixPt_d7 sll 1;
  shiftmul32_FixPt_add_cast_20 <= signed(resize(shiftmul32_FixPt_d7_3, 24));
  shiftmul32_FixPt_add_cast_21 <= signed(resize(b14_unsigned, 27));
  shiftmul32_FixPt_d12_1 <= shiftmul32_FixPt_d12 sll 1;
  shiftmul32_FixPt_sub_cast_15 <= signed(resize(shiftmul32_FixPt_d12_1, 29));
  shiftmul32_FixPt_sub_cast_16 <= signed(resize(b12_unsigned, 30));
  shiftmul32_FixPt_sub_cast_17 <= signed(resize(b5_unsigned, 35));
  shiftmul32_FixPt_d3_2 <= shiftmul32_FixPt_d3 sll 1;
  shiftmul32_FixPt_sub_cast_18 <= signed(resize(shiftmul32_FixPt_d3_2, 39));
  shiftmul32_FixPt_d10_1 <= shiftmul32_FixPt_d10 sll 1;
  shiftmul32_FixPt_sub_cast_19 <= signed(resize(shiftmul32_FixPt_d10_1, 43));
  shiftmul32_FixPt_sub_cast_20 <= signed(resize(b10_unsigned, 44));
  shiftmul32_FixPt_d16_3 <= shiftmul32_FixPt_d16 sll 1;
  shiftmul32_FixPt_add_cast_22 <= signed(resize(shiftmul32_FixPt_d16_3, 47));
  shiftmul32_FixPt_add_cast_23 <= signed(resize(b16_unsigned, 48));
  shiftmul32_FixPt_d9_3 <= shiftmul32_FixPt_d9 sll 1;
  shiftmul32_FixPt_add_cast_24 <= signed(resize(shiftmul32_FixPt_d9_3, 52));
  shiftmul32_FixPt_d2_3 <= shiftmul32_FixPt_d2 sll 1;
  shiftmul32_FixPt_add_cast_25 <= signed(resize(shiftmul32_FixPt_d2_3, 55));
  shiftmul32_FixPt_add_cast_26 <= signed(resize(b6_unsigned, 58));
  shiftmul32_FixPt_cast_21 <= resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize( - (shiftmul32_FixPt_cast_20), 10) - shiftmul32_FixPt_sub_cast_14, 17) + shiftmul32_FixPt_add_cast_18, 20) + shiftmul32_FixPt_add_cast_19, 24) + shiftmul32_FixPt_add_cast_20, 27) + shiftmul32_FixPt_add_cast_21, 29) - shiftmul32_FixPt_sub_cast_15, 30) - shiftmul32_FixPt_sub_cast_16, 35) - shiftmul32_FixPt_sub_cast_17, 39) - shiftmul32_FixPt_sub_cast_18, 43) - shiftmul32_FixPt_sub_cast_19, 44) - shiftmul32_FixPt_sub_cast_20, 47) + shiftmul32_FixPt_add_cast_22, 48) + shiftmul32_FixPt_add_cast_23, 52) + shiftmul32_FixPt_add_cast_24, 55) + shiftmul32_FixPt_add_cast_25, 58) + shiftmul32_FixPt_add_cast_26, 59);
  y9_tmp <= unsigned(shiftmul32_FixPt_cast_21(6 DOWNTO 0));
  shiftmul32_FixPt_cast_22 <= resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(shiftmul32_FixPt_d12 sll 1, 9) - resize(shiftmul32_FixPt_d15 sll 1, 9), 16) + resize(b6_unsigned, 16), 19) - resize(shiftmul32_FixPt_d3 sll 1, 19), 23) + resize(shiftmul32_FixPt_d1 sll 1, 23), 26) + resize(b4_unsigned, 26), 28) + resize(shiftmul32_FixPt_d7 sll 1, 28), 29) + resize(b7_unsigned, 29), 34) - resize(b10_unsigned, 34), 38) + resize(shiftmul32_FixPt_d13 sll 1, 38), 42) - resize(shiftmul32_FixPt_d16 sll 1, 42), 43) - resize(b16_unsigned, 43), 46) - resize(shiftmul32_FixPt_d14 sll 1, 46), 47) - resize(b14_unsigned, 47), 51) + resize(shiftmul32_FixPt_d11 sll 1, 51), 54) - resize(shiftmul32_FixPt_d8 sll 1, 54), 57) + resize(b5_unsigned, 57), 58);
  y11_tmp <= signed(shiftmul32_FixPt_cast_22(7 DOWNTO 0));
  shiftmul32_FixPt_d3_3 <= shiftmul32_FixPt_d3 sll 1;
  shiftmul32_FixPt_cast_23 <= signed(resize(shiftmul32_FixPt_d3_3, 6));
  shiftmul32_FixPt_d8_3 <= shiftmul32_FixPt_d8 sll 1;
  shiftmul32_FixPt_sub_cast_21 <= signed(resize(shiftmul32_FixPt_d8_3, 10));
  shiftmul32_FixPt_add_cast_27 <= signed(resize(b15_unsigned, 17));
  shiftmul32_FixPt_d10_2 <= shiftmul32_FixPt_d10 sll 1;
  shiftmul32_FixPt_add_cast_28 <= signed(resize(shiftmul32_FixPt_d10_2, 20));
  shiftmul32_FixPt_d5_3 <= shiftmul32_FixPt_d5 sll 1;
  shiftmul32_FixPt_add_cast_29 <= signed(resize(shiftmul32_FixPt_d5_3, 24));
  shiftmul32_FixPt_add_cast_30 <= signed(resize(b1_unsigned, 27));
  shiftmul32_FixPt_d6_2 <= shiftmul32_FixPt_d6 sll 1;
  shiftmul32_FixPt_add_cast_31 <= signed(resize(shiftmul32_FixPt_d6_2, 29));
  shiftmul32_FixPt_add_cast_32 <= signed(resize(b6_unsigned, 30));
  shiftmul32_FixPt_add_cast_33 <= signed(resize(b11_unsigned, 35));
  shiftmul32_FixPt_d16_4 <= shiftmul32_FixPt_d16 sll 1;
  shiftmul32_FixPt_add_cast_34 <= signed(resize(shiftmul32_FixPt_d16_4, 39));
  shiftmul32_FixPt_d12_2 <= shiftmul32_FixPt_d12 sll 1;
  shiftmul32_FixPt_sub_cast_22 <= signed(resize(shiftmul32_FixPt_d12_2, 43));
  shiftmul32_FixPt_add_cast_35 <= signed(resize(b12_unsigned, 44));
  shiftmul32_FixPt_d7_4 <= shiftmul32_FixPt_d7 sll 1;
  shiftmul32_FixPt_sub_cast_23 <= signed(resize(shiftmul32_FixPt_d7_4, 47));
  shiftmul32_FixPt_sub_cast_24 <= signed(resize(b7_unsigned, 48));
  shiftmul32_FixPt_d2_4 <= shiftmul32_FixPt_d2 sll 1;
  shiftmul32_FixPt_sub_cast_25 <= signed(resize(shiftmul32_FixPt_d2_4, 52));
  shiftmul32_FixPt_d4_3 <= shiftmul32_FixPt_d4 sll 1;
  shiftmul32_FixPt_sub_cast_26 <= signed(resize(shiftmul32_FixPt_d4_3, 55));
  shiftmul32_FixPt_sub_cast_27 <= signed(resize(b9_unsigned, 58));
  shiftmul32_FixPt_sub_temp_1 <= resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize( - (shiftmul32_FixPt_cast_23), 10) - shiftmul32_FixPt_sub_cast_21, 17) + shiftmul32_FixPt_add_cast_27, 20) + shiftmul32_FixPt_add_cast_28, 24) + shiftmul32_FixPt_add_cast_29, 27) + shiftmul32_FixPt_add_cast_30, 29) + shiftmul32_FixPt_add_cast_31, 30) + shiftmul32_FixPt_add_cast_32, 35) + shiftmul32_FixPt_add_cast_33, 39) + shiftmul32_FixPt_add_cast_34, 43) - shiftmul32_FixPt_sub_cast_22, 44) + shiftmul32_FixPt_add_cast_35, 47) - shiftmul32_FixPt_sub_cast_23, 48) - shiftmul32_FixPt_sub_cast_24, 52) - shiftmul32_FixPt_sub_cast_25, 55) - shiftmul32_FixPt_sub_cast_26, 58) - shiftmul32_FixPt_sub_cast_27;
  y13_tmp <= shiftmul32_FixPt_sub_temp_1(8 DOWNTO 0);
  shiftmul32_FixPt_d7_5 <= shiftmul32_FixPt_d7 sll 1;
  shiftmul32_FixPt_cast_24 <= signed(resize(shiftmul32_FixPt_d7_5, 6));
  shiftmul32_FixPt_d9_4 <= shiftmul32_FixPt_d9 sll 1;
  shiftmul32_FixPt_add_cast_36 <= signed(resize(shiftmul32_FixPt_d9_4, 10));
  shiftmul32_FixPt_add_cast_37 <= signed(resize(b5_unsigned, 17));
  shiftmul32_FixPt_d13_2 <= shiftmul32_FixPt_d13 sll 1;
  shiftmul32_FixPt_add_cast_38 <= signed(resize(shiftmul32_FixPt_d13_2, 20));
  shiftmul32_FixPt_d3_4 <= shiftmul32_FixPt_d3 sll 1;
  shiftmul32_FixPt_sub_cast_28 <= signed(resize(shiftmul32_FixPt_d3_4, 24));
  shiftmul32_FixPt_sub_cast_29 <= signed(resize(b15_unsigned, 27));
  shiftmul32_FixPt_d1_2 <= shiftmul32_FixPt_d1 sll 1;
  shiftmul32_FixPt_add_cast_39 <= signed(resize(shiftmul32_FixPt_d1_2, 29));
  shiftmul32_FixPt_add_cast_40 <= signed(resize(b1_unsigned, 30));
  shiftmul32_FixPt_sub_cast_30 <= signed(resize(b16_unsigned, 35));
  shiftmul32_FixPt_d2_5 <= shiftmul32_FixPt_d2 sll 1;
  shiftmul32_FixPt_sub_cast_31 <= signed(resize(shiftmul32_FixPt_d2_5, 39));
  shiftmul32_FixPt_d14_2 <= shiftmul32_FixPt_d14 sll 1;
  shiftmul32_FixPt_add_cast_41 <= signed(resize(shiftmul32_FixPt_d14_2, 43));
  shiftmul32_FixPt_add_cast_42 <= signed(resize(b14_unsigned, 44));
  shiftmul32_FixPt_d4_4 <= shiftmul32_FixPt_d4 sll 1;
  shiftmul32_FixPt_add_cast_43 <= signed(resize(shiftmul32_FixPt_d4_4, 47));
  shiftmul32_FixPt_add_cast_44 <= signed(resize(b4_unsigned, 48));
  shiftmul32_FixPt_d12_3 <= shiftmul32_FixPt_d12 sll 1;
  shiftmul32_FixPt_sub_cast_32 <= signed(resize(shiftmul32_FixPt_d12_3, 52));
  shiftmul32_FixPt_d6_3 <= shiftmul32_FixPt_d6 sll 1;
  shiftmul32_FixPt_sub_cast_33 <= signed(resize(shiftmul32_FixPt_d6_3, 55));
  shiftmul32_FixPt_add_cast_45 <= signed(resize(b10_unsigned, 58));
  shiftmul32_FixPt_add_temp <= resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize( - (shiftmul32_FixPt_cast_24), 10) + shiftmul32_FixPt_add_cast_36, 17) + shiftmul32_FixPt_add_cast_37, 20) + shiftmul32_FixPt_add_cast_38, 24) - shiftmul32_FixPt_sub_cast_28, 27) - shiftmul32_FixPt_sub_cast_29, 29) + shiftmul32_FixPt_add_cast_39, 30) + shiftmul32_FixPt_add_cast_40, 35) - shiftmul32_FixPt_sub_cast_30, 39) - shiftmul32_FixPt_sub_cast_31, 43) + shiftmul32_FixPt_add_cast_41, 44) + shiftmul32_FixPt_add_cast_42, 47) + shiftmul32_FixPt_add_cast_43, 48) + shiftmul32_FixPt_add_cast_44, 52) - shiftmul32_FixPt_sub_cast_32, 55) - shiftmul32_FixPt_sub_cast_33, 58) + shiftmul32_FixPt_add_cast_45;
  y15_tmp <= shiftmul32_FixPt_add_temp(5 DOWNTO 0);
  y17_tmp <= resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(shiftmul32_FixPt_d8 sll 1, 9) - resize(shiftmul32_FixPt_d10 sll 1, 9), 16) + resize(b12_unsigned, 16), 19) + resize(shiftmul32_FixPt_d4 sll 1, 19), 23) - resize(shiftmul32_FixPt_d14 sll 1, 23), 26) - resize(b2_unsigned, 26), 28) + resize(shiftmul32_FixPt_d16 sll 1, 28), 29) + resize(b16_unsigned, 29), 34) + resize(b1_unsigned, 34), 38) + resize(shiftmul32_FixPt_d15 sll 1, 38), 42) - resize(shiftmul32_FixPt_d3 sll 1, 42), 43) - resize(b3_unsigned, 43), 46) - resize(shiftmul32_FixPt_d13 sll 1, 46), 47) - resize(b13_unsigned, 47), 51) + resize(shiftmul32_FixPt_d5 sll 1, 51), 54) + resize(shiftmul32_FixPt_d11 sll 1, 54), 57) - resize(b7_unsigned, 57), 5);
  shiftmul32_FixPt_d9_5 <= shiftmul32_FixPt_d9 sll 1;
  shiftmul32_FixPt_cast_25 <= signed(resize(shiftmul32_FixPt_d9_5, 6));
  shiftmul32_FixPt_d14_3 <= shiftmul32_FixPt_d14 sll 1;
  shiftmul32_FixPt_add_cast_46 <= signed(resize(shiftmul32_FixPt_d14_3, 10));
  shiftmul32_FixPt_sub_cast_34 <= signed(resize(b2_unsigned, 17));
  shiftmul32_FixPt_d7_6 <= shiftmul32_FixPt_d7 sll 1;
  shiftmul32_FixPt_add_cast_47 <= signed(resize(shiftmul32_FixPt_d7_6, 20));
  shiftmul32_FixPt_d12_4 <= shiftmul32_FixPt_d12 sll 1;
  shiftmul32_FixPt_sub_cast_35 <= signed(resize(shiftmul32_FixPt_d12_4, 24));
  shiftmul32_FixPt_sub_cast_36 <= signed(resize(b16_unsigned, 27));
  shiftmul32_FixPt_d11_4 <= shiftmul32_FixPt_d11 sll 1;
  shiftmul32_FixPt_add_cast_48 <= signed(resize(shiftmul32_FixPt_d11_4, 29));
  shiftmul32_FixPt_add_cast_49 <= signed(resize(b11_unsigned, 30));
  shiftmul32_FixPt_sub_cast_37 <= signed(resize(b6_unsigned, 35));
  shiftmul32_FixPt_d1_3 <= shiftmul32_FixPt_d1 sll 1;
  shiftmul32_FixPt_add_cast_50 <= signed(resize(shiftmul32_FixPt_d1_3, 39));
  shiftmul32_FixPt_d5_4 <= shiftmul32_FixPt_d5 sll 1;
  shiftmul32_FixPt_sub_cast_38 <= signed(resize(shiftmul32_FixPt_d5_4, 43));
  shiftmul32_FixPt_sub_cast_39 <= signed(resize(b5_unsigned, 44));
  shiftmul32_FixPt_d10_3 <= shiftmul32_FixPt_d10 sll 1;
  shiftmul32_FixPt_add_cast_51 <= signed(resize(shiftmul32_FixPt_d10_3, 47));
  shiftmul32_FixPt_add_cast_52 <= signed(resize(b10_unsigned, 48));
  shiftmul32_FixPt_d15_2 <= shiftmul32_FixPt_d15 sll 1;
  shiftmul32_FixPt_sub_cast_40 <= signed(resize(shiftmul32_FixPt_d15_2, 52));
  shiftmul32_FixPt_d13_3 <= shiftmul32_FixPt_d13 sll 1;
  shiftmul32_FixPt_sub_cast_41 <= signed(resize(shiftmul32_FixPt_d13_3, 55));
  shiftmul32_FixPt_add_cast_53 <= signed(resize(b8_unsigned, 58));
  shiftmul32_FixPt_cast_26 <= resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize( - (shiftmul32_FixPt_cast_25), 10) + shiftmul32_FixPt_add_cast_46, 17) - shiftmul32_FixPt_sub_cast_34, 20) + shiftmul32_FixPt_add_cast_47, 24) - shiftmul32_FixPt_sub_cast_35, 27) - shiftmul32_FixPt_sub_cast_36, 29) + shiftmul32_FixPt_add_cast_48, 30) + shiftmul32_FixPt_add_cast_49, 35) - shiftmul32_FixPt_sub_cast_37, 39) + shiftmul32_FixPt_add_cast_50, 43) - shiftmul32_FixPt_sub_cast_38, 44) - shiftmul32_FixPt_sub_cast_39, 47) + shiftmul32_FixPt_add_cast_51, 48) + shiftmul32_FixPt_add_cast_52, 52) - shiftmul32_FixPt_sub_cast_40, 55) - shiftmul32_FixPt_sub_cast_41, 58) + shiftmul32_FixPt_add_cast_53, 59);
  y19_tmp <= unsigned(shiftmul32_FixPt_cast_26(5 DOWNTO 0));
  shiftmul32_FixPt_d1_4 <= shiftmul32_FixPt_d1 sll 1;
  shiftmul32_FixPt_cast_27 <= signed(resize(shiftmul32_FixPt_d1_4, 6));
  shiftmul32_FixPt_d5_5 <= shiftmul32_FixPt_d5 sll 1;
  shiftmul32_FixPt_sub_cast_42 <= signed(resize(shiftmul32_FixPt_d5_5, 10));
  shiftmul32_FixPt_sub_cast_43 <= signed(resize(b11_unsigned, 17));
  shiftmul32_FixPt_d14_4 <= shiftmul32_FixPt_d14 sll 1;
  shiftmul32_FixPt_sub_cast_44 <= signed(resize(shiftmul32_FixPt_d14_4, 20));
  shiftmul32_FixPt_d16_5 <= shiftmul32_FixPt_d16 sll 1;
  shiftmul32_FixPt_add_cast_54 <= signed(resize(shiftmul32_FixPt_d16_5, 24));
  shiftmul32_FixPt_add_cast_55 <= signed(resize(b13_unsigned, 27));
  shiftmul32_FixPt_d10_4 <= shiftmul32_FixPt_d10 sll 1;
  shiftmul32_FixPt_add_cast_56 <= signed(resize(shiftmul32_FixPt_d10_4, 29));
  shiftmul32_FixPt_add_cast_57 <= signed(resize(b10_unsigned, 30));
  shiftmul32_FixPt_add_cast_58 <= signed(resize(b7_unsigned, 35));
  shiftmul32_FixPt_d4_5 <= shiftmul32_FixPt_d4 sll 1;
  shiftmul32_FixPt_add_cast_59 <= signed(resize(shiftmul32_FixPt_d4_5, 39));
  shiftmul32_FixPt_d1_5 <= shiftmul32_FixPt_d1 sll 1;
  shiftmul32_FixPt_add_cast_60 <= signed(resize(shiftmul32_FixPt_d1_5, 43));
  shiftmul32_FixPt_add_cast_61 <= signed(resize(b1_unsigned, 44));
  shiftmul32_FixPt_d3_5 <= shiftmul32_FixPt_d3 sll 1;
  shiftmul32_FixPt_add_cast_62 <= signed(resize(shiftmul32_FixPt_d3_5, 47));
  shiftmul32_FixPt_add_cast_63 <= signed(resize(b3_unsigned, 48));
  shiftmul32_FixPt_d6_4 <= shiftmul32_FixPt_d6 sll 1;
  shiftmul32_FixPt_add_cast_64 <= signed(resize(shiftmul32_FixPt_d6_4, 52));
  shiftmul32_FixPt_d9_6 <= shiftmul32_FixPt_d9 sll 1;
  shiftmul32_FixPt_add_cast_65 <= signed(resize(shiftmul32_FixPt_d9_6, 55));
  shiftmul32_FixPt_add_cast_66 <= signed(resize(b12_unsigned, 58));
  shiftmul32_FixPt_cast_28 <= resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize( - (shiftmul32_FixPt_cast_27), 10) - shiftmul32_FixPt_sub_cast_42, 17) - shiftmul32_FixPt_sub_cast_43, 20) - shiftmul32_FixPt_sub_cast_44, 24) + shiftmul32_FixPt_add_cast_54, 27) + shiftmul32_FixPt_add_cast_55, 29) + shiftmul32_FixPt_add_cast_56, 30) + shiftmul32_FixPt_add_cast_57, 35) + shiftmul32_FixPt_add_cast_58, 39) + shiftmul32_FixPt_add_cast_59, 43) + shiftmul32_FixPt_add_cast_60, 44) + shiftmul32_FixPt_add_cast_61, 47) + shiftmul32_FixPt_add_cast_62, 48) + shiftmul32_FixPt_add_cast_63, 52) + shiftmul32_FixPt_add_cast_64, 55) + shiftmul32_FixPt_add_cast_65, 58) + shiftmul32_FixPt_add_cast_66, 59);
  y21_tmp <= unsigned(shiftmul32_FixPt_cast_28(7 DOWNTO 0));
  y23_tmp <= resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(shiftmul32_FixPt_d6 sll 1, 9) - resize(shiftmul32_FixPt_d13 sll 1, 9), 16) + resize(b9_unsigned, 16), 19) - resize(shiftmul32_FixPt_d16 sll 1, 19), 23) - resize(shiftmul32_FixPt_d10 sll 1, 23), 26) + resize(b3_unsigned, 26), 28) - resize(shiftmul32_FixPt_d5 sll 1, 28), 29) - resize(b5_unsigned, 29), 34) + resize(b12_unsigned, 34), 38) + resize(shiftmul32_FixPt_d14 sll 1, 38), 42) - resize(shiftmul32_FixPt_d7 sll 1, 42), 43) - resize(b7_unsigned, 43), 46) + resize(shiftmul32_FixPt_d1 sll 1, 46), 47) + resize(b1_unsigned, 47), 51) - resize(shiftmul32_FixPt_d8 sll 1, 51), 54) + resize(shiftmul32_FixPt_d15 sll 1, 54), 57) + resize(b11_unsigned, 57), 7);
  shiftmul32_FixPt_cast_29 <= resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(shiftmul32_FixPt_d3 sll 1, 9) - resize(shiftmul32_FixPt_d12 sll 1, 9), 16) + resize(b16_unsigned, 16), 19) + resize(shiftmul32_FixPt_d8 sll 1, 19), 23) - resize(shiftmul32_FixPt_d2 sll 1, 23), 26) + resize(b11_unsigned, 26), 28) + resize(shiftmul32_FixPt_d13 sll 1, 28), 29) + resize(b13_unsigned, 29), 34) - resize(b4_unsigned, 34), 38) + resize(shiftmul32_FixPt_d6 sll 1, 38), 42) - resize(shiftmul32_FixPt_d15 sll 1, 42), 43) - resize(b15_unsigned, 43), 46) - resize(shiftmul32_FixPt_d9 sll 1, 46), 47) - resize(b9_unsigned, 47), 51) + resize(shiftmul32_FixPt_d1 sll 1, 51), 54) - resize(shiftmul32_FixPt_d10 sll 1, 54), 57) - resize(b14_unsigned, 57), 58);
  y25_tmp <= signed(shiftmul32_FixPt_cast_29(7 DOWNTO 0));
  shiftmul32_FixPt_cast_30 <= resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(shiftmul32_FixPt_d10 sll 1, 9) + resize(shiftmul32_FixPt_d4 sll 1, 9), 16) + resize(b3_unsigned, 16), 19) - resize(shiftmul32_FixPt_d11 sll 1, 19), 23) - resize(shiftmul32_FixPt_d9 sll 1, 23), 26) + resize(b5_unsigned, 26), 28) + resize(shiftmul32_FixPt_d15 sll 1, 28), 29) + resize(b15_unsigned, 29), 34) - resize(b2_unsigned, 34), 38) + resize(shiftmul32_FixPt_d12 sll 1, 38), 42) + resize(shiftmul32_FixPt_d8 sll 1, 42), 43) + resize(b8_unsigned, 43), 46) - resize(shiftmul32_FixPt_d6 sll 1, 46), 47) - resize(b6_unsigned, 47), 51) - resize(shiftmul32_FixPt_d14 sll 1, 51), 54) + resize(shiftmul32_FixPt_d1 sll 1, 54), 57) - resize(b13_unsigned, 57), 58);
  y27_tmp <= signed(shiftmul32_FixPt_cast_30(6 DOWNTO 0));
  shiftmul32_FixPt_d6_5 <= shiftmul32_FixPt_d6 sll 1;
  shiftmul32_FixPt_cast_31 <= signed(resize(shiftmul32_FixPt_d6_5, 6));
  shiftmul32_FixPt_d16_6 <= shiftmul32_FixPt_d16 sll 1;
  shiftmul32_FixPt_add_cast_67 <= signed(resize(shiftmul32_FixPt_d16_6, 10));
  shiftmul32_FixPt_add_cast_68 <= signed(resize(b7_unsigned, 17));
  shiftmul32_FixPt_d15_3 <= shiftmul32_FixPt_d15 sll 1;
  shiftmul32_FixPt_sub_cast_45 <= signed(resize(shiftmul32_FixPt_d15_3, 20));
  shiftmul32_FixPt_d4_6 <= shiftmul32_FixPt_d4 sll 1;
  shiftmul32_FixPt_sub_cast_46 <= signed(resize(shiftmul32_FixPt_d4_6, 24));
  shiftmul32_FixPt_sub_cast_47 <= signed(resize(b8_unsigned, 27));
  shiftmul32_FixPt_d14_5 <= shiftmul32_FixPt_d14 sll 1;
  shiftmul32_FixPt_add_cast_69 <= signed(resize(shiftmul32_FixPt_d14_5, 29));
  shiftmul32_FixPt_add_cast_70 <= signed(resize(b14_unsigned, 30));
  shiftmul32_FixPt_add_cast_71 <= signed(resize(b3_unsigned, 35));
  shiftmul32_FixPt_d9_7 <= shiftmul32_FixPt_d9 sll 1;
  shiftmul32_FixPt_add_cast_72 <= signed(resize(shiftmul32_FixPt_d9_7, 39));
  shiftmul32_FixPt_d13_4 <= shiftmul32_FixPt_d13 sll 1;
  shiftmul32_FixPt_sub_cast_48 <= signed(resize(shiftmul32_FixPt_d13_4, 43));
  shiftmul32_FixPt_sub_cast_49 <= signed(resize(b13_unsigned, 44));
  shiftmul32_FixPt_d2_6 <= shiftmul32_FixPt_d2 sll 1;
  shiftmul32_FixPt_sub_cast_50 <= signed(resize(shiftmul32_FixPt_d2_6, 47));
  shiftmul32_FixPt_sub_cast_51 <= signed(resize(b2_unsigned, 48));
  shiftmul32_FixPt_d10_5 <= shiftmul32_FixPt_d10 sll 1;
  shiftmul32_FixPt_sub_cast_52 <= signed(resize(shiftmul32_FixPt_d10_5, 52));
  shiftmul32_FixPt_d12_5 <= shiftmul32_FixPt_d12 sll 1;
  shiftmul32_FixPt_add_cast_73 <= signed(resize(shiftmul32_FixPt_d12_5, 55));
  shiftmul32_FixPt_add_cast_74 <= signed(resize(b1_unsigned, 58));
  shiftmul32_FixPt_add_temp_1 <= resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize( - (shiftmul32_FixPt_cast_31), 10) + shiftmul32_FixPt_add_cast_67, 17) + shiftmul32_FixPt_add_cast_68, 20) - shiftmul32_FixPt_sub_cast_45, 24) - shiftmul32_FixPt_sub_cast_46, 27) - shiftmul32_FixPt_sub_cast_47, 29) + shiftmul32_FixPt_add_cast_69, 30) + shiftmul32_FixPt_add_cast_70, 35) + shiftmul32_FixPt_add_cast_71, 39) + shiftmul32_FixPt_add_cast_72, 43) - shiftmul32_FixPt_sub_cast_48, 44) - shiftmul32_FixPt_sub_cast_49, 47) - shiftmul32_FixPt_sub_cast_50, 48) - shiftmul32_FixPt_sub_cast_51, 52) - shiftmul32_FixPt_sub_cast_52, 55) + shiftmul32_FixPt_add_cast_73, 58) + shiftmul32_FixPt_add_cast_74;
  y29_tmp <= shiftmul32_FixPt_add_temp_1(5 DOWNTO 0);
  shiftmul32_FixPt_d16_7 <= shiftmul32_FixPt_d16 sll 1;
  shiftmul32_FixPt_cast_32 <= signed(resize(shiftmul32_FixPt_d16_7, 6));
  shiftmul32_FixPt_d15_4 <= shiftmul32_FixPt_d15 sll 1;
  shiftmul32_FixPt_add_cast_75 <= signed(resize(shiftmul32_FixPt_d15_4, 10));
  shiftmul32_FixPt_add_cast_76 <= signed(resize(b13_unsigned, 17));
  shiftmul32_FixPt_d12_6 <= shiftmul32_FixPt_d12 sll 1;
  shiftmul32_FixPt_sub_cast_53 <= signed(resize(shiftmul32_FixPt_d12_6, 20));
  shiftmul32_FixPt_d11_5 <= shiftmul32_FixPt_d11 sll 1;
  shiftmul32_FixPt_add_cast_77 <= signed(resize(shiftmul32_FixPt_d11_5, 24));
  shiftmul32_FixPt_sub_cast_54 <= signed(resize(b10_unsigned, 27));
  shiftmul32_FixPt_d9_8 <= shiftmul32_FixPt_d9 sll 1;
  shiftmul32_FixPt_add_cast_78 <= signed(resize(shiftmul32_FixPt_d9_8, 29));
  shiftmul32_FixPt_add_cast_79 <= signed(resize(b9_unsigned, 30));
  shiftmul32_FixPt_sub_cast_55 <= signed(resize(b8_unsigned, 35));
  shiftmul32_FixPt_d7_7 <= shiftmul32_FixPt_d7 sll 1;
  shiftmul32_FixPt_add_cast_80 <= signed(resize(shiftmul32_FixPt_d7_7, 39));
  shiftmul32_FixPt_d6_6 <= shiftmul32_FixPt_d6 sll 1;
  shiftmul32_FixPt_sub_cast_56 <= signed(resize(shiftmul32_FixPt_d6_6, 43));
  shiftmul32_FixPt_sub_cast_57 <= signed(resize(b6_unsigned, 44));
  shiftmul32_FixPt_d5_6 <= shiftmul32_FixPt_d5 sll 1;
  shiftmul32_FixPt_add_cast_81 <= signed(resize(shiftmul32_FixPt_d5_6, 47));
  shiftmul32_FixPt_add_cast_82 <= signed(resize(b5_unsigned, 48));
  shiftmul32_FixPt_d4_7 <= shiftmul32_FixPt_d4 sll 1;
  shiftmul32_FixPt_sub_cast_58 <= signed(resize(shiftmul32_FixPt_d4_7, 52));
  shiftmul32_FixPt_d3_6 <= shiftmul32_FixPt_d3 sll 1;
  shiftmul32_FixPt_add_cast_83 <= signed(resize(shiftmul32_FixPt_d3_6, 55));
  shiftmul32_FixPt_sub_cast_59 <= signed(resize(b2_unsigned, 58));
  shiftmul32_FixPt_sub_temp_2 <= resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize(resize( - (shiftmul32_FixPt_cast_32), 10) + shiftmul32_FixPt_add_cast_75, 17) + shiftmul32_FixPt_add_cast_76, 20) - shiftmul32_FixPt_sub_cast_53, 24) + shiftmul32_FixPt_add_cast_77, 27) - shiftmul32_FixPt_sub_cast_54, 29) + shiftmul32_FixPt_add_cast_78, 30) + shiftmul32_FixPt_add_cast_79, 35) - shiftmul32_FixPt_sub_cast_55, 39) + shiftmul32_FixPt_add_cast_80, 43) - shiftmul32_FixPt_sub_cast_56, 44) - shiftmul32_FixPt_sub_cast_57, 47) + shiftmul32_FixPt_add_cast_81, 48) + shiftmul32_FixPt_add_cast_82, 52) - shiftmul32_FixPt_sub_cast_58, 55) + shiftmul32_FixPt_add_cast_83, 58) - shiftmul32_FixPt_sub_cast_59;
  y31_tmp <= shiftmul32_FixPt_sub_temp_2(7 DOWNTO 0);

  y1 <= std_logic_vector(y1_tmp);

  y3 <= std_logic_vector(y3_tmp);

  y5 <= std_logic_vector(y5_tmp);

  y7 <= std_logic_vector(y7_tmp);

  y9 <= std_logic_vector(y9_tmp);

  y11 <= std_logic_vector(y11_tmp);

  y13 <= std_logic_vector(y13_tmp);

  y15 <= std_logic_vector(y15_tmp);

  y17 <= std_logic_vector(y17_tmp);

  y19 <= std_logic_vector(y19_tmp);

  y21 <= std_logic_vector(y21_tmp);

  y23 <= std_logic_vector(y23_tmp);

  y25 <= std_logic_vector(y25_tmp);

  y27 <= std_logic_vector(y27_tmp);

  y29 <= std_logic_vector(y29_tmp);

  y31 <= std_logic_vector(y31_tmp);

  ce_out <= clk_enable;

END rtl;

