// -------------------------------------------------------------
// 
// File Name: G:\AI\IIT BHU\codegen\shiftmul32\hdlsrc\shiftmul32_FixPt.v
// Created: 2016-06-06 12:32:49
// 
// Generated by MATLAB 8.1, MATLAB Coder 2.4 and HDL Coder 3.2
// 
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Design base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// y1                            ce_out        1
// y3                            ce_out        1
// y5                            ce_out        1
// y7                            ce_out        1
// y9                            ce_out        1
// y11                           ce_out        1
// y13                           ce_out        1
// y15                           ce_out        1
// y17                           ce_out        1
// y19                           ce_out        1
// y21                           ce_out        1
// y23                           ce_out        1
// y25                           ce_out        1
// y27                           ce_out        1
// y29                           ce_out        1
// y31                           ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: shiftmul32_FixPt
// Source Path: shiftmul32_FixPt
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module shiftmul32_FixPt
          (
           clk,
           reset,
           clk_enable,
           b1,
           b2,
           b3,
           b4,
           b5,
           b6,
           b7,
           b8,
           b9,
           b10,
           b11,
           b12,
           b13,
           b14,
           b15,
           b16,
           ce_out,
           y1,
           y3,
           y5,
           y7,
           y9,
           y11,
           y13,
           y15,
           y17,
           y19,
           y21,
           y23,
           y25,
           y27,
           y29,
           y31
          );


  input   clk;
  input   reset;
  input   clk_enable;
  input   [1:0] b1;  // ufix2
  input   [1:0] b2;  // ufix2
  input   [1:0] b3;  // ufix2
  input   [1:0] b4;  // ufix2
  input   [1:0] b5;  // ufix2
  input   [1:0] b6;  // ufix2
  input   [1:0] b7;  // ufix2
  input   [1:0] b8;  // ufix2
  input   [1:0] b9;  // ufix2
  input   [1:0] b10;  // ufix2
  input   [1:0] b11;  // ufix2
  input   [1:0] b12;  // ufix2
  input   [1:0] b13;  // ufix2
  input   [1:0] b14;  // ufix2
  input   [1:0] b15;  // ufix2
  input   [1:0] b16;  // ufix2
  output  ce_out;
  output  [7:0] y1;  // ufix8
  output  signed [7:0] y3;  // sfix8
  output  [6:0] y5;  // ufix7
  output  signed [4:0] y7;  // sfix5
  output  [6:0] y9;  // ufix7
  output  signed [7:0] y11;  // sfix8
  output  signed [8:0] y13;  // sfix9
  output  signed [5:0] y15;  // sfix6
  output  [4:0] y17;  // ufix5
  output  [5:0] y19;  // ufix6
  output  [7:0] y21;  // ufix8
  output  [6:0] y23;  // ufix7
  output  signed [7:0] y25;  // sfix8
  output  signed [6:0] y27;  // sfix7
  output  signed [5:0] y29;  // sfix6
  output  signed [7:0] y31;  // sfix8


  wire enb;
  wire [1:0] shiftmul32_FixPt_d1;  // ufix2
  wire [1:0] shiftmul32_FixPt_d2;  // ufix2
  wire [1:0] shiftmul32_FixPt_d3;  // ufix2
  wire [1:0] shiftmul32_FixPt_d4;  // ufix2
  wire [1:0] shiftmul32_FixPt_d5;  // ufix2
  wire [1:0] shiftmul32_FixPt_d6;  // ufix2
  wire [1:0] shiftmul32_FixPt_d7;  // ufix2
  wire [1:0] shiftmul32_FixPt_d8;  // ufix2
  wire [1:0] shiftmul32_FixPt_d9;  // ufix2
  wire [1:0] shiftmul32_FixPt_d10;  // ufix2
  wire [1:0] shiftmul32_FixPt_d11;  // ufix2
  wire [1:0] shiftmul32_FixPt_d12;  // ufix2
  wire [1:0] shiftmul32_FixPt_d13;  // ufix2
  wire [1:0] shiftmul32_FixPt_d14;  // ufix2
  wire [1:0] shiftmul32_FixPt_d15;  // ufix2
  wire [1:0] shiftmul32_FixPt_d16;  // ufix2
  wire [1:0] shiftmul32_FixPt_d1_1;  // ufix2
  wire [1:0] shiftmul32_FixPt_d2_1;  // ufix2
  wire [8:0] shiftmul32_FixPt_add_temp;  // ufix9
  wire [15:0] shiftmul32_FixPt_add_temp_1;  // ufix16
  wire [1:0] shiftmul32_FixPt_d5_1;  // ufix2
  wire [18:0] shiftmul32_FixPt_add_temp_2;  // ufix19
  wire [1:0] shiftmul32_FixPt_d6_1;  // ufix2
  wire [22:0] shiftmul32_FixPt_add_temp_3;  // ufix23
  wire [25:0] shiftmul32_FixPt_add_temp_4;  // ufix26
  wire [1:0] shiftmul32_FixPt_d8_1;  // ufix2
  wire [27:0] shiftmul32_FixPt_add_temp_5;  // ufix28
  wire [28:0] shiftmul32_FixPt_add_temp_6;  // ufix29
  wire [33:0] shiftmul32_FixPt_add_temp_7;  // ufix34
  wire [1:0] shiftmul32_FixPt_d10_1;  // ufix2
  wire [37:0] shiftmul32_FixPt_add_temp_8;  // ufix38
  wire [1:0] shiftmul32_FixPt_d11_1;  // ufix2
  wire [41:0] shiftmul32_FixPt_add_temp_9;  // ufix42
  wire [42:0] shiftmul32_FixPt_add_temp_10;  // ufix43
  wire [1:0] shiftmul32_FixPt_d12_1;  // ufix2
  wire [45:0] shiftmul32_FixPt_add_temp_11;  // ufix46
  wire [46:0] shiftmul32_FixPt_add_temp_12;  // ufix47
  wire [1:0] shiftmul32_FixPt_d13_1;  // ufix2
  wire [50:0] shiftmul32_FixPt_add_temp_13;  // ufix51
  wire [1:0] shiftmul32_FixPt_d14_1;  // ufix2
  wire [53:0] shiftmul32_FixPt_add_temp_14;  // ufix54
  wire [1:0] shiftmul32_FixPt_d1_2;  // ufix2
  wire [1:0] shiftmul32_FixPt_d11_2;  // ufix2
  wire [8:0] shiftmul32_FixPt_sub_temp;  // ufix9
  wire [15:0] shiftmul32_FixPt_add_temp_15;  // ufix16
  wire [1:0] shiftmul32_FixPt_d2_2;  // ufix2
  wire [18:0] shiftmul32_FixPt_add_temp_16;  // ufix19
  wire [1:0] shiftmul32_FixPt_d13_2;  // ufix2
  wire [22:0] shiftmul32_FixPt_sub_temp_1;  // ufix23
  wire [25:0] shiftmul32_FixPt_sub_temp_2;  // ufix26
  wire [1:0] shiftmul32_FixPt_d3_1;  // ufix2
  wire [27:0] shiftmul32_FixPt_add_temp_17;  // ufix28
  wire [28:0] shiftmul32_FixPt_add_temp_18;  // ufix29
  wire [33:0] shiftmul32_FixPt_sub_temp_3;  // ufix34
  wire [1:0] shiftmul32_FixPt_d8_2;  // ufix2
  wire [37:0] shiftmul32_FixPt_sub_temp_4;  // ufix38
  wire [1:0] shiftmul32_FixPt_d4_1;  // ufix2
  wire [41:0] shiftmul32_FixPt_add_temp_19;  // ufix42
  wire [42:0] shiftmul32_FixPt_add_temp_20;  // ufix43
  wire [1:0] shiftmul32_FixPt_d15_1;  // ufix2
  wire [45:0] shiftmul32_FixPt_sub_temp_5;  // ufix46
  wire [46:0] shiftmul32_FixPt_sub_temp_6;  // ufix47
  wire [1:0] shiftmul32_FixPt_d7_1;  // ufix2
  wire [50:0] shiftmul32_FixPt_sub_temp_7;  // ufix51
  wire [1:0] shiftmul32_FixPt_d5_2;  // ufix2
  wire [53:0] shiftmul32_FixPt_add_temp_21;  // ufix54
  wire [56:0] shiftmul32_FixPt_sub_temp_8;  // ufix57
  wire [1:0] shiftmul32_FixPt_d7_2;  // ufix2
  wire [1:0] shiftmul32_FixPt_d13_3;  // ufix2
  wire signed [9:0] shiftmul32_FixPt_add_temp_22;  // sfix10
  wire signed [16:0] shiftmul32_FixPt_add_temp_23;  // sfix17
  wire [1:0] shiftmul32_FixPt_d6_2;  // ufix2
  wire signed [19:0] shiftmul32_FixPt_sub_temp_9;  // sfix20
  wire [1:0] shiftmul32_FixPt_d8_3;  // ufix2
  wire signed [23:0] shiftmul32_FixPt_sub_temp_10;  // sfix24
  wire signed [26:0] shiftmul32_FixPt_add_temp_24;  // sfix27
  wire [1:0] shiftmul32_FixPt_d2_3;  // ufix2
  wire signed [28:0] shiftmul32_FixPt_add_temp_25;  // sfix29
  wire signed [29:0] shiftmul32_FixPt_add_temp_26;  // sfix30
  wire signed [34:0] shiftmul32_FixPt_add_temp_27;  // sfix35
  wire [1:0] shiftmul32_FixPt_d5_3;  // ufix2
  wire signed [38:0] shiftmul32_FixPt_sub_temp_11;  // sfix39
  wire [1:0] shiftmul32_FixPt_d9_1;  // ufix2
  wire signed [42:0] shiftmul32_FixPt_sub_temp_12;  // sfix43
  wire signed [43:0] shiftmul32_FixPt_add_temp_28;  // sfix44
  wire [1:0] shiftmul32_FixPt_d11_3;  // ufix2
  wire signed [46:0] shiftmul32_FixPt_add_temp_29;  // sfix47
  wire signed [47:0] shiftmul32_FixPt_add_temp_30;  // sfix48
  wire [1:0] shiftmul32_FixPt_d3_2;  // ufix2
  wire signed [51:0] shiftmul32_FixPt_add_temp_31;  // sfix52
  wire [1:0] shiftmul32_FixPt_d16_1;  // ufix2
  wire signed [54:0] shiftmul32_FixPt_add_temp_32;  // sfix55
  wire signed [57:0] shiftmul32_FixPt_sub_temp_13;  // sfix58
  wire [1:0] shiftmul32_FixPt_d5_4;  // ufix2
  wire [1:0] shiftmul32_FixPt_d14_2;  // ufix2
  wire signed [9:0] shiftmul32_FixPt_sub_temp_14;  // sfix10
  wire signed [16:0] shiftmul32_FixPt_add_temp_33;  // sfix17
  wire [1:0] shiftmul32_FixPt_d9_2;  // ufix2
  wire signed [19:0] shiftmul32_FixPt_add_temp_34;  // sfix20
  wire [1:0] shiftmul32_FixPt_d15_2;  // ufix2
  wire signed [23:0] shiftmul32_FixPt_sub_temp_15;  // sfix24
  wire signed [26:0] shiftmul32_FixPt_sub_temp_16;  // sfix27
  wire [1:0] shiftmul32_FixPt_d4_2;  // ufix2
  wire signed [28:0] shiftmul32_FixPt_sub_temp_17;  // sfix29
  wire signed [29:0] shiftmul32_FixPt_sub_temp_18;  // sfix30
  wire signed [34:0] shiftmul32_FixPt_sub_temp_19;  // sfix35
  wire [1:0] shiftmul32_FixPt_d11_4;  // ufix2
  wire signed [38:0] shiftmul32_FixPt_add_temp_35;  // sfix39
  wire [1:0] shiftmul32_FixPt_d2_4;  // ufix2
  wire signed [42:0] shiftmul32_FixPt_add_temp_36;  // sfix43
  wire signed [43:0] shiftmul32_FixPt_add_temp_37;  // sfix44
  wire [1:0] shiftmul32_FixPt_d8_4;  // ufix2
  wire signed [46:0] shiftmul32_FixPt_add_temp_38;  // sfix47
  wire signed [47:0] shiftmul32_FixPt_add_temp_39;  // sfix48
  wire [1:0] shiftmul32_FixPt_d16_2;  // ufix2
  wire signed [51:0] shiftmul32_FixPt_sub_temp_20;  // sfix52
  wire [1:0] shiftmul32_FixPt_d7_3;  // ufix2
  wire signed [54:0] shiftmul32_FixPt_sub_temp_21;  // sfix55
  wire [1:0] shiftmul32_FixPt_d4_3;  // ufix2
  wire [1:0] shiftmul32_FixPt_d11_5;  // ufix2
  wire signed [9:0] shiftmul32_FixPt_sub_temp_22;  // sfix10
  wire signed [16:0] shiftmul32_FixPt_add_temp_40;  // sfix17
  wire [1:0] shiftmul32_FixPt_d1_3;  // ufix2
  wire signed [19:0] shiftmul32_FixPt_add_temp_41;  // sfix20
  wire [1:0] shiftmul32_FixPt_d7_4;  // ufix2
  wire signed [23:0] shiftmul32_FixPt_add_temp_42;  // sfix24
  wire signed [26:0] shiftmul32_FixPt_add_temp_43;  // sfix27
  wire [1:0] shiftmul32_FixPt_d12_2;  // ufix2
  wire signed [28:0] shiftmul32_FixPt_sub_temp_23;  // sfix29
  wire signed [29:0] shiftmul32_FixPt_sub_temp_24;  // sfix30
  wire signed [34:0] shiftmul32_FixPt_sub_temp_25;  // sfix35
  wire [1:0] shiftmul32_FixPt_d3_3;  // ufix2
  wire signed [38:0] shiftmul32_FixPt_sub_temp_26;  // sfix39
  wire [1:0] shiftmul32_FixPt_d10_2;  // ufix2
  wire signed [42:0] shiftmul32_FixPt_sub_temp_27;  // sfix43
  wire signed [43:0] shiftmul32_FixPt_sub_temp_28;  // sfix44
  wire [1:0] shiftmul32_FixPt_d16_3;  // ufix2
  wire signed [46:0] shiftmul32_FixPt_add_temp_44;  // sfix47
  wire signed [47:0] shiftmul32_FixPt_add_temp_45;  // sfix48
  wire [1:0] shiftmul32_FixPt_d9_3;  // ufix2
  wire signed [51:0] shiftmul32_FixPt_add_temp_46;  // sfix52
  wire [1:0] shiftmul32_FixPt_d2_5;  // ufix2
  wire signed [54:0] shiftmul32_FixPt_add_temp_47;  // sfix55
  wire signed [57:0] shiftmul32_FixPt_add_temp_48;  // sfix58
  wire [1:0] shiftmul32_FixPt_d12_3;  // ufix2
  wire [1:0] shiftmul32_FixPt_d15_3;  // ufix2
  wire [8:0] shiftmul32_FixPt_sub_temp_29;  // ufix9
  wire [15:0] shiftmul32_FixPt_add_temp_49;  // ufix16
  wire [1:0] shiftmul32_FixPt_d3_4;  // ufix2
  wire [18:0] shiftmul32_FixPt_sub_temp_30;  // ufix19
  wire [1:0] shiftmul32_FixPt_d1_4;  // ufix2
  wire [22:0] shiftmul32_FixPt_add_temp_50;  // ufix23
  wire [25:0] shiftmul32_FixPt_add_temp_51;  // ufix26
  wire [1:0] shiftmul32_FixPt_d7_5;  // ufix2
  wire [27:0] shiftmul32_FixPt_add_temp_52;  // ufix28
  wire [28:0] shiftmul32_FixPt_add_temp_53;  // ufix29
  wire [33:0] shiftmul32_FixPt_sub_temp_31;  // ufix34
  wire [1:0] shiftmul32_FixPt_d13_4;  // ufix2
  wire [37:0] shiftmul32_FixPt_add_temp_54;  // ufix38
  wire [1:0] shiftmul32_FixPt_d16_4;  // ufix2
  wire [41:0] shiftmul32_FixPt_sub_temp_32;  // ufix42
  wire [42:0] shiftmul32_FixPt_sub_temp_33;  // ufix43
  wire [1:0] shiftmul32_FixPt_d14_3;  // ufix2
  wire [45:0] shiftmul32_FixPt_sub_temp_34;  // ufix46
  wire [46:0] shiftmul32_FixPt_sub_temp_35;  // ufix47
  wire [1:0] shiftmul32_FixPt_d11_6;  // ufix2
  wire [50:0] shiftmul32_FixPt_add_temp_55;  // ufix51
  wire [1:0] shiftmul32_FixPt_d8_5;  // ufix2
  wire [53:0] shiftmul32_FixPt_sub_temp_36;  // ufix54
  wire [56:0] shiftmul32_FixPt_add_temp_56;  // ufix57
  wire [1:0] shiftmul32_FixPt_d3_5;  // ufix2
  wire [1:0] shiftmul32_FixPt_d8_6;  // ufix2
  wire signed [9:0] shiftmul32_FixPt_sub_temp_37;  // sfix10
  wire signed [16:0] shiftmul32_FixPt_add_temp_57;  // sfix17
  wire [1:0] shiftmul32_FixPt_d10_3;  // ufix2
  wire signed [19:0] shiftmul32_FixPt_add_temp_58;  // sfix20
  wire [1:0] shiftmul32_FixPt_d5_5;  // ufix2
  wire signed [23:0] shiftmul32_FixPt_add_temp_59;  // sfix24
  wire signed [26:0] shiftmul32_FixPt_add_temp_60;  // sfix27
  wire [1:0] shiftmul32_FixPt_d6_3;  // ufix2
  wire signed [28:0] shiftmul32_FixPt_add_temp_61;  // sfix29
  wire signed [29:0] shiftmul32_FixPt_add_temp_62;  // sfix30
  wire signed [34:0] shiftmul32_FixPt_add_temp_63;  // sfix35
  wire [1:0] shiftmul32_FixPt_d16_5;  // ufix2
  wire signed [38:0] shiftmul32_FixPt_add_temp_64;  // sfix39
  wire [1:0] shiftmul32_FixPt_d12_4;  // ufix2
  wire signed [42:0] shiftmul32_FixPt_sub_temp_38;  // sfix43
  wire signed [43:0] shiftmul32_FixPt_add_temp_65;  // sfix44
  wire [1:0] shiftmul32_FixPt_d7_6;  // ufix2
  wire signed [46:0] shiftmul32_FixPt_sub_temp_39;  // sfix47
  wire signed [47:0] shiftmul32_FixPt_sub_temp_40;  // sfix48
  wire [1:0] shiftmul32_FixPt_d2_6;  // ufix2
  wire signed [51:0] shiftmul32_FixPt_sub_temp_41;  // sfix52
  wire [1:0] shiftmul32_FixPt_d4_4;  // ufix2
  wire signed [54:0] shiftmul32_FixPt_sub_temp_42;  // sfix55
  wire [1:0] shiftmul32_FixPt_d7_7;  // ufix2
  wire [1:0] shiftmul32_FixPt_d9_4;  // ufix2
  wire signed [9:0] shiftmul32_FixPt_add_temp_66;  // sfix10
  wire signed [16:0] shiftmul32_FixPt_add_temp_67;  // sfix17
  wire [1:0] shiftmul32_FixPt_d13_5;  // ufix2
  wire signed [19:0] shiftmul32_FixPt_add_temp_68;  // sfix20
  wire [1:0] shiftmul32_FixPt_d3_6;  // ufix2
  wire signed [23:0] shiftmul32_FixPt_sub_temp_43;  // sfix24
  wire signed [26:0] shiftmul32_FixPt_sub_temp_44;  // sfix27
  wire [1:0] shiftmul32_FixPt_d1_5;  // ufix2
  wire signed [28:0] shiftmul32_FixPt_add_temp_69;  // sfix29
  wire signed [29:0] shiftmul32_FixPt_add_temp_70;  // sfix30
  wire signed [34:0] shiftmul32_FixPt_sub_temp_45;  // sfix35
  wire [1:0] shiftmul32_FixPt_d2_7;  // ufix2
  wire signed [38:0] shiftmul32_FixPt_sub_temp_46;  // sfix39
  wire [1:0] shiftmul32_FixPt_d14_4;  // ufix2
  wire signed [42:0] shiftmul32_FixPt_add_temp_71;  // sfix43
  wire signed [43:0] shiftmul32_FixPt_add_temp_72;  // sfix44
  wire [1:0] shiftmul32_FixPt_d4_5;  // ufix2
  wire signed [46:0] shiftmul32_FixPt_add_temp_73;  // sfix47
  wire signed [47:0] shiftmul32_FixPt_add_temp_74;  // sfix48
  wire [1:0] shiftmul32_FixPt_d12_5;  // ufix2
  wire signed [51:0] shiftmul32_FixPt_sub_temp_47;  // sfix52
  wire [1:0] shiftmul32_FixPt_d6_4;  // ufix2
  wire signed [54:0] shiftmul32_FixPt_sub_temp_48;  // sfix55
  wire [1:0] shiftmul32_FixPt_d8_7;  // ufix2
  wire [1:0] shiftmul32_FixPt_d10_4;  // ufix2
  wire [8:0] shiftmul32_FixPt_sub_temp_49;  // ufix9
  wire [15:0] shiftmul32_FixPt_add_temp_75;  // ufix16
  wire [1:0] shiftmul32_FixPt_d4_6;  // ufix2
  wire [18:0] shiftmul32_FixPt_add_temp_76;  // ufix19
  wire [1:0] shiftmul32_FixPt_d14_5;  // ufix2
  wire [22:0] shiftmul32_FixPt_sub_temp_50;  // ufix23
  wire [25:0] shiftmul32_FixPt_sub_temp_51;  // ufix26
  wire [1:0] shiftmul32_FixPt_d16_6;  // ufix2
  wire [27:0] shiftmul32_FixPt_add_temp_77;  // ufix28
  wire [28:0] shiftmul32_FixPt_add_temp_78;  // ufix29
  wire [33:0] shiftmul32_FixPt_add_temp_79;  // ufix34
  wire [1:0] shiftmul32_FixPt_d15_4;  // ufix2
  wire [37:0] shiftmul32_FixPt_add_temp_80;  // ufix38
  wire [1:0] shiftmul32_FixPt_d3_7;  // ufix2
  wire [41:0] shiftmul32_FixPt_sub_temp_52;  // ufix42
  wire [42:0] shiftmul32_FixPt_sub_temp_53;  // ufix43
  wire [1:0] shiftmul32_FixPt_d13_6;  // ufix2
  wire [45:0] shiftmul32_FixPt_sub_temp_54;  // ufix46
  wire [46:0] shiftmul32_FixPt_sub_temp_55;  // ufix47
  wire [1:0] shiftmul32_FixPt_d5_6;  // ufix2
  wire [50:0] shiftmul32_FixPt_add_temp_81;  // ufix51
  wire [1:0] shiftmul32_FixPt_d11_7;  // ufix2
  wire [53:0] shiftmul32_FixPt_add_temp_82;  // ufix54
  wire [1:0] shiftmul32_FixPt_d9_5;  // ufix2
  wire [1:0] shiftmul32_FixPt_d14_6;  // ufix2
  wire signed [9:0] shiftmul32_FixPt_add_temp_83;  // sfix10
  wire signed [16:0] shiftmul32_FixPt_sub_temp_56;  // sfix17
  wire [1:0] shiftmul32_FixPt_d7_8;  // ufix2
  wire signed [19:0] shiftmul32_FixPt_add_temp_84;  // sfix20
  wire [1:0] shiftmul32_FixPt_d12_6;  // ufix2
  wire signed [23:0] shiftmul32_FixPt_sub_temp_57;  // sfix24
  wire signed [26:0] shiftmul32_FixPt_sub_temp_58;  // sfix27
  wire [1:0] shiftmul32_FixPt_d11_8;  // ufix2
  wire signed [28:0] shiftmul32_FixPt_add_temp_85;  // sfix29
  wire signed [29:0] shiftmul32_FixPt_add_temp_86;  // sfix30
  wire signed [34:0] shiftmul32_FixPt_sub_temp_59;  // sfix35
  wire [1:0] shiftmul32_FixPt_d1_6;  // ufix2
  wire signed [38:0] shiftmul32_FixPt_add_temp_87;  // sfix39
  wire [1:0] shiftmul32_FixPt_d5_7;  // ufix2
  wire signed [42:0] shiftmul32_FixPt_sub_temp_60;  // sfix43
  wire signed [43:0] shiftmul32_FixPt_sub_temp_61;  // sfix44
  wire [1:0] shiftmul32_FixPt_d10_5;  // ufix2
  wire signed [46:0] shiftmul32_FixPt_add_temp_88;  // sfix47
  wire signed [47:0] shiftmul32_FixPt_add_temp_89;  // sfix48
  wire [1:0] shiftmul32_FixPt_d15_5;  // ufix2
  wire signed [51:0] shiftmul32_FixPt_sub_temp_62;  // sfix52
  wire [1:0] shiftmul32_FixPt_d13_7;  // ufix2
  wire signed [54:0] shiftmul32_FixPt_sub_temp_63;  // sfix55
  wire signed [57:0] shiftmul32_FixPt_add_temp_90;  // sfix58
  wire [1:0] shiftmul32_FixPt_d1_7;  // ufix2
  wire [1:0] shiftmul32_FixPt_d5_8;  // ufix2
  wire signed [9:0] shiftmul32_FixPt_sub_temp_64;  // sfix10
  wire signed [16:0] shiftmul32_FixPt_sub_temp_65;  // sfix17
  wire [1:0] shiftmul32_FixPt_d14_7;  // ufix2
  wire signed [19:0] shiftmul32_FixPt_sub_temp_66;  // sfix20
  wire [1:0] shiftmul32_FixPt_d16_7;  // ufix2
  wire signed [23:0] shiftmul32_FixPt_add_temp_91;  // sfix24
  wire signed [26:0] shiftmul32_FixPt_add_temp_92;  // sfix27
  wire [1:0] shiftmul32_FixPt_d10_6;  // ufix2
  wire signed [28:0] shiftmul32_FixPt_add_temp_93;  // sfix29
  wire signed [29:0] shiftmul32_FixPt_add_temp_94;  // sfix30
  wire signed [34:0] shiftmul32_FixPt_add_temp_95;  // sfix35
  wire [1:0] shiftmul32_FixPt_d4_7;  // ufix2
  wire signed [38:0] shiftmul32_FixPt_add_temp_96;  // sfix39
  wire [1:0] shiftmul32_FixPt_d1_8;  // ufix2
  wire signed [42:0] shiftmul32_FixPt_add_temp_97;  // sfix43
  wire signed [43:0] shiftmul32_FixPt_add_temp_98;  // sfix44
  wire [1:0] shiftmul32_FixPt_d3_8;  // ufix2
  wire signed [46:0] shiftmul32_FixPt_add_temp_99;  // sfix47
  wire signed [47:0] shiftmul32_FixPt_add_temp_100;  // sfix48
  wire [1:0] shiftmul32_FixPt_d6_5;  // ufix2
  wire signed [51:0] shiftmul32_FixPt_add_temp_101;  // sfix52
  wire [1:0] shiftmul32_FixPt_d9_6;  // ufix2
  wire signed [54:0] shiftmul32_FixPt_add_temp_102;  // sfix55
  wire signed [57:0] shiftmul32_FixPt_add_temp_103;  // sfix58
  wire [1:0] shiftmul32_FixPt_d6_6;  // ufix2
  wire [1:0] shiftmul32_FixPt_d13_8;  // ufix2
  wire [8:0] shiftmul32_FixPt_sub_temp_67;  // ufix9
  wire [15:0] shiftmul32_FixPt_add_temp_104;  // ufix16
  wire [1:0] shiftmul32_FixPt_d16_8;  // ufix2
  wire [18:0] shiftmul32_FixPt_sub_temp_68;  // ufix19
  wire [1:0] shiftmul32_FixPt_d10_7;  // ufix2
  wire [22:0] shiftmul32_FixPt_sub_temp_69;  // ufix23
  wire [25:0] shiftmul32_FixPt_add_temp_105;  // ufix26
  wire [1:0] shiftmul32_FixPt_d5_9;  // ufix2
  wire [27:0] shiftmul32_FixPt_sub_temp_70;  // ufix28
  wire [28:0] shiftmul32_FixPt_sub_temp_71;  // ufix29
  wire [33:0] shiftmul32_FixPt_add_temp_106;  // ufix34
  wire [1:0] shiftmul32_FixPt_d14_8;  // ufix2
  wire [37:0] shiftmul32_FixPt_add_temp_107;  // ufix38
  wire [1:0] shiftmul32_FixPt_d7_9;  // ufix2
  wire [41:0] shiftmul32_FixPt_sub_temp_72;  // ufix42
  wire [42:0] shiftmul32_FixPt_sub_temp_73;  // ufix43
  wire [1:0] shiftmul32_FixPt_d1_9;  // ufix2
  wire [45:0] shiftmul32_FixPt_add_temp_108;  // ufix46
  wire [46:0] shiftmul32_FixPt_add_temp_109;  // ufix47
  wire [1:0] shiftmul32_FixPt_d8_8;  // ufix2
  wire [50:0] shiftmul32_FixPt_sub_temp_74;  // ufix51
  wire [1:0] shiftmul32_FixPt_d15_6;  // ufix2
  wire [53:0] shiftmul32_FixPt_add_temp_110;  // ufix54
  wire [1:0] shiftmul32_FixPt_d3_9;  // ufix2
  wire [1:0] shiftmul32_FixPt_d12_7;  // ufix2
  wire [8:0] shiftmul32_FixPt_sub_temp_75;  // ufix9
  wire [15:0] shiftmul32_FixPt_add_temp_111;  // ufix16
  wire [1:0] shiftmul32_FixPt_d8_9;  // ufix2
  wire [18:0] shiftmul32_FixPt_add_temp_112;  // ufix19
  wire [1:0] shiftmul32_FixPt_d2_8;  // ufix2
  wire [22:0] shiftmul32_FixPt_sub_temp_76;  // ufix23
  wire [25:0] shiftmul32_FixPt_add_temp_113;  // ufix26
  wire [1:0] shiftmul32_FixPt_d13_9;  // ufix2
  wire [27:0] shiftmul32_FixPt_add_temp_114;  // ufix28
  wire [28:0] shiftmul32_FixPt_add_temp_115;  // ufix29
  wire [33:0] shiftmul32_FixPt_sub_temp_77;  // ufix34
  wire [1:0] shiftmul32_FixPt_d6_7;  // ufix2
  wire [37:0] shiftmul32_FixPt_add_temp_116;  // ufix38
  wire [1:0] shiftmul32_FixPt_d15_7;  // ufix2
  wire [41:0] shiftmul32_FixPt_sub_temp_78;  // ufix42
  wire [42:0] shiftmul32_FixPt_sub_temp_79;  // ufix43
  wire [1:0] shiftmul32_FixPt_d9_7;  // ufix2
  wire [45:0] shiftmul32_FixPt_sub_temp_80;  // ufix46
  wire [46:0] shiftmul32_FixPt_sub_temp_81;  // ufix47
  wire [1:0] shiftmul32_FixPt_d1_10;  // ufix2
  wire [50:0] shiftmul32_FixPt_add_temp_117;  // ufix51
  wire [1:0] shiftmul32_FixPt_d10_8;  // ufix2
  wire [53:0] shiftmul32_FixPt_sub_temp_82;  // ufix54
  wire [56:0] shiftmul32_FixPt_sub_temp_83;  // ufix57
  wire [1:0] shiftmul32_FixPt_d10_9;  // ufix2
  wire [1:0] shiftmul32_FixPt_d4_8;  // ufix2
  wire [8:0] shiftmul32_FixPt_add_temp_118;  // ufix9
  wire [15:0] shiftmul32_FixPt_add_temp_119;  // ufix16
  wire [1:0] shiftmul32_FixPt_d11_9;  // ufix2
  wire [18:0] shiftmul32_FixPt_sub_temp_84;  // ufix19
  wire [1:0] shiftmul32_FixPt_d9_8;  // ufix2
  wire [22:0] shiftmul32_FixPt_sub_temp_85;  // ufix23
  wire [25:0] shiftmul32_FixPt_add_temp_120;  // ufix26
  wire [1:0] shiftmul32_FixPt_d15_8;  // ufix2
  wire [27:0] shiftmul32_FixPt_add_temp_121;  // ufix28
  wire [28:0] shiftmul32_FixPt_add_temp_122;  // ufix29
  wire [33:0] shiftmul32_FixPt_sub_temp_86;  // ufix34
  wire [1:0] shiftmul32_FixPt_d12_8;  // ufix2
  wire [37:0] shiftmul32_FixPt_add_temp_123;  // ufix38
  wire [1:0] shiftmul32_FixPt_d8_10;  // ufix2
  wire [41:0] shiftmul32_FixPt_add_temp_124;  // ufix42
  wire [42:0] shiftmul32_FixPt_add_temp_125;  // ufix43
  wire [1:0] shiftmul32_FixPt_d6_8;  // ufix2
  wire [45:0] shiftmul32_FixPt_sub_temp_87;  // ufix46
  wire [46:0] shiftmul32_FixPt_sub_temp_88;  // ufix47
  wire [1:0] shiftmul32_FixPt_d14_9;  // ufix2
  wire [50:0] shiftmul32_FixPt_sub_temp_89;  // ufix51
  wire [1:0] shiftmul32_FixPt_d1_11;  // ufix2
  wire [53:0] shiftmul32_FixPt_add_temp_126;  // ufix54
  wire [56:0] shiftmul32_FixPt_sub_temp_90;  // ufix57
  wire [1:0] shiftmul32_FixPt_d6_9;  // ufix2
  wire [1:0] shiftmul32_FixPt_d16_9;  // ufix2
  wire signed [9:0] shiftmul32_FixPt_add_temp_127;  // sfix10
  wire signed [16:0] shiftmul32_FixPt_add_temp_128;  // sfix17
  wire [1:0] shiftmul32_FixPt_d15_9;  // ufix2
  wire signed [19:0] shiftmul32_FixPt_sub_temp_91;  // sfix20
  wire [1:0] shiftmul32_FixPt_d4_9;  // ufix2
  wire signed [23:0] shiftmul32_FixPt_sub_temp_92;  // sfix24
  wire signed [26:0] shiftmul32_FixPt_sub_temp_93;  // sfix27
  wire [1:0] shiftmul32_FixPt_d14_10;  // ufix2
  wire signed [28:0] shiftmul32_FixPt_add_temp_129;  // sfix29
  wire signed [29:0] shiftmul32_FixPt_add_temp_130;  // sfix30
  wire signed [34:0] shiftmul32_FixPt_add_temp_131;  // sfix35
  wire [1:0] shiftmul32_FixPt_d9_9;  // ufix2
  wire signed [38:0] shiftmul32_FixPt_add_temp_132;  // sfix39
  wire [1:0] shiftmul32_FixPt_d13_10;  // ufix2
  wire signed [42:0] shiftmul32_FixPt_sub_temp_94;  // sfix43
  wire signed [43:0] shiftmul32_FixPt_sub_temp_95;  // sfix44
  wire [1:0] shiftmul32_FixPt_d2_9;  // ufix2
  wire signed [46:0] shiftmul32_FixPt_sub_temp_96;  // sfix47
  wire signed [47:0] shiftmul32_FixPt_sub_temp_97;  // sfix48
  wire [1:0] shiftmul32_FixPt_d10_10;  // ufix2
  wire signed [51:0] shiftmul32_FixPt_sub_temp_98;  // sfix52
  wire [1:0] shiftmul32_FixPt_d12_9;  // ufix2
  wire signed [54:0] shiftmul32_FixPt_add_temp_133;  // sfix55
  wire [1:0] shiftmul32_FixPt_d16_10;  // ufix2
  wire [1:0] shiftmul32_FixPt_d15_10;  // ufix2
  wire signed [9:0] shiftmul32_FixPt_add_temp_134;  // sfix10
  wire signed [16:0] shiftmul32_FixPt_add_temp_135;  // sfix17
  wire [1:0] shiftmul32_FixPt_d12_10;  // ufix2
  wire signed [19:0] shiftmul32_FixPt_sub_temp_99;  // sfix20
  wire [1:0] shiftmul32_FixPt_d11_10;  // ufix2
  wire signed [23:0] shiftmul32_FixPt_add_temp_136;  // sfix24
  wire signed [26:0] shiftmul32_FixPt_sub_temp_100;  // sfix27
  wire [1:0] shiftmul32_FixPt_d9_10;  // ufix2
  wire signed [28:0] shiftmul32_FixPt_add_temp_137;  // sfix29
  wire signed [29:0] shiftmul32_FixPt_add_temp_138;  // sfix30
  wire signed [34:0] shiftmul32_FixPt_sub_temp_101;  // sfix35
  wire [1:0] shiftmul32_FixPt_d7_10;  // ufix2
  wire signed [38:0] shiftmul32_FixPt_add_temp_139;  // sfix39
  wire [1:0] shiftmul32_FixPt_d6_10;  // ufix2
  wire signed [42:0] shiftmul32_FixPt_sub_temp_102;  // sfix43
  wire signed [43:0] shiftmul32_FixPt_sub_temp_103;  // sfix44
  wire [1:0] shiftmul32_FixPt_d5_10;  // ufix2
  wire signed [46:0] shiftmul32_FixPt_add_temp_140;  // sfix47
  wire signed [47:0] shiftmul32_FixPt_add_temp_141;  // sfix48
  wire [1:0] shiftmul32_FixPt_d4_10;  // ufix2
  wire signed [51:0] shiftmul32_FixPt_sub_temp_104;  // sfix52
  wire [1:0] shiftmul32_FixPt_d3_10;  // ufix2
  wire signed [54:0] shiftmul32_FixPt_add_temp_142;  // sfix55


  assign enb = clk_enable;

  //spssa
  //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  //                                                                          %
  //        Generated by MATLAB 8.1, MATLAB Coder 2.4 and HDL Coder 3.2      %
  //                                                                          %
  //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  assign shiftmul32_FixPt_d1 = b1;
  assign shiftmul32_FixPt_d2 = b2;
  assign shiftmul32_FixPt_d3 = b3;
  assign shiftmul32_FixPt_d4 = b4;
  assign shiftmul32_FixPt_d5 = b5;
  assign shiftmul32_FixPt_d6 = b6;
  assign shiftmul32_FixPt_d7 = b7;
  assign shiftmul32_FixPt_d8 = b8;
  assign shiftmul32_FixPt_d9 = b9;
  assign shiftmul32_FixPt_d10 = b10;
  assign shiftmul32_FixPt_d11 = b11;
  assign shiftmul32_FixPt_d12 = b12;
  assign shiftmul32_FixPt_d13 = b13;
  assign shiftmul32_FixPt_d14 = b14;
  assign shiftmul32_FixPt_d15 = b15;
  assign shiftmul32_FixPt_d16 = b16;
  assign shiftmul32_FixPt_d1_1 = shiftmul32_FixPt_d1 <<< 1;
  assign shiftmul32_FixPt_d2_1 = shiftmul32_FixPt_d2 <<< 1;
  assign shiftmul32_FixPt_add_temp = shiftmul32_FixPt_d1_1 + shiftmul32_FixPt_d2_1;
  assign shiftmul32_FixPt_add_temp_1 = shiftmul32_FixPt_add_temp + b4;
  assign shiftmul32_FixPt_d5_1 = shiftmul32_FixPt_d5 <<< 1;
  assign shiftmul32_FixPt_add_temp_2 = shiftmul32_FixPt_add_temp_1 + shiftmul32_FixPt_d5_1;
  assign shiftmul32_FixPt_d6_1 = shiftmul32_FixPt_d6 <<< 1;
  assign shiftmul32_FixPt_add_temp_3 = shiftmul32_FixPt_add_temp_2 + shiftmul32_FixPt_d6_1;
  assign shiftmul32_FixPt_add_temp_4 = shiftmul32_FixPt_add_temp_3 + b7;
  assign shiftmul32_FixPt_d8_1 = shiftmul32_FixPt_d8 <<< 1;
  assign shiftmul32_FixPt_add_temp_5 = shiftmul32_FixPt_add_temp_4 + shiftmul32_FixPt_d8_1;
  assign shiftmul32_FixPt_add_temp_6 = shiftmul32_FixPt_add_temp_5 + b8;
  assign shiftmul32_FixPt_add_temp_7 = shiftmul32_FixPt_add_temp_6 + b9;
  assign shiftmul32_FixPt_d10_1 = shiftmul32_FixPt_d10 <<< 1;
  assign shiftmul32_FixPt_add_temp_8 = shiftmul32_FixPt_add_temp_7 + shiftmul32_FixPt_d10_1;
  assign shiftmul32_FixPt_d11_1 = shiftmul32_FixPt_d11 <<< 1;
  assign shiftmul32_FixPt_add_temp_9 = shiftmul32_FixPt_add_temp_8 + shiftmul32_FixPt_d11_1;
  assign shiftmul32_FixPt_add_temp_10 = shiftmul32_FixPt_add_temp_9 + b11;
  assign shiftmul32_FixPt_d12_1 = shiftmul32_FixPt_d12 <<< 1;
  assign shiftmul32_FixPt_add_temp_11 = shiftmul32_FixPt_add_temp_10 + shiftmul32_FixPt_d12_1;
  assign shiftmul32_FixPt_add_temp_12 = shiftmul32_FixPt_add_temp_11 + b12;
  assign shiftmul32_FixPt_d13_1 = shiftmul32_FixPt_d13 <<< 1;
  assign shiftmul32_FixPt_add_temp_13 = shiftmul32_FixPt_add_temp_12 + shiftmul32_FixPt_d13_1;
  assign shiftmul32_FixPt_d14_1 = shiftmul32_FixPt_d14 <<< 1;
  assign shiftmul32_FixPt_add_temp_14 = shiftmul32_FixPt_add_temp_13 + shiftmul32_FixPt_d14_1;
  assign y1 = shiftmul32_FixPt_add_temp_14 + b15;
  assign shiftmul32_FixPt_d1_2 = shiftmul32_FixPt_d1 <<< 1;
  assign shiftmul32_FixPt_d11_2 = shiftmul32_FixPt_d11 <<< 1;
  assign shiftmul32_FixPt_sub_temp = shiftmul32_FixPt_d1_2 - shiftmul32_FixPt_d11_2;
  assign shiftmul32_FixPt_add_temp_15 = shiftmul32_FixPt_sub_temp + b10;
  assign shiftmul32_FixPt_d2_2 = shiftmul32_FixPt_d2 <<< 1;
  assign shiftmul32_FixPt_add_temp_16 = shiftmul32_FixPt_add_temp_15 + shiftmul32_FixPt_d2_2;
  assign shiftmul32_FixPt_d13_2 = shiftmul32_FixPt_d13 <<< 1;
  assign shiftmul32_FixPt_sub_temp_1 = shiftmul32_FixPt_add_temp_16 - shiftmul32_FixPt_d13_2;
  assign shiftmul32_FixPt_sub_temp_2 = shiftmul32_FixPt_sub_temp_1 - b9;
  assign shiftmul32_FixPt_d3_1 = shiftmul32_FixPt_d3 <<< 1;
  assign shiftmul32_FixPt_add_temp_17 = shiftmul32_FixPt_sub_temp_2 + shiftmul32_FixPt_d3_1;
  assign shiftmul32_FixPt_add_temp_18 = shiftmul32_FixPt_add_temp_17 + b3;
  assign shiftmul32_FixPt_sub_temp_3 = shiftmul32_FixPt_add_temp_18 - b14;
  assign shiftmul32_FixPt_d8_2 = shiftmul32_FixPt_d8 <<< 1;
  assign shiftmul32_FixPt_sub_temp_4 = shiftmul32_FixPt_sub_temp_3 - shiftmul32_FixPt_d8_2;
  assign shiftmul32_FixPt_d4_1 = shiftmul32_FixPt_d4 <<< 1;
  assign shiftmul32_FixPt_add_temp_19 = shiftmul32_FixPt_sub_temp_4 + shiftmul32_FixPt_d4_1;
  assign shiftmul32_FixPt_add_temp_20 = shiftmul32_FixPt_add_temp_19 + b4;
  assign shiftmul32_FixPt_d15_1 = shiftmul32_FixPt_d15 <<< 1;
  assign shiftmul32_FixPt_sub_temp_5 = shiftmul32_FixPt_add_temp_20 - shiftmul32_FixPt_d15_1;
  assign shiftmul32_FixPt_sub_temp_6 = shiftmul32_FixPt_sub_temp_5 - b15;
  assign shiftmul32_FixPt_d7_1 = shiftmul32_FixPt_d7 <<< 1;
  assign shiftmul32_FixPt_sub_temp_7 = shiftmul32_FixPt_sub_temp_6 - shiftmul32_FixPt_d7_1;
  assign shiftmul32_FixPt_d5_2 = shiftmul32_FixPt_d5 <<< 1;
  assign shiftmul32_FixPt_add_temp_21 = shiftmul32_FixPt_sub_temp_7 + shiftmul32_FixPt_d5_2;
  assign shiftmul32_FixPt_sub_temp_8 = shiftmul32_FixPt_add_temp_21 - b16;
  assign y3 = shiftmul32_FixPt_sub_temp_8;
  assign shiftmul32_FixPt_d7_2 = shiftmul32_FixPt_d7 <<< 1;
  assign shiftmul32_FixPt_d13_3 = shiftmul32_FixPt_d13 <<< 1;
  assign shiftmul32_FixPt_add_temp_22 = ( - (shiftmul32_FixPt_d7_2)) + $signed({1'b0, shiftmul32_FixPt_d13_3});
  assign shiftmul32_FixPt_add_temp_23 = shiftmul32_FixPt_add_temp_22 + $signed({1'b0, b12});
  assign shiftmul32_FixPt_d6_2 = shiftmul32_FixPt_d6 <<< 1;
  assign shiftmul32_FixPt_sub_temp_9 = shiftmul32_FixPt_add_temp_23 - $signed({1'b0, shiftmul32_FixPt_d6_2});
  assign shiftmul32_FixPt_d8_3 = shiftmul32_FixPt_d8 <<< 1;
  assign shiftmul32_FixPt_sub_temp_10 = shiftmul32_FixPt_sub_temp_9 - $signed({1'b0, shiftmul32_FixPt_d8_3});
  assign shiftmul32_FixPt_add_temp_24 = shiftmul32_FixPt_sub_temp_10 + $signed({1'b0, b12});
  assign shiftmul32_FixPt_d2_3 = shiftmul32_FixPt_d2 <<< 1;
  assign shiftmul32_FixPt_add_temp_25 = shiftmul32_FixPt_add_temp_24 + $signed({1'b0, shiftmul32_FixPt_d2_3});
  assign shiftmul32_FixPt_add_temp_26 = shiftmul32_FixPt_add_temp_25 + $signed({1'b0, b2});
  assign shiftmul32_FixPt_add_temp_27 = shiftmul32_FixPt_add_temp_26 + $signed({1'b0, b15});
  assign shiftmul32_FixPt_d5_3 = shiftmul32_FixPt_d5 <<< 1;
  assign shiftmul32_FixPt_sub_temp_11 = shiftmul32_FixPt_add_temp_27 - $signed({1'b0, shiftmul32_FixPt_d5_3});
  assign shiftmul32_FixPt_d9_1 = shiftmul32_FixPt_d9 <<< 1;
  assign shiftmul32_FixPt_sub_temp_12 = shiftmul32_FixPt_sub_temp_11 - $signed({1'b0, shiftmul32_FixPt_d9_1});
  assign shiftmul32_FixPt_add_temp_28 = shiftmul32_FixPt_sub_temp_12 + $signed({1'b0, b9});
  assign shiftmul32_FixPt_d11_3 = shiftmul32_FixPt_d11 <<< 1;
  assign shiftmul32_FixPt_add_temp_29 = shiftmul32_FixPt_add_temp_28 + $signed({1'b0, shiftmul32_FixPt_d11_3});
  assign shiftmul32_FixPt_add_temp_30 = shiftmul32_FixPt_add_temp_29 + $signed({1'b0, b11});
  assign shiftmul32_FixPt_d3_2 = shiftmul32_FixPt_d3 <<< 1;
  assign shiftmul32_FixPt_add_temp_31 = shiftmul32_FixPt_add_temp_30 + $signed({1'b0, shiftmul32_FixPt_d3_2});
  assign shiftmul32_FixPt_d16_1 = shiftmul32_FixPt_d16 <<< 1;
  assign shiftmul32_FixPt_add_temp_32 = shiftmul32_FixPt_add_temp_31 + $signed({1'b0, shiftmul32_FixPt_d16_1});
  assign shiftmul32_FixPt_sub_temp_13 = shiftmul32_FixPt_add_temp_32 - $signed({1'b0, b10});
  assign y5 = shiftmul32_FixPt_sub_temp_13;
  assign shiftmul32_FixPt_d5_4 = shiftmul32_FixPt_d5 <<< 1;
  assign shiftmul32_FixPt_d14_2 = shiftmul32_FixPt_d14 <<< 1;
  assign shiftmul32_FixPt_sub_temp_14 = ( - (shiftmul32_FixPt_d5_4)) - $signed({1'b0, shiftmul32_FixPt_d14_2});
  assign shiftmul32_FixPt_add_temp_33 = shiftmul32_FixPt_sub_temp_14 + $signed({1'b0, b1});
  assign shiftmul32_FixPt_d9_2 = shiftmul32_FixPt_d9 <<< 1;
  assign shiftmul32_FixPt_add_temp_34 = shiftmul32_FixPt_add_temp_33 + $signed({1'b0, shiftmul32_FixPt_d9_2});
  assign shiftmul32_FixPt_d15_2 = shiftmul32_FixPt_d15 <<< 1;
  assign shiftmul32_FixPt_sub_temp_15 = shiftmul32_FixPt_add_temp_34 - $signed({1'b0, shiftmul32_FixPt_d15_2});
  assign shiftmul32_FixPt_sub_temp_16 = shiftmul32_FixPt_sub_temp_15 - $signed({1'b0, b6});
  assign shiftmul32_FixPt_d4_2 = shiftmul32_FixPt_d4 <<< 1;
  assign shiftmul32_FixPt_sub_temp_17 = shiftmul32_FixPt_sub_temp_16 - $signed({1'b0, shiftmul32_FixPt_d4_2});
  assign shiftmul32_FixPt_sub_temp_18 = shiftmul32_FixPt_sub_temp_17 - $signed({1'b0, b4});
  assign shiftmul32_FixPt_sub_temp_19 = shiftmul32_FixPt_sub_temp_18 - $signed({1'b0, b13});
  assign shiftmul32_FixPt_d11_4 = shiftmul32_FixPt_d11 <<< 1;
  assign shiftmul32_FixPt_add_temp_35 = shiftmul32_FixPt_sub_temp_19 + $signed({1'b0, shiftmul32_FixPt_d11_4});
  assign shiftmul32_FixPt_d2_4 = shiftmul32_FixPt_d2 <<< 1;
  assign shiftmul32_FixPt_add_temp_36 = shiftmul32_FixPt_add_temp_35 + $signed({1'b0, shiftmul32_FixPt_d2_4});
  assign shiftmul32_FixPt_add_temp_37 = shiftmul32_FixPt_add_temp_36 + $signed({1'b0, b2});
  assign shiftmul32_FixPt_d8_4 = shiftmul32_FixPt_d8 <<< 1;
  assign shiftmul32_FixPt_add_temp_38 = shiftmul32_FixPt_add_temp_37 + $signed({1'b0, shiftmul32_FixPt_d8_4});
  assign shiftmul32_FixPt_add_temp_39 = shiftmul32_FixPt_add_temp_38 + $signed({1'b0, b8});
  assign shiftmul32_FixPt_d16_2 = shiftmul32_FixPt_d16 <<< 1;
  assign shiftmul32_FixPt_sub_temp_20 = shiftmul32_FixPt_add_temp_39 - $signed({1'b0, shiftmul32_FixPt_d16_2});
  assign shiftmul32_FixPt_d7_3 = shiftmul32_FixPt_d7 <<< 1;
  assign shiftmul32_FixPt_sub_temp_21 = shiftmul32_FixPt_sub_temp_20 - $signed({1'b0, shiftmul32_FixPt_d7_3});
  assign y7 = shiftmul32_FixPt_sub_temp_21 - $signed({1'b0, b3});
  assign shiftmul32_FixPt_d4_3 = shiftmul32_FixPt_d4 <<< 1;
  assign shiftmul32_FixPt_d11_5 = shiftmul32_FixPt_d11 <<< 1;
  assign shiftmul32_FixPt_sub_temp_22 = ( - (shiftmul32_FixPt_d4_3)) - $signed({1'b0, shiftmul32_FixPt_d11_5});
  assign shiftmul32_FixPt_add_temp_40 = shiftmul32_FixPt_sub_temp_22 + $signed({1'b0, b8});
  assign shiftmul32_FixPt_d1_3 = shiftmul32_FixPt_d1 <<< 1;
  assign shiftmul32_FixPt_add_temp_41 = shiftmul32_FixPt_add_temp_40 + $signed({1'b0, shiftmul32_FixPt_d1_3});
  assign shiftmul32_FixPt_d7_4 = shiftmul32_FixPt_d7 <<< 1;
  assign shiftmul32_FixPt_add_temp_42 = shiftmul32_FixPt_add_temp_41 + $signed({1'b0, shiftmul32_FixPt_d7_4});
  assign shiftmul32_FixPt_add_temp_43 = shiftmul32_FixPt_add_temp_42 + $signed({1'b0, b14});
  assign shiftmul32_FixPt_d12_2 = shiftmul32_FixPt_d12 <<< 1;
  assign shiftmul32_FixPt_sub_temp_23 = shiftmul32_FixPt_add_temp_43 - $signed({1'b0, shiftmul32_FixPt_d12_2});
  assign shiftmul32_FixPt_sub_temp_24 = shiftmul32_FixPt_sub_temp_23 - $signed({1'b0, b12});
  assign shiftmul32_FixPt_sub_temp_25 = shiftmul32_FixPt_sub_temp_24 - $signed({1'b0, b5});
  assign shiftmul32_FixPt_d3_3 = shiftmul32_FixPt_d3 <<< 1;
  assign shiftmul32_FixPt_sub_temp_26 = shiftmul32_FixPt_sub_temp_25 - $signed({1'b0, shiftmul32_FixPt_d3_3});
  assign shiftmul32_FixPt_d10_2 = shiftmul32_FixPt_d10 <<< 1;
  assign shiftmul32_FixPt_sub_temp_27 = shiftmul32_FixPt_sub_temp_26 - $signed({1'b0, shiftmul32_FixPt_d10_2});
  assign shiftmul32_FixPt_sub_temp_28 = shiftmul32_FixPt_sub_temp_27 - $signed({1'b0, b10});
  assign shiftmul32_FixPt_d16_3 = shiftmul32_FixPt_d16 <<< 1;
  assign shiftmul32_FixPt_add_temp_44 = shiftmul32_FixPt_sub_temp_28 + $signed({1'b0, shiftmul32_FixPt_d16_3});
  assign shiftmul32_FixPt_add_temp_45 = shiftmul32_FixPt_add_temp_44 + $signed({1'b0, b16});
  assign shiftmul32_FixPt_d9_3 = shiftmul32_FixPt_d9 <<< 1;
  assign shiftmul32_FixPt_add_temp_46 = shiftmul32_FixPt_add_temp_45 + $signed({1'b0, shiftmul32_FixPt_d9_3});
  assign shiftmul32_FixPt_d2_5 = shiftmul32_FixPt_d2 <<< 1;
  assign shiftmul32_FixPt_add_temp_47 = shiftmul32_FixPt_add_temp_46 + $signed({1'b0, shiftmul32_FixPt_d2_5});
  assign shiftmul32_FixPt_add_temp_48 = shiftmul32_FixPt_add_temp_47 + $signed({1'b0, b6});
  assign y9 = shiftmul32_FixPt_add_temp_48;
  assign shiftmul32_FixPt_d12_3 = shiftmul32_FixPt_d12 <<< 1;
  assign shiftmul32_FixPt_d15_3 = shiftmul32_FixPt_d15 <<< 1;
  assign shiftmul32_FixPt_sub_temp_29 = shiftmul32_FixPt_d12_3 - shiftmul32_FixPt_d15_3;
  assign shiftmul32_FixPt_add_temp_49 = shiftmul32_FixPt_sub_temp_29 + b6;
  assign shiftmul32_FixPt_d3_4 = shiftmul32_FixPt_d3 <<< 1;
  assign shiftmul32_FixPt_sub_temp_30 = shiftmul32_FixPt_add_temp_49 - shiftmul32_FixPt_d3_4;
  assign shiftmul32_FixPt_d1_4 = shiftmul32_FixPt_d1 <<< 1;
  assign shiftmul32_FixPt_add_temp_50 = shiftmul32_FixPt_sub_temp_30 + shiftmul32_FixPt_d1_4;
  assign shiftmul32_FixPt_add_temp_51 = shiftmul32_FixPt_add_temp_50 + b4;
  assign shiftmul32_FixPt_d7_5 = shiftmul32_FixPt_d7 <<< 1;
  assign shiftmul32_FixPt_add_temp_52 = shiftmul32_FixPt_add_temp_51 + shiftmul32_FixPt_d7_5;
  assign shiftmul32_FixPt_add_temp_53 = shiftmul32_FixPt_add_temp_52 + b7;
  assign shiftmul32_FixPt_sub_temp_31 = shiftmul32_FixPt_add_temp_53 - b10;
  assign shiftmul32_FixPt_d13_4 = shiftmul32_FixPt_d13 <<< 1;
  assign shiftmul32_FixPt_add_temp_54 = shiftmul32_FixPt_sub_temp_31 + shiftmul32_FixPt_d13_4;
  assign shiftmul32_FixPt_d16_4 = shiftmul32_FixPt_d16 <<< 1;
  assign shiftmul32_FixPt_sub_temp_32 = shiftmul32_FixPt_add_temp_54 - shiftmul32_FixPt_d16_4;
  assign shiftmul32_FixPt_sub_temp_33 = shiftmul32_FixPt_sub_temp_32 - b16;
  assign shiftmul32_FixPt_d14_3 = shiftmul32_FixPt_d14 <<< 1;
  assign shiftmul32_FixPt_sub_temp_34 = shiftmul32_FixPt_sub_temp_33 - shiftmul32_FixPt_d14_3;
  assign shiftmul32_FixPt_sub_temp_35 = shiftmul32_FixPt_sub_temp_34 - b14;
  assign shiftmul32_FixPt_d11_6 = shiftmul32_FixPt_d11 <<< 1;
  assign shiftmul32_FixPt_add_temp_55 = shiftmul32_FixPt_sub_temp_35 + shiftmul32_FixPt_d11_6;
  assign shiftmul32_FixPt_d8_5 = shiftmul32_FixPt_d8 <<< 1;
  assign shiftmul32_FixPt_sub_temp_36 = shiftmul32_FixPt_add_temp_55 - shiftmul32_FixPt_d8_5;
  assign shiftmul32_FixPt_add_temp_56 = shiftmul32_FixPt_sub_temp_36 + b5;
  assign y11 = shiftmul32_FixPt_add_temp_56;
  assign shiftmul32_FixPt_d3_5 = shiftmul32_FixPt_d3 <<< 1;
  assign shiftmul32_FixPt_d8_6 = shiftmul32_FixPt_d8 <<< 1;
  assign shiftmul32_FixPt_sub_temp_37 = ( - (shiftmul32_FixPt_d3_5)) - $signed({1'b0, shiftmul32_FixPt_d8_6});
  assign shiftmul32_FixPt_add_temp_57 = shiftmul32_FixPt_sub_temp_37 + $signed({1'b0, b15});
  assign shiftmul32_FixPt_d10_3 = shiftmul32_FixPt_d10 <<< 1;
  assign shiftmul32_FixPt_add_temp_58 = shiftmul32_FixPt_add_temp_57 + $signed({1'b0, shiftmul32_FixPt_d10_3});
  assign shiftmul32_FixPt_d5_5 = shiftmul32_FixPt_d5 <<< 1;
  assign shiftmul32_FixPt_add_temp_59 = shiftmul32_FixPt_add_temp_58 + $signed({1'b0, shiftmul32_FixPt_d5_5});
  assign shiftmul32_FixPt_add_temp_60 = shiftmul32_FixPt_add_temp_59 + $signed({1'b0, b1});
  assign shiftmul32_FixPt_d6_3 = shiftmul32_FixPt_d6 <<< 1;
  assign shiftmul32_FixPt_add_temp_61 = shiftmul32_FixPt_add_temp_60 + $signed({1'b0, shiftmul32_FixPt_d6_3});
  assign shiftmul32_FixPt_add_temp_62 = shiftmul32_FixPt_add_temp_61 + $signed({1'b0, b6});
  assign shiftmul32_FixPt_add_temp_63 = shiftmul32_FixPt_add_temp_62 + $signed({1'b0, b11});
  assign shiftmul32_FixPt_d16_5 = shiftmul32_FixPt_d16 <<< 1;
  assign shiftmul32_FixPt_add_temp_64 = shiftmul32_FixPt_add_temp_63 + $signed({1'b0, shiftmul32_FixPt_d16_5});
  assign shiftmul32_FixPt_d12_4 = shiftmul32_FixPt_d12 <<< 1;
  assign shiftmul32_FixPt_sub_temp_38 = shiftmul32_FixPt_add_temp_64 - $signed({1'b0, shiftmul32_FixPt_d12_4});
  assign shiftmul32_FixPt_add_temp_65 = shiftmul32_FixPt_sub_temp_38 + $signed({1'b0, b12});
  assign shiftmul32_FixPt_d7_6 = shiftmul32_FixPt_d7 <<< 1;
  assign shiftmul32_FixPt_sub_temp_39 = shiftmul32_FixPt_add_temp_65 - $signed({1'b0, shiftmul32_FixPt_d7_6});
  assign shiftmul32_FixPt_sub_temp_40 = shiftmul32_FixPt_sub_temp_39 - $signed({1'b0, b7});
  assign shiftmul32_FixPt_d2_6 = shiftmul32_FixPt_d2 <<< 1;
  assign shiftmul32_FixPt_sub_temp_41 = shiftmul32_FixPt_sub_temp_40 - $signed({1'b0, shiftmul32_FixPt_d2_6});
  assign shiftmul32_FixPt_d4_4 = shiftmul32_FixPt_d4 <<< 1;
  assign shiftmul32_FixPt_sub_temp_42 = shiftmul32_FixPt_sub_temp_41 - $signed({1'b0, shiftmul32_FixPt_d4_4});
  assign y13 = shiftmul32_FixPt_sub_temp_42 - $signed({1'b0, b9});
  assign shiftmul32_FixPt_d7_7 = shiftmul32_FixPt_d7 <<< 1;
  assign shiftmul32_FixPt_d9_4 = shiftmul32_FixPt_d9 <<< 1;
  assign shiftmul32_FixPt_add_temp_66 = ( - (shiftmul32_FixPt_d7_7)) + $signed({1'b0, shiftmul32_FixPt_d9_4});
  assign shiftmul32_FixPt_add_temp_67 = shiftmul32_FixPt_add_temp_66 + $signed({1'b0, b5});
  assign shiftmul32_FixPt_d13_5 = shiftmul32_FixPt_d13 <<< 1;
  assign shiftmul32_FixPt_add_temp_68 = shiftmul32_FixPt_add_temp_67 + $signed({1'b0, shiftmul32_FixPt_d13_5});
  assign shiftmul32_FixPt_d3_6 = shiftmul32_FixPt_d3 <<< 1;
  assign shiftmul32_FixPt_sub_temp_43 = shiftmul32_FixPt_add_temp_68 - $signed({1'b0, shiftmul32_FixPt_d3_6});
  assign shiftmul32_FixPt_sub_temp_44 = shiftmul32_FixPt_sub_temp_43 - $signed({1'b0, b15});
  assign shiftmul32_FixPt_d1_5 = shiftmul32_FixPt_d1 <<< 1;
  assign shiftmul32_FixPt_add_temp_69 = shiftmul32_FixPt_sub_temp_44 + $signed({1'b0, shiftmul32_FixPt_d1_5});
  assign shiftmul32_FixPt_add_temp_70 = shiftmul32_FixPt_add_temp_69 + $signed({1'b0, b1});
  assign shiftmul32_FixPt_sub_temp_45 = shiftmul32_FixPt_add_temp_70 - $signed({1'b0, b16});
  assign shiftmul32_FixPt_d2_7 = shiftmul32_FixPt_d2 <<< 1;
  assign shiftmul32_FixPt_sub_temp_46 = shiftmul32_FixPt_sub_temp_45 - $signed({1'b0, shiftmul32_FixPt_d2_7});
  assign shiftmul32_FixPt_d14_4 = shiftmul32_FixPt_d14 <<< 1;
  assign shiftmul32_FixPt_add_temp_71 = shiftmul32_FixPt_sub_temp_46 + $signed({1'b0, shiftmul32_FixPt_d14_4});
  assign shiftmul32_FixPt_add_temp_72 = shiftmul32_FixPt_add_temp_71 + $signed({1'b0, b14});
  assign shiftmul32_FixPt_d4_5 = shiftmul32_FixPt_d4 <<< 1;
  assign shiftmul32_FixPt_add_temp_73 = shiftmul32_FixPt_add_temp_72 + $signed({1'b0, shiftmul32_FixPt_d4_5});
  assign shiftmul32_FixPt_add_temp_74 = shiftmul32_FixPt_add_temp_73 + $signed({1'b0, b4});
  assign shiftmul32_FixPt_d12_5 = shiftmul32_FixPt_d12 <<< 1;
  assign shiftmul32_FixPt_sub_temp_47 = shiftmul32_FixPt_add_temp_74 - $signed({1'b0, shiftmul32_FixPt_d12_5});
  assign shiftmul32_FixPt_d6_4 = shiftmul32_FixPt_d6 <<< 1;
  assign shiftmul32_FixPt_sub_temp_48 = shiftmul32_FixPt_sub_temp_47 - $signed({1'b0, shiftmul32_FixPt_d6_4});
  assign y15 = shiftmul32_FixPt_sub_temp_48 + $signed({1'b0, b10});
  assign shiftmul32_FixPt_d8_7 = shiftmul32_FixPt_d8 <<< 1;
  assign shiftmul32_FixPt_d10_4 = shiftmul32_FixPt_d10 <<< 1;
  assign shiftmul32_FixPt_sub_temp_49 = shiftmul32_FixPt_d8_7 - shiftmul32_FixPt_d10_4;
  assign shiftmul32_FixPt_add_temp_75 = shiftmul32_FixPt_sub_temp_49 + b12;
  assign shiftmul32_FixPt_d4_6 = shiftmul32_FixPt_d4 <<< 1;
  assign shiftmul32_FixPt_add_temp_76 = shiftmul32_FixPt_add_temp_75 + shiftmul32_FixPt_d4_6;
  assign shiftmul32_FixPt_d14_5 = shiftmul32_FixPt_d14 <<< 1;
  assign shiftmul32_FixPt_sub_temp_50 = shiftmul32_FixPt_add_temp_76 - shiftmul32_FixPt_d14_5;
  assign shiftmul32_FixPt_sub_temp_51 = shiftmul32_FixPt_sub_temp_50 - b2;
  assign shiftmul32_FixPt_d16_6 = shiftmul32_FixPt_d16 <<< 1;
  assign shiftmul32_FixPt_add_temp_77 = shiftmul32_FixPt_sub_temp_51 + shiftmul32_FixPt_d16_6;
  assign shiftmul32_FixPt_add_temp_78 = shiftmul32_FixPt_add_temp_77 + b16;
  assign shiftmul32_FixPt_add_temp_79 = shiftmul32_FixPt_add_temp_78 + b1;
  assign shiftmul32_FixPt_d15_4 = shiftmul32_FixPt_d15 <<< 1;
  assign shiftmul32_FixPt_add_temp_80 = shiftmul32_FixPt_add_temp_79 + shiftmul32_FixPt_d15_4;
  assign shiftmul32_FixPt_d3_7 = shiftmul32_FixPt_d3 <<< 1;
  assign shiftmul32_FixPt_sub_temp_52 = shiftmul32_FixPt_add_temp_80 - shiftmul32_FixPt_d3_7;
  assign shiftmul32_FixPt_sub_temp_53 = shiftmul32_FixPt_sub_temp_52 - b3;
  assign shiftmul32_FixPt_d13_6 = shiftmul32_FixPt_d13 <<< 1;
  assign shiftmul32_FixPt_sub_temp_54 = shiftmul32_FixPt_sub_temp_53 - shiftmul32_FixPt_d13_6;
  assign shiftmul32_FixPt_sub_temp_55 = shiftmul32_FixPt_sub_temp_54 - b13;
  assign shiftmul32_FixPt_d5_6 = shiftmul32_FixPt_d5 <<< 1;
  assign shiftmul32_FixPt_add_temp_81 = shiftmul32_FixPt_sub_temp_55 + shiftmul32_FixPt_d5_6;
  assign shiftmul32_FixPt_d11_7 = shiftmul32_FixPt_d11 <<< 1;
  assign shiftmul32_FixPt_add_temp_82 = shiftmul32_FixPt_add_temp_81 + shiftmul32_FixPt_d11_7;
  assign y17 = shiftmul32_FixPt_add_temp_82 - b7;
  assign shiftmul32_FixPt_d9_5 = shiftmul32_FixPt_d9 <<< 1;
  assign shiftmul32_FixPt_d14_6 = shiftmul32_FixPt_d14 <<< 1;
  assign shiftmul32_FixPt_add_temp_83 = ( - (shiftmul32_FixPt_d9_5)) + $signed({1'b0, shiftmul32_FixPt_d14_6});
  assign shiftmul32_FixPt_sub_temp_56 = shiftmul32_FixPt_add_temp_83 - $signed({1'b0, b2});
  assign shiftmul32_FixPt_d7_8 = shiftmul32_FixPt_d7 <<< 1;
  assign shiftmul32_FixPt_add_temp_84 = shiftmul32_FixPt_sub_temp_56 + $signed({1'b0, shiftmul32_FixPt_d7_8});
  assign shiftmul32_FixPt_d12_6 = shiftmul32_FixPt_d12 <<< 1;
  assign shiftmul32_FixPt_sub_temp_57 = shiftmul32_FixPt_add_temp_84 - $signed({1'b0, shiftmul32_FixPt_d12_6});
  assign shiftmul32_FixPt_sub_temp_58 = shiftmul32_FixPt_sub_temp_57 - $signed({1'b0, b16});
  assign shiftmul32_FixPt_d11_8 = shiftmul32_FixPt_d11 <<< 1;
  assign shiftmul32_FixPt_add_temp_85 = shiftmul32_FixPt_sub_temp_58 + $signed({1'b0, shiftmul32_FixPt_d11_8});
  assign shiftmul32_FixPt_add_temp_86 = shiftmul32_FixPt_add_temp_85 + $signed({1'b0, b11});
  assign shiftmul32_FixPt_sub_temp_59 = shiftmul32_FixPt_add_temp_86 - $signed({1'b0, b6});
  assign shiftmul32_FixPt_d1_6 = shiftmul32_FixPt_d1 <<< 1;
  assign shiftmul32_FixPt_add_temp_87 = shiftmul32_FixPt_sub_temp_59 + $signed({1'b0, shiftmul32_FixPt_d1_6});
  assign shiftmul32_FixPt_d5_7 = shiftmul32_FixPt_d5 <<< 1;
  assign shiftmul32_FixPt_sub_temp_60 = shiftmul32_FixPt_add_temp_87 - $signed({1'b0, shiftmul32_FixPt_d5_7});
  assign shiftmul32_FixPt_sub_temp_61 = shiftmul32_FixPt_sub_temp_60 - $signed({1'b0, b5});
  assign shiftmul32_FixPt_d10_5 = shiftmul32_FixPt_d10 <<< 1;
  assign shiftmul32_FixPt_add_temp_88 = shiftmul32_FixPt_sub_temp_61 + $signed({1'b0, shiftmul32_FixPt_d10_5});
  assign shiftmul32_FixPt_add_temp_89 = shiftmul32_FixPt_add_temp_88 + $signed({1'b0, b10});
  assign shiftmul32_FixPt_d15_5 = shiftmul32_FixPt_d15 <<< 1;
  assign shiftmul32_FixPt_sub_temp_62 = shiftmul32_FixPt_add_temp_89 - $signed({1'b0, shiftmul32_FixPt_d15_5});
  assign shiftmul32_FixPt_d13_7 = shiftmul32_FixPt_d13 <<< 1;
  assign shiftmul32_FixPt_sub_temp_63 = shiftmul32_FixPt_sub_temp_62 - $signed({1'b0, shiftmul32_FixPt_d13_7});
  assign shiftmul32_FixPt_add_temp_90 = shiftmul32_FixPt_sub_temp_63 + $signed({1'b0, b8});
  assign y19 = shiftmul32_FixPt_add_temp_90;
  assign shiftmul32_FixPt_d1_7 = shiftmul32_FixPt_d1 <<< 1;
  assign shiftmul32_FixPt_d5_8 = shiftmul32_FixPt_d5 <<< 1;
  assign shiftmul32_FixPt_sub_temp_64 = ( - (shiftmul32_FixPt_d1_7)) - $signed({1'b0, shiftmul32_FixPt_d5_8});
  assign shiftmul32_FixPt_sub_temp_65 = shiftmul32_FixPt_sub_temp_64 - $signed({1'b0, b11});
  assign shiftmul32_FixPt_d14_7 = shiftmul32_FixPt_d14 <<< 1;
  assign shiftmul32_FixPt_sub_temp_66 = shiftmul32_FixPt_sub_temp_65 - $signed({1'b0, shiftmul32_FixPt_d14_7});
  assign shiftmul32_FixPt_d16_7 = shiftmul32_FixPt_d16 <<< 1;
  assign shiftmul32_FixPt_add_temp_91 = shiftmul32_FixPt_sub_temp_66 + $signed({1'b0, shiftmul32_FixPt_d16_7});
  assign shiftmul32_FixPt_add_temp_92 = shiftmul32_FixPt_add_temp_91 + $signed({1'b0, b13});
  assign shiftmul32_FixPt_d10_6 = shiftmul32_FixPt_d10 <<< 1;
  assign shiftmul32_FixPt_add_temp_93 = shiftmul32_FixPt_add_temp_92 + $signed({1'b0, shiftmul32_FixPt_d10_6});
  assign shiftmul32_FixPt_add_temp_94 = shiftmul32_FixPt_add_temp_93 + $signed({1'b0, b10});
  assign shiftmul32_FixPt_add_temp_95 = shiftmul32_FixPt_add_temp_94 + $signed({1'b0, b7});
  assign shiftmul32_FixPt_d4_7 = shiftmul32_FixPt_d4 <<< 1;
  assign shiftmul32_FixPt_add_temp_96 = shiftmul32_FixPt_add_temp_95 + $signed({1'b0, shiftmul32_FixPt_d4_7});
  assign shiftmul32_FixPt_d1_8 = shiftmul32_FixPt_d1 <<< 1;
  assign shiftmul32_FixPt_add_temp_97 = shiftmul32_FixPt_add_temp_96 + $signed({1'b0, shiftmul32_FixPt_d1_8});
  assign shiftmul32_FixPt_add_temp_98 = shiftmul32_FixPt_add_temp_97 + $signed({1'b0, b1});
  assign shiftmul32_FixPt_d3_8 = shiftmul32_FixPt_d3 <<< 1;
  assign shiftmul32_FixPt_add_temp_99 = shiftmul32_FixPt_add_temp_98 + $signed({1'b0, shiftmul32_FixPt_d3_8});
  assign shiftmul32_FixPt_add_temp_100 = shiftmul32_FixPt_add_temp_99 + $signed({1'b0, b3});
  assign shiftmul32_FixPt_d6_5 = shiftmul32_FixPt_d6 <<< 1;
  assign shiftmul32_FixPt_add_temp_101 = shiftmul32_FixPt_add_temp_100 + $signed({1'b0, shiftmul32_FixPt_d6_5});
  assign shiftmul32_FixPt_d9_6 = shiftmul32_FixPt_d9 <<< 1;
  assign shiftmul32_FixPt_add_temp_102 = shiftmul32_FixPt_add_temp_101 + $signed({1'b0, shiftmul32_FixPt_d9_6});
  assign shiftmul32_FixPt_add_temp_103 = shiftmul32_FixPt_add_temp_102 + $signed({1'b0, b12});
  assign y21 = shiftmul32_FixPt_add_temp_103;
  assign shiftmul32_FixPt_d6_6 = shiftmul32_FixPt_d6 <<< 1;
  assign shiftmul32_FixPt_d13_8 = shiftmul32_FixPt_d13 <<< 1;
  assign shiftmul32_FixPt_sub_temp_67 = shiftmul32_FixPt_d6_6 - shiftmul32_FixPt_d13_8;
  assign shiftmul32_FixPt_add_temp_104 = shiftmul32_FixPt_sub_temp_67 + b9;
  assign shiftmul32_FixPt_d16_8 = shiftmul32_FixPt_d16 <<< 1;
  assign shiftmul32_FixPt_sub_temp_68 = shiftmul32_FixPt_add_temp_104 - shiftmul32_FixPt_d16_8;
  assign shiftmul32_FixPt_d10_7 = shiftmul32_FixPt_d10 <<< 1;
  assign shiftmul32_FixPt_sub_temp_69 = shiftmul32_FixPt_sub_temp_68 - shiftmul32_FixPt_d10_7;
  assign shiftmul32_FixPt_add_temp_105 = shiftmul32_FixPt_sub_temp_69 + b3;
  assign shiftmul32_FixPt_d5_9 = shiftmul32_FixPt_d5 <<< 1;
  assign shiftmul32_FixPt_sub_temp_70 = shiftmul32_FixPt_add_temp_105 - shiftmul32_FixPt_d5_9;
  assign shiftmul32_FixPt_sub_temp_71 = shiftmul32_FixPt_sub_temp_70 - b5;
  assign shiftmul32_FixPt_add_temp_106 = shiftmul32_FixPt_sub_temp_71 + b12;
  assign shiftmul32_FixPt_d14_8 = shiftmul32_FixPt_d14 <<< 1;
  assign shiftmul32_FixPt_add_temp_107 = shiftmul32_FixPt_add_temp_106 + shiftmul32_FixPt_d14_8;
  assign shiftmul32_FixPt_d7_9 = shiftmul32_FixPt_d7 <<< 1;
  assign shiftmul32_FixPt_sub_temp_72 = shiftmul32_FixPt_add_temp_107 - shiftmul32_FixPt_d7_9;
  assign shiftmul32_FixPt_sub_temp_73 = shiftmul32_FixPt_sub_temp_72 - b7;
  assign shiftmul32_FixPt_d1_9 = shiftmul32_FixPt_d1 <<< 1;
  assign shiftmul32_FixPt_add_temp_108 = shiftmul32_FixPt_sub_temp_73 + shiftmul32_FixPt_d1_9;
  assign shiftmul32_FixPt_add_temp_109 = shiftmul32_FixPt_add_temp_108 + b1;
  assign shiftmul32_FixPt_d8_8 = shiftmul32_FixPt_d8 <<< 1;
  assign shiftmul32_FixPt_sub_temp_74 = shiftmul32_FixPt_add_temp_109 - shiftmul32_FixPt_d8_8;
  assign shiftmul32_FixPt_d15_6 = shiftmul32_FixPt_d15 <<< 1;
  assign shiftmul32_FixPt_add_temp_110 = shiftmul32_FixPt_sub_temp_74 + shiftmul32_FixPt_d15_6;
  assign y23 = shiftmul32_FixPt_add_temp_110 + b11;
  assign shiftmul32_FixPt_d3_9 = shiftmul32_FixPt_d3 <<< 1;
  assign shiftmul32_FixPt_d12_7 = shiftmul32_FixPt_d12 <<< 1;
  assign shiftmul32_FixPt_sub_temp_75 = shiftmul32_FixPt_d3_9 - shiftmul32_FixPt_d12_7;
  assign shiftmul32_FixPt_add_temp_111 = shiftmul32_FixPt_sub_temp_75 + b16;
  assign shiftmul32_FixPt_d8_9 = shiftmul32_FixPt_d8 <<< 1;
  assign shiftmul32_FixPt_add_temp_112 = shiftmul32_FixPt_add_temp_111 + shiftmul32_FixPt_d8_9;
  assign shiftmul32_FixPt_d2_8 = shiftmul32_FixPt_d2 <<< 1;
  assign shiftmul32_FixPt_sub_temp_76 = shiftmul32_FixPt_add_temp_112 - shiftmul32_FixPt_d2_8;
  assign shiftmul32_FixPt_add_temp_113 = shiftmul32_FixPt_sub_temp_76 + b11;
  assign shiftmul32_FixPt_d13_9 = shiftmul32_FixPt_d13 <<< 1;
  assign shiftmul32_FixPt_add_temp_114 = shiftmul32_FixPt_add_temp_113 + shiftmul32_FixPt_d13_9;
  assign shiftmul32_FixPt_add_temp_115 = shiftmul32_FixPt_add_temp_114 + b13;
  assign shiftmul32_FixPt_sub_temp_77 = shiftmul32_FixPt_add_temp_115 - b4;
  assign shiftmul32_FixPt_d6_7 = shiftmul32_FixPt_d6 <<< 1;
  assign shiftmul32_FixPt_add_temp_116 = shiftmul32_FixPt_sub_temp_77 + shiftmul32_FixPt_d6_7;
  assign shiftmul32_FixPt_d15_7 = shiftmul32_FixPt_d15 <<< 1;
  assign shiftmul32_FixPt_sub_temp_78 = shiftmul32_FixPt_add_temp_116 - shiftmul32_FixPt_d15_7;
  assign shiftmul32_FixPt_sub_temp_79 = shiftmul32_FixPt_sub_temp_78 - b15;
  assign shiftmul32_FixPt_d9_7 = shiftmul32_FixPt_d9 <<< 1;
  assign shiftmul32_FixPt_sub_temp_80 = shiftmul32_FixPt_sub_temp_79 - shiftmul32_FixPt_d9_7;
  assign shiftmul32_FixPt_sub_temp_81 = shiftmul32_FixPt_sub_temp_80 - b9;
  assign shiftmul32_FixPt_d1_10 = shiftmul32_FixPt_d1 <<< 1;
  assign shiftmul32_FixPt_add_temp_117 = shiftmul32_FixPt_sub_temp_81 + shiftmul32_FixPt_d1_10;
  assign shiftmul32_FixPt_d10_8 = shiftmul32_FixPt_d10 <<< 1;
  assign shiftmul32_FixPt_sub_temp_82 = shiftmul32_FixPt_add_temp_117 - shiftmul32_FixPt_d10_8;
  assign shiftmul32_FixPt_sub_temp_83 = shiftmul32_FixPt_sub_temp_82 - b14;
  assign y25 = shiftmul32_FixPt_sub_temp_83;
  assign shiftmul32_FixPt_d10_9 = shiftmul32_FixPt_d10 <<< 1;
  assign shiftmul32_FixPt_d4_8 = shiftmul32_FixPt_d4 <<< 1;
  assign shiftmul32_FixPt_add_temp_118 = shiftmul32_FixPt_d10_9 + shiftmul32_FixPt_d4_8;
  assign shiftmul32_FixPt_add_temp_119 = shiftmul32_FixPt_add_temp_118 + b3;
  assign shiftmul32_FixPt_d11_9 = shiftmul32_FixPt_d11 <<< 1;
  assign shiftmul32_FixPt_sub_temp_84 = shiftmul32_FixPt_add_temp_119 - shiftmul32_FixPt_d11_9;
  assign shiftmul32_FixPt_d9_8 = shiftmul32_FixPt_d9 <<< 1;
  assign shiftmul32_FixPt_sub_temp_85 = shiftmul32_FixPt_sub_temp_84 - shiftmul32_FixPt_d9_8;
  assign shiftmul32_FixPt_add_temp_120 = shiftmul32_FixPt_sub_temp_85 + b5;
  assign shiftmul32_FixPt_d15_8 = shiftmul32_FixPt_d15 <<< 1;
  assign shiftmul32_FixPt_add_temp_121 = shiftmul32_FixPt_add_temp_120 + shiftmul32_FixPt_d15_8;
  assign shiftmul32_FixPt_add_temp_122 = shiftmul32_FixPt_add_temp_121 + b15;
  assign shiftmul32_FixPt_sub_temp_86 = shiftmul32_FixPt_add_temp_122 - b2;
  assign shiftmul32_FixPt_d12_8 = shiftmul32_FixPt_d12 <<< 1;
  assign shiftmul32_FixPt_add_temp_123 = shiftmul32_FixPt_sub_temp_86 + shiftmul32_FixPt_d12_8;
  assign shiftmul32_FixPt_d8_10 = shiftmul32_FixPt_d8 <<< 1;
  assign shiftmul32_FixPt_add_temp_124 = shiftmul32_FixPt_add_temp_123 + shiftmul32_FixPt_d8_10;
  assign shiftmul32_FixPt_add_temp_125 = shiftmul32_FixPt_add_temp_124 + b8;
  assign shiftmul32_FixPt_d6_8 = shiftmul32_FixPt_d6 <<< 1;
  assign shiftmul32_FixPt_sub_temp_87 = shiftmul32_FixPt_add_temp_125 - shiftmul32_FixPt_d6_8;
  assign shiftmul32_FixPt_sub_temp_88 = shiftmul32_FixPt_sub_temp_87 - b6;
  assign shiftmul32_FixPt_d14_9 = shiftmul32_FixPt_d14 <<< 1;
  assign shiftmul32_FixPt_sub_temp_89 = shiftmul32_FixPt_sub_temp_88 - shiftmul32_FixPt_d14_9;
  assign shiftmul32_FixPt_d1_11 = shiftmul32_FixPt_d1 <<< 1;
  assign shiftmul32_FixPt_add_temp_126 = shiftmul32_FixPt_sub_temp_89 + shiftmul32_FixPt_d1_11;
  assign shiftmul32_FixPt_sub_temp_90 = shiftmul32_FixPt_add_temp_126 - b13;
  assign y27 = shiftmul32_FixPt_sub_temp_90;
  assign shiftmul32_FixPt_d6_9 = shiftmul32_FixPt_d6 <<< 1;
  assign shiftmul32_FixPt_d16_9 = shiftmul32_FixPt_d16 <<< 1;
  assign shiftmul32_FixPt_add_temp_127 = ( - (shiftmul32_FixPt_d6_9)) + $signed({1'b0, shiftmul32_FixPt_d16_9});
  assign shiftmul32_FixPt_add_temp_128 = shiftmul32_FixPt_add_temp_127 + $signed({1'b0, b7});
  assign shiftmul32_FixPt_d15_9 = shiftmul32_FixPt_d15 <<< 1;
  assign shiftmul32_FixPt_sub_temp_91 = shiftmul32_FixPt_add_temp_128 - $signed({1'b0, shiftmul32_FixPt_d15_9});
  assign shiftmul32_FixPt_d4_9 = shiftmul32_FixPt_d4 <<< 1;
  assign shiftmul32_FixPt_sub_temp_92 = shiftmul32_FixPt_sub_temp_91 - $signed({1'b0, shiftmul32_FixPt_d4_9});
  assign shiftmul32_FixPt_sub_temp_93 = shiftmul32_FixPt_sub_temp_92 - $signed({1'b0, b8});
  assign shiftmul32_FixPt_d14_10 = shiftmul32_FixPt_d14 <<< 1;
  assign shiftmul32_FixPt_add_temp_129 = shiftmul32_FixPt_sub_temp_93 + $signed({1'b0, shiftmul32_FixPt_d14_10});
  assign shiftmul32_FixPt_add_temp_130 = shiftmul32_FixPt_add_temp_129 + $signed({1'b0, b14});
  assign shiftmul32_FixPt_add_temp_131 = shiftmul32_FixPt_add_temp_130 + $signed({1'b0, b3});
  assign shiftmul32_FixPt_d9_9 = shiftmul32_FixPt_d9 <<< 1;
  assign shiftmul32_FixPt_add_temp_132 = shiftmul32_FixPt_add_temp_131 + $signed({1'b0, shiftmul32_FixPt_d9_9});
  assign shiftmul32_FixPt_d13_10 = shiftmul32_FixPt_d13 <<< 1;
  assign shiftmul32_FixPt_sub_temp_94 = shiftmul32_FixPt_add_temp_132 - $signed({1'b0, shiftmul32_FixPt_d13_10});
  assign shiftmul32_FixPt_sub_temp_95 = shiftmul32_FixPt_sub_temp_94 - $signed({1'b0, b13});
  assign shiftmul32_FixPt_d2_9 = shiftmul32_FixPt_d2 <<< 1;
  assign shiftmul32_FixPt_sub_temp_96 = shiftmul32_FixPt_sub_temp_95 - $signed({1'b0, shiftmul32_FixPt_d2_9});
  assign shiftmul32_FixPt_sub_temp_97 = shiftmul32_FixPt_sub_temp_96 - $signed({1'b0, b2});
  assign shiftmul32_FixPt_d10_10 = shiftmul32_FixPt_d10 <<< 1;
  assign shiftmul32_FixPt_sub_temp_98 = shiftmul32_FixPt_sub_temp_97 - $signed({1'b0, shiftmul32_FixPt_d10_10});
  assign shiftmul32_FixPt_d12_9 = shiftmul32_FixPt_d12 <<< 1;
  assign shiftmul32_FixPt_add_temp_133 = shiftmul32_FixPt_sub_temp_98 + $signed({1'b0, shiftmul32_FixPt_d12_9});
  assign y29 = shiftmul32_FixPt_add_temp_133 + $signed({1'b0, b1});
  assign shiftmul32_FixPt_d16_10 = shiftmul32_FixPt_d16 <<< 1;
  assign shiftmul32_FixPt_d15_10 = shiftmul32_FixPt_d15 <<< 1;
  assign shiftmul32_FixPt_add_temp_134 = ( - (shiftmul32_FixPt_d16_10)) + $signed({1'b0, shiftmul32_FixPt_d15_10});
  assign shiftmul32_FixPt_add_temp_135 = shiftmul32_FixPt_add_temp_134 + $signed({1'b0, b13});
  assign shiftmul32_FixPt_d12_10 = shiftmul32_FixPt_d12 <<< 1;
  assign shiftmul32_FixPt_sub_temp_99 = shiftmul32_FixPt_add_temp_135 - $signed({1'b0, shiftmul32_FixPt_d12_10});
  assign shiftmul32_FixPt_d11_10 = shiftmul32_FixPt_d11 <<< 1;
  assign shiftmul32_FixPt_add_temp_136 = shiftmul32_FixPt_sub_temp_99 + $signed({1'b0, shiftmul32_FixPt_d11_10});
  assign shiftmul32_FixPt_sub_temp_100 = shiftmul32_FixPt_add_temp_136 - $signed({1'b0, b10});
  assign shiftmul32_FixPt_d9_10 = shiftmul32_FixPt_d9 <<< 1;
  assign shiftmul32_FixPt_add_temp_137 = shiftmul32_FixPt_sub_temp_100 + $signed({1'b0, shiftmul32_FixPt_d9_10});
  assign shiftmul32_FixPt_add_temp_138 = shiftmul32_FixPt_add_temp_137 + $signed({1'b0, b9});
  assign shiftmul32_FixPt_sub_temp_101 = shiftmul32_FixPt_add_temp_138 - $signed({1'b0, b8});
  assign shiftmul32_FixPt_d7_10 = shiftmul32_FixPt_d7 <<< 1;
  assign shiftmul32_FixPt_add_temp_139 = shiftmul32_FixPt_sub_temp_101 + $signed({1'b0, shiftmul32_FixPt_d7_10});
  assign shiftmul32_FixPt_d6_10 = shiftmul32_FixPt_d6 <<< 1;
  assign shiftmul32_FixPt_sub_temp_102 = shiftmul32_FixPt_add_temp_139 - $signed({1'b0, shiftmul32_FixPt_d6_10});
  assign shiftmul32_FixPt_sub_temp_103 = shiftmul32_FixPt_sub_temp_102 - $signed({1'b0, b6});
  assign shiftmul32_FixPt_d5_10 = shiftmul32_FixPt_d5 <<< 1;
  assign shiftmul32_FixPt_add_temp_140 = shiftmul32_FixPt_sub_temp_103 + $signed({1'b0, shiftmul32_FixPt_d5_10});
  assign shiftmul32_FixPt_add_temp_141 = shiftmul32_FixPt_add_temp_140 + $signed({1'b0, b5});
  assign shiftmul32_FixPt_d4_10 = shiftmul32_FixPt_d4 <<< 1;
  assign shiftmul32_FixPt_sub_temp_104 = shiftmul32_FixPt_add_temp_141 - $signed({1'b0, shiftmul32_FixPt_d4_10});
  assign shiftmul32_FixPt_d3_10 = shiftmul32_FixPt_d3 <<< 1;
  assign shiftmul32_FixPt_add_temp_142 = shiftmul32_FixPt_sub_temp_104 + $signed({1'b0, shiftmul32_FixPt_d3_10});
  assign y31 = shiftmul32_FixPt_add_temp_142 - $signed({1'b0, b2});



  assign ce_out = clk_enable;

endmodule  // shiftmul32_FixPt

