-- -------------------------------------------------------------
-- 
-- File Name: G:\AI\IIT BHU\codegen\shiftmul16\hdlsrc\shiftmul16_FixPt.vhd
-- Created: 2016-06-01 22:01:17
-- 
-- Generated by MATLAB 8.1, MATLAB Coder 2.4 and HDL Coder 3.2
-- 
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Design base rate: 1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- y1                            ce_out        1
-- y3                            ce_out        1
-- y5                            ce_out        1
-- y7                            ce_out        1
-- y9                            ce_out        1
-- y11                           ce_out        1
-- y13                           ce_out        1
-- y15                           ce_out        1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: shiftmul16_FixPt
-- Source Path: shiftmul16_FixPt
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY shiftmul16_FixPt IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        b1                                :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        b2                                :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        b3                                :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        b4                                :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        b5                                :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        b6                                :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        b7                                :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        b8                                :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        ce_out                            :   OUT   std_logic;
        y1                                :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
        y3                                :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
        y5                                :   OUT   std_logic_vector(6 DOWNTO 0);  -- ufix7
        y7                                :   OUT   std_logic;  -- ufix1
        y9                                :   OUT   std_logic_vector(5 DOWNTO 0);  -- ufix6
        y11                               :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
        y13                               :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
        y15                               :   OUT   std_logic_vector(5 DOWNTO 0)  -- ufix6
        );
END shiftmul16_FixPt;


ARCHITECTURE rtl OF shiftmul16_FixPt IS

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL b1_unsigned                      : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL b2_unsigned                      : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL b3_unsigned                      : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL b4_unsigned                      : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL b5_unsigned                      : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL b6_unsigned                      : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL b7_unsigned                      : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL b8_unsigned                      : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL y1_tmp                           : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL y3_tmp                           : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL y5_tmp                           : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL y9_tmp                           : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL y11_tmp                          : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL y13_tmp                          : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL y15_tmp                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL shiftmul16_FixPt_d1              : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul16_FixPt_d2              : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul16_FixPt_d3              : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul16_FixPt_d4              : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul16_FixPt_d5              : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul16_FixPt_d6              : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul16_FixPt_d7              : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul16_FixPt_d8              : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul16_FixPt_cast            : signed(7 DOWNTO 0);  -- int8
  SIGNAL shiftmul16_FixPt_cast_1          : signed(7 DOWNTO 0);  -- int8
  SIGNAL shiftmul16_FixPt_cast_2          : signed(7 DOWNTO 0);  -- int8
  SIGNAL shiftmul16_FixPt_cast_3          : signed(7 DOWNTO 0);  -- int8
  SIGNAL shiftmul16_FixPt_cast_4          : signed(7 DOWNTO 0);  -- int8
  SIGNAL shiftmul16_FixPt_cast_5          : signed(7 DOWNTO 0);  -- int8
  SIGNAL shiftmul16_FixPt_cast_6          : signed(7 DOWNTO 0);  -- int8
  SIGNAL shiftmul16_FixPt_cast_7          : signed(7 DOWNTO 0);  -- int8
  SIGNAL shiftmul16_FixPt_d6_1            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul16_FixPt_cast_8          : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL shiftmul16_FixPt_d1_1            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul16_FixPt_add_cast        : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL shiftmul16_FixPt_sub_cast        : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL shiftmul16_FixPt_d7_1            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul16_FixPt_sub_cast_1      : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL shiftmul16_FixPt_add_cast_1      : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL shiftmul16_FixPt_d4_1            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul16_FixPt_sub_cast_2      : signed(22 DOWNTO 0);  -- sfix23
  SIGNAL shiftmul16_FixPt_add_cast_2      : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL shiftmul16_FixPt_d8_1            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul16_FixPt_sub_cast_3      : signed(26 DOWNTO 0);  -- sfix27
  SIGNAL shiftmul16_FixPt_add_cast_3      : signed(28 DOWNTO 0);  -- sfix29
  SIGNAL shiftmul16_FixPt_add_temp        : signed(28 DOWNTO 0);  -- sfix29
  SIGNAL shiftmul16_FixPt_add_temp_1      : unsigned(27 DOWNTO 0);  -- ufix28
  SIGNAL shiftmul16_FixPt_d2_1            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul16_FixPt_cast_9          : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL shiftmul16_FixPt_d5_1            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul16_FixPt_sub_cast_4      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL shiftmul16_FixPt_sub_cast_5      : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL shiftmul16_FixPt_d6_2            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul16_FixPt_add_cast_4      : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL shiftmul16_FixPt_add_cast_5      : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL shiftmul16_FixPt_d1_2            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul16_FixPt_add_cast_6      : signed(22 DOWNTO 0);  -- sfix23
  SIGNAL shiftmul16_FixPt_add_cast_7      : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL shiftmul16_FixPt_d4_2            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul16_FixPt_add_cast_8      : signed(26 DOWNTO 0);  -- sfix27
  SIGNAL shiftmul16_FixPt_add_cast_9      : signed(28 DOWNTO 0);  -- sfix29
  SIGNAL shiftmul16_FixPt_add_temp_2      : signed(28 DOWNTO 0);  -- sfix29
  SIGNAL shiftmul16_FixPt_d8_2            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul16_FixPt_cast_10         : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL shiftmul16_FixPt_d7_2            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul16_FixPt_add_cast_10     : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL shiftmul16_FixPt_add_cast_11     : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL shiftmul16_FixPt_d6_3            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul16_FixPt_sub_cast_6      : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL shiftmul16_FixPt_add_cast_12     : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL shiftmul16_FixPt_d3_1            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul16_FixPt_add_cast_13     : signed(22 DOWNTO 0);  -- sfix23
  SIGNAL shiftmul16_FixPt_add_cast_14     : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL shiftmul16_FixPt_d2_2            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL shiftmul16_FixPt_sub_cast_7      : signed(26 DOWNTO 0);  -- sfix27
  SIGNAL shiftmul16_FixPt_add_cast_15     : signed(28 DOWNTO 0);  -- sfix29
  SIGNAL shiftmul16_FixPt_add_temp_3      : signed(28 DOWNTO 0);  -- sfix29

BEGIN
  b1_unsigned <= unsigned(b1);

  b2_unsigned <= unsigned(b2);

  b3_unsigned <= unsigned(b3);

  b4_unsigned <= unsigned(b4);

  b5_unsigned <= unsigned(b5);

  b6_unsigned <= unsigned(b6);

  b7_unsigned <= unsigned(b7);

  b8_unsigned <= unsigned(b8);

  enb <= clk_enable;

  --spssa
  --%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  --                                                                          %
  --        Generated by MATLAB 8.1, MATLAB Coder 2.4 and HDL Coder 3.2      %
  --                                                                          %
  --%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  shiftmul16_FixPt_cast <= signed(resize(b1_unsigned, 8));
  shiftmul16_FixPt_d1 <= unsigned(shiftmul16_FixPt_cast(1 DOWNTO 0));
  shiftmul16_FixPt_cast_1 <= signed(resize(b2_unsigned, 8));
  shiftmul16_FixPt_d2 <= unsigned(shiftmul16_FixPt_cast_1(1 DOWNTO 0));
  shiftmul16_FixPt_cast_2 <= signed(resize(b3_unsigned, 8));
  shiftmul16_FixPt_d3 <= unsigned(shiftmul16_FixPt_cast_2(1 DOWNTO 0));
  shiftmul16_FixPt_cast_3 <= signed(resize(b4_unsigned, 8));
  shiftmul16_FixPt_d4 <= unsigned(shiftmul16_FixPt_cast_3(1 DOWNTO 0));
  shiftmul16_FixPt_cast_4 <= signed(resize(b5_unsigned, 8));
  shiftmul16_FixPt_d5 <= unsigned(shiftmul16_FixPt_cast_4(1 DOWNTO 0));
  shiftmul16_FixPt_cast_5 <= signed(resize(b6_unsigned, 8));
  shiftmul16_FixPt_d6 <= unsigned(shiftmul16_FixPt_cast_5(1 DOWNTO 0));
  shiftmul16_FixPt_cast_6 <= signed(resize(b7_unsigned, 8));
  shiftmul16_FixPt_d7 <= unsigned(shiftmul16_FixPt_cast_6(1 DOWNTO 0));
  shiftmul16_FixPt_cast_7 <= signed(resize(b8_unsigned, 8));
  shiftmul16_FixPt_d8 <= unsigned(shiftmul16_FixPt_cast_7(1 DOWNTO 0));
  y1_tmp <= resize(resize(resize(resize(resize(resize(resize(resize(resize(shiftmul16_FixPt_d1 sll 1, 9) + resize(shiftmul16_FixPt_d2 sll 1, 9), 10) + resize(b2_unsigned, 10), 15) + resize(shiftmul16_FixPt_d4 sll 1, 15), 19) + resize(b5_unsigned, 19), 22) + resize(shiftmul16_FixPt_d6 sll 1, 22), 23) + resize(b6_unsigned, 23), 26) + resize(shiftmul16_FixPt_d7 sll 1, 26), 28) + resize(b8_unsigned, 28), 8);
  shiftmul16_FixPt_d6_1 <= shiftmul16_FixPt_d6 sll 1;
  shiftmul16_FixPt_cast_8 <= signed(resize(shiftmul16_FixPt_d6_1, 6));
  shiftmul16_FixPt_d1_1 <= shiftmul16_FixPt_d1 sll 1;
  shiftmul16_FixPt_add_cast <= signed(resize(shiftmul16_FixPt_d1_1, 10));
  shiftmul16_FixPt_sub_cast <= signed(resize(b5_unsigned, 11));
  shiftmul16_FixPt_d7_1 <= shiftmul16_FixPt_d7 sll 1;
  shiftmul16_FixPt_sub_cast_1 <= signed(resize(shiftmul16_FixPt_d7_1, 16));
  shiftmul16_FixPt_add_cast_1 <= signed(resize(b2_unsigned, 20));
  shiftmul16_FixPt_d4_1 <= shiftmul16_FixPt_d4 sll 1;
  shiftmul16_FixPt_sub_cast_2 <= signed(resize(shiftmul16_FixPt_d4_1, 23));
  shiftmul16_FixPt_add_cast_2 <= signed(resize(b4_unsigned, 24));
  shiftmul16_FixPt_d8_1 <= shiftmul16_FixPt_d8 sll 1;
  shiftmul16_FixPt_sub_cast_3 <= signed(resize(shiftmul16_FixPt_d8_1, 27));
  shiftmul16_FixPt_add_cast_3 <= signed(resize(b3_unsigned, 29));
  shiftmul16_FixPt_add_temp <= resize(resize(resize(resize(resize(resize(resize(resize( - (shiftmul16_FixPt_cast_8), 10) + shiftmul16_FixPt_add_cast, 11) - shiftmul16_FixPt_sub_cast, 16) - shiftmul16_FixPt_sub_cast_1, 20) + shiftmul16_FixPt_add_cast_1, 23) - shiftmul16_FixPt_sub_cast_2, 24) + shiftmul16_FixPt_add_cast_2, 27) - shiftmul16_FixPt_sub_cast_3, 29) + shiftmul16_FixPt_add_cast_3;
  y3_tmp <= unsigned(shiftmul16_FixPt_add_temp(3 DOWNTO 0));
  y5_tmp <= resize(resize(resize(resize(resize(resize(resize(resize(resize(shiftmul16_FixPt_d7 sll 1, 9) - resize(shiftmul16_FixPt_d4 sll 1, 9), 10) + resize(b4_unsigned, 10), 15) - resize(shiftmul16_FixPt_d3 sll 1, 15), 19) + resize(b6_unsigned, 19), 22) + resize(shiftmul16_FixPt_d8 sll 1, 22), 23) + resize(b8_unsigned, 23), 26) - resize(shiftmul16_FixPt_d5 sll 1, 26), 28) + resize(b2_unsigned, 28), 7);
  shiftmul16_FixPt_add_temp_1 <= resize(resize(resize(resize(resize(resize(resize(resize(shiftmul16_FixPt_d5 sll 1, 9) - resize(shiftmul16_FixPt_d3 sll 1, 9), 10) + resize(b3_unsigned, 10), 15) + resize(shiftmul16_FixPt_d1 sll 1, 15), 19) + resize(b8_unsigned, 19), 22) - resize(shiftmul16_FixPt_d2 sll 1, 22), 23) - resize(b2_unsigned, 23), 26) + resize(shiftmul16_FixPt_d6 sll 1, 26), 28) + resize(b4_unsigned, 28);
  y7 <= shiftmul16_FixPt_add_temp_1(0);
  y9_tmp <= resize(resize(resize(resize(resize(resize(resize(resize(resize(shiftmul16_FixPt_d4 sll 1, 9) - resize(shiftmul16_FixPt_d6 sll 1, 9), 10) + resize(b6_unsigned, 10), 15) + resize(shiftmul16_FixPt_d8 sll 1, 15), 19) + resize(b1_unsigned, 19), 22) + resize(shiftmul16_FixPt_d7 sll 1, 22), 23) + resize(b7_unsigned, 23), 26) - resize(shiftmul16_FixPt_d3 sll 1, 26), 28) - resize(b5_unsigned, 28), 6);
  shiftmul16_FixPt_d2_1 <= shiftmul16_FixPt_d2 sll 1;
  shiftmul16_FixPt_cast_9 <= signed(resize(shiftmul16_FixPt_d2_1, 6));
  shiftmul16_FixPt_d5_1 <= shiftmul16_FixPt_d5 sll 1;
  shiftmul16_FixPt_sub_cast_4 <= signed(resize(shiftmul16_FixPt_d5_1, 10));
  shiftmul16_FixPt_sub_cast_5 <= signed(resize(b5_unsigned, 11));
  shiftmul16_FixPt_d6_2 <= shiftmul16_FixPt_d6 sll 1;
  shiftmul16_FixPt_add_cast_4 <= signed(resize(shiftmul16_FixPt_d6_2, 16));
  shiftmul16_FixPt_add_cast_5 <= signed(resize(b5_unsigned, 20));
  shiftmul16_FixPt_d1_2 <= shiftmul16_FixPt_d1 sll 1;
  shiftmul16_FixPt_add_cast_6 <= signed(resize(shiftmul16_FixPt_d1_2, 23));
  shiftmul16_FixPt_add_cast_7 <= signed(resize(b1_unsigned, 24));
  shiftmul16_FixPt_d4_2 <= shiftmul16_FixPt_d4 sll 1;
  shiftmul16_FixPt_add_cast_8 <= signed(resize(shiftmul16_FixPt_d4_2, 27));
  shiftmul16_FixPt_add_cast_9 <= signed(resize(b7_unsigned, 29));
  shiftmul16_FixPt_add_temp_2 <= resize(resize(resize(resize(resize(resize(resize(resize( - (shiftmul16_FixPt_cast_9), 10) - shiftmul16_FixPt_sub_cast_4, 11) - shiftmul16_FixPt_sub_cast_5, 16) + shiftmul16_FixPt_add_cast_4, 20) + shiftmul16_FixPt_add_cast_5, 23) + shiftmul16_FixPt_add_cast_6, 24) + shiftmul16_FixPt_add_cast_7, 27) + shiftmul16_FixPt_add_cast_8, 29) + shiftmul16_FixPt_add_cast_9;
  y11_tmp <= unsigned(shiftmul16_FixPt_add_temp_2(7 DOWNTO 0));
  y13_tmp <= resize(resize(resize(resize(resize(resize(resize(resize(resize(shiftmul16_FixPt_d3 sll 1, 9) + resize(shiftmul16_FixPt_d8 sll 1, 9), 10) + resize(b8_unsigned, 10), 15) - resize(shiftmul16_FixPt_d2 sll 1, 15), 19) - resize(b7_unsigned, 19), 22) + resize(shiftmul16_FixPt_d5 sll 1, 22), 23) + resize(b5_unsigned, 23), 26) + resize(shiftmul16_FixPt_d1 sll 1, 26), 28) + resize(b6_unsigned, 28), 8);
  shiftmul16_FixPt_d8_2 <= shiftmul16_FixPt_d8 sll 1;
  shiftmul16_FixPt_cast_10 <= signed(resize(shiftmul16_FixPt_d8_2, 6));
  shiftmul16_FixPt_d7_2 <= shiftmul16_FixPt_d7 sll 1;
  shiftmul16_FixPt_add_cast_10 <= signed(resize(shiftmul16_FixPt_d7_2, 10));
  shiftmul16_FixPt_add_cast_11 <= signed(resize(b7_unsigned, 11));
  shiftmul16_FixPt_d6_3 <= shiftmul16_FixPt_d6 sll 1;
  shiftmul16_FixPt_sub_cast_6 <= signed(resize(shiftmul16_FixPt_d6_3, 16));
  shiftmul16_FixPt_add_cast_12 <= signed(resize(b4_unsigned, 20));
  shiftmul16_FixPt_d3_1 <= shiftmul16_FixPt_d3 sll 1;
  shiftmul16_FixPt_add_cast_13 <= signed(resize(shiftmul16_FixPt_d3_1, 23));
  shiftmul16_FixPt_add_cast_14 <= signed(resize(b3_unsigned, 24));
  shiftmul16_FixPt_d2_2 <= shiftmul16_FixPt_d2 sll 1;
  shiftmul16_FixPt_sub_cast_7 <= signed(resize(shiftmul16_FixPt_d2_2, 27));
  shiftmul16_FixPt_add_cast_15 <= signed(resize(b1_unsigned, 29));
  shiftmul16_FixPt_add_temp_3 <= resize(resize(resize(resize(resize(resize(resize(resize( - (shiftmul16_FixPt_cast_10), 10) + shiftmul16_FixPt_add_cast_10, 11) + shiftmul16_FixPt_add_cast_11, 16) - shiftmul16_FixPt_sub_cast_6, 20) + shiftmul16_FixPt_add_cast_12, 23) + shiftmul16_FixPt_add_cast_13, 24) + shiftmul16_FixPt_add_cast_14, 27) - shiftmul16_FixPt_sub_cast_7, 29) + shiftmul16_FixPt_add_cast_15;
  y15_tmp <= unsigned(shiftmul16_FixPt_add_temp_3(5 DOWNTO 0));

  y1 <= std_logic_vector(y1_tmp);

  y3 <= std_logic_vector(y3_tmp);

  y5 <= std_logic_vector(y5_tmp);

  y9 <= std_logic_vector(y9_tmp);

  y11 <= std_logic_vector(y11_tmp);

  y13 <= std_logic_vector(y13_tmp);

  y15 <= std_logic_vector(y15_tmp);

  ce_out <= clk_enable;

END rtl;

