// -------------------------------------------------------------
// 
// File Name: G:\AI\IIT BHU\codegen\shiftmul1\hdlsrc\shiftmul1_FixPt.v
// Created: 2016-05-31 10:50:16
// 
// Generated by MATLAB 8.1, MATLAB Coder 2.4 and HDL Coder 3.2
// 
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Design base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Y1                            ce_out        1
// Y3                            ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: shiftmul1_FixPt
// Source Path: shiftmul1_FixPt
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module shiftmul1_FixPt
          (
           clk,
           reset,
           clk_enable,
           data1,
           data2,
           ce_out,
           Y1,
           Y3
          );


  input   clk;
  input   reset;
  input   clk_enable;
  input   [4:0] data1;  // ufix5
  input   [5:0] data2;  // ufix6
  output  ce_out;
  output  [7:0] Y1;  // ufix8
  output  signed [6:0] Y3;  // sfix7


  wire enb;
  wire [4:0] shiftmul1_FixPt_d1;  // ufix5
  wire [5:0] shiftmul1_FixPt_d2;  // ufix6
  wire [4:0] shiftmul1_FixPt_d1_1;  // ufix5
  wire [6:0] shiftmul1_FixPt_add_temp;  // ufix7
  wire [4:0] shiftmul1_FixPt_d1_2;  // ufix5
  wire [7:0] shiftmul1_FixPt_add_temp_1;  // ufix8
  wire [5:0] shiftmul1_FixPt_d2_1;  // ufix6
  wire [5:0] shiftmul1_FixPt_d2_2;  // ufix6
  wire [6:0] shiftmul1_FixPt_add_temp_2;  // ufix7
  wire [4:0] shiftmul1_FixPt_d1_3;  // ufix5
  wire [5:0] shiftmul1_FixPt_d2_3;  // ufix6
  wire [7:0] shiftmul1_FixPt_add_temp_3;  // ufix8
  wire [5:0] shiftmul1_FixPt_d2_4;  // ufix6
  wire [8:0] shiftmul1_FixPt_add_temp_4;  // ufix9
  wire signed [5:0] shiftmul1_FixPt_sub_cast;  // sfix6


  assign enb = clk_enable;

  //spssa
  //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  //                                                                          %
  //        Generated by MATLAB 8.1, MATLAB Coder 2.4 and HDL Coder 3.2      %
  //                                                                          %
  //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  assign shiftmul1_FixPt_d1 = data1;
  assign shiftmul1_FixPt_d2 = data2;
  assign shiftmul1_FixPt_d1_1 = shiftmul1_FixPt_d1 <<< 4;
  assign shiftmul1_FixPt_add_temp = data1 + shiftmul1_FixPt_d1_1;
  assign shiftmul1_FixPt_d1_2 = shiftmul1_FixPt_d1 <<< 1;
  assign shiftmul1_FixPt_add_temp_1 = shiftmul1_FixPt_add_temp + shiftmul1_FixPt_d1_2;
  assign shiftmul1_FixPt_d2_1 = shiftmul1_FixPt_d2 <<< 5;
  assign shiftmul1_FixPt_d2_2 = shiftmul1_FixPt_d2 <<< 1;
  assign shiftmul1_FixPt_add_temp_2 = shiftmul1_FixPt_d2_1 + shiftmul1_FixPt_d2_2;
  assign Y1 = shiftmul1_FixPt_add_temp_1 + shiftmul1_FixPt_add_temp_2;
  assign shiftmul1_FixPt_d1_3 = shiftmul1_FixPt_d1 <<< 1;
  assign shiftmul1_FixPt_d2_3 = shiftmul1_FixPt_d2 <<< 4;
  assign shiftmul1_FixPt_add_temp_3 = data1 + shiftmul1_FixPt_d2_3;
  assign shiftmul1_FixPt_d2_4 = shiftmul1_FixPt_d2 <<< 1;
  assign shiftmul1_FixPt_add_temp_4 = shiftmul1_FixPt_add_temp_3 + shiftmul1_FixPt_d2_4;
  assign shiftmul1_FixPt_sub_cast = $signed(shiftmul1_FixPt_add_temp_4[5:0]);
  assign Y3 = $signed({1'b0, shiftmul1_FixPt_d1_3}) - shiftmul1_FixPt_sub_cast;



  assign ce_out = clk_enable;

endmodule  // shiftmul1_FixPt

